var m,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ca=ba(this),da="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");ca.BigInt64Array&&(da.push("BigInt64"),da.push("BigUint64"));
function q(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&p(c,a,{configurable:!0,writable:!0,value:b})}}var ea;if(typeof Object.setPrototypeOf=="function")ea=Object.setPrototypeOf;else{var fa;a:{var ha={a:!0},ia={};try{ia.__proto__=ha;fa=ia.a;break a}catch(a){}fa=!1}ea=fa?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=ea;
function ka(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ja)ja(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.L=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function r(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function t(a){return u(a,a)}function u(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function v(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function ma(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
q("globalThis",function(a){return a||ca});q("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,k){this.fa=f;p(this,"description",{configurable:!0,writable:!0,value:k})}if(a)return a;c.prototype.toString=function(){return this.fa};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return na(la(this))}});return a});function na(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}q("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
q("WeakMap",function(a){function b(g){this.K=(h+=Math.random()+1).toString();if(g){g=r(g);for(var l;!(l=g.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(g){var l=typeof g;return l==="object"&&g!==null||l==="function"}function e(g){if(!v(g,k)){var l=new c;p(g,k,{value:l})}}function f(g){var l=Object[g];l&&(Object[g]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return l(n)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),l=Object.seal({}),
n=new a([[g,2],[l,3]]);if(n.get(g)!=2||n.get(l)!=3)return!1;n.delete(g);n.set(l,4);return!n.has(g)&&n.get(l)==4}catch(F){return!1}}())return a;var k="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(g,l){if(!d(g))throw Error("Invalid WeakMap key");e(g);if(!v(g,k))throw Error("WeakMap key fail: "+g);g[k][this.K]=l;return this};b.prototype.get=function(g){return d(g)&&v(g,k)?g[k][this.K]:void 0};b.prototype.has=function(g){return d(g)&&v(g,
k)&&v(g[k],this.K)};b.prototype.delete=function(g){return d(g)&&v(g,k)&&v(g[k],this.K)?delete g[k][this.K]:!1};return b});
q("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,g){var l=h[1];return na(function(){if(l){for(;l.head!=h[1];)l=l.previous;for(;l.next!=l.head;)return l=l.next,{done:!1,value:g(l)};l=null}return{done:!0,value:void 0}})}function d(h,g){var l=g&&typeof g;l=="object"||l=="function"?f.has(g)?l=f.get(g):(l=""+ ++k,f.set(g,l)):l="p_"+g;var n=h[0][l];if(n&&v(h[0],l))for(h=0;h<n.length;h++){var F=n[h];if(g!==g&&F.key!==F.key||g===F.key)return{id:l,list:n,index:h,entry:F}}return{id:l,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=r(h);for(var g;!(g=h.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),g=new a(r([[h,"s"]]));if(g.get(h)!="s"||g.size!=1||g.get({x:4})||g.set({x:4},"t")!=g||g.size!=2)return!1;var l=g.entries(),n=l.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=l.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!l.next().done?!1:!0}catch(F){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,g){h=h===0?0:h;var l=d(this,h);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=g:(l.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:g},l.list.push(l.entry),this[1].previous.next=l.entry,this[1].previous=l.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,g){for(var l=this.entries(),n;!(n=l.next()).done;)n=n.value,h.call(g,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});q("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)v(b,d)&&c.push(b[d]);return c}});
q("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});
function oa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});q("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var w=this||self;function pa(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}function x(a){var b=pa(a);return b=="array"||b=="object"&&typeof a.length=="number"}function y(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}var qa="closure_uid_"+(Math.random()*1E9>>>0),ra=0;function sa(a,b,c){return a.call.apply(a.bind,arguments)}
function ta(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function ua(a,b,c){ua=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?sa:ta;return ua.apply(null,arguments)}
function z(a,b){function c(){}c.prototype=b.prototype;a.L=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Eb=function(d,e,f){for(var k=Array(arguments.length-2),h=2;h<arguments.length;h++)k[h-2]=arguments[h];return b.prototype[e].apply(d,k)}};function A(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,A);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}z(A,Error);A.prototype.name="CustomError";var B;function C(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");A.call(this,c+a[d])}z(C,A);C.prototype.name="AssertionError";function va(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new C(""+e,f||[]);}function D(a,b,c){a||va("",null,b,Array.prototype.slice.call(arguments,2));return a}function wa(a,b,c){a==null&&va("Expected to exist: %s.",[a],b,Array.prototype.slice.call(arguments,2));return a}
function xa(a,b){throw new C("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));}function E(a,b,c){typeof a!=="number"&&va("Expected number but got %s: %s.",[pa(a),a],b,Array.prototype.slice.call(arguments,2));return a}function ya(a,b,c){Array.isArray(a)||va("Expected array but got %s: %s.",[pa(a),a],b,Array.prototype.slice.call(arguments,2));return a};function za(){var a=w.navigator;return a&&(a=a.userAgent)?a:""};var Aa=Array.prototype.indexOf?function(a,b){D(a.length!=null);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ba=Array.prototype.forEach?function(a,b){D(a.length!=null);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Ca(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Da=za().toLowerCase().indexOf("webkit")!=-1&&za().indexOf("Edge")==-1;var Ea=typeof Symbol==="function"&&typeof Symbol()==="symbol",Fa;Fa=typeof Symbol==="function"&&typeof Symbol()==="symbol"?Symbol.for?Symbol.for("jas"):Symbol("jas"):void 0;var Ga=Math,Ha=Ga.round,Ia=Math,Ja=Ia.log2,Ka=Math.max,La=Ka.apply,Ma=Object.values({Ua:1,Ta:2,Sa:4,hb:8,yb:16,eb:32,xa:64,Oa:128,Ja:256,wb:512,Ka:1024,Pa:2048,fb:4096,Va:8192}),Na;if(Ma instanceof Array)Na=Ma;else{for(var Oa=r(Ma),Pa,Qa=[];!(Pa=Oa.next()).done;)Qa.push(Pa.value);Na=Qa}D(Ha.call(Ga,Ja.call(Ia,La.call(Ka,Math,Na)))===13);var Ra=Ea?wa(Fa):"Fb",Sa=Object.getOwnPropertyDescriptor(Array.prototype,"na");
Object.defineProperties(Array.prototype,{na:{get:function(){var a=Ta(this);return Sa?Sa.get.call(this)+"|"+a:a},configurable:!0,enumerable:!1}});
function Ta(a){function b(e,f){e&c&&d.push(f)}var c=ya(a,"state is only maintained on arrays.")[Ra]|0,d=[];b(1,"IS_REPEATED_FIELD");b(2,"IS_IMMUTABLE_ARRAY");b(4,"IS_API_FORMATTED");b(512,"STRING_FORMATTED");b(1024,"GBIGINT_FORMATTED");b(1024,"BINARY");b(8,"ONLY_MUTABLE_VALUES");b(16,"UNFROZEN_SHARED");b(32,"MUTABLE_REFERENCES_ARE_OWNED");b(64,"CONSTRUCTED");b(128,"HAS_MESSAGE_ID");b(256,"FROZEN_ARRAY");b(2048,"HAS_WRAPPER");b(4096,"MUTABLE_SUBSTRUCTURES");b(8192,"KNOWN_MAP_ARRAY");c&64&&(D(c&64),
a=c>>14&1023||536870912,a!==536870912&&d.push("pivot: "+a));return d.join(",")};var Ua=typeof Symbol!="undefined"&&typeof Symbol.hasInstance!="undefined";Object.freeze({});function Va(){throw Error("please construct maps as mutable then call toImmutable");}if(Ua){var Wa=function(){throw Error("Cannot perform instanceof checks on ImmutableMap: please use isImmutableMap or isMutableMap to assert on the mutability of a map. See go/jspb-api-gotchas#immutable-classes for more information");},Xa={};Object.defineProperties(Va,(Xa[Symbol.hasInstance]={value:Wa,configurable:!1,writable:!1,enumerable:!1},Xa));D(Va[Symbol.hasInstance]===Wa,"defineProperties did not work: was it monkey-patched?")};if(typeof Proxy!=="undefined"){var G=Ya;new Proxy({},{getPrototypeOf:G,setPrototypeOf:G,isExtensible:G,preventExtensions:G,getOwnPropertyDescriptor:G,defineProperty:G,has:G,get:G,set:G,deleteProperty:G,apply:G,construct:G})}function Ya(){throw Error("this array or object is owned by JSPB and should not be reused, did you mean to copy it with copyJspbArray? See go/jspb-api-gotchas#construct_from_array");};D(!0);function Za(){};(function(){var a=w.jspbGetTypeName;w.jspbGetTypeName=a?function(b){return a(b)||void 0}:Za})();Object.create(null);globalThis.$J2CL_PRESERVE$=function(){};var $a={qa:"activedescendant",ra:"atomic",sa:"autocomplete",ta:"busy",va:"checked",wa:"colindex",ya:"controls",za:"current",Ba:"describedby",DISABLED:"disabled",Ca:"dropeffect",Fa:"expanded",Ga:"flowto",La:"grabbed",Na:"haspopup",Qa:"hidden",Ra:"invalid",Wa:"label",Xa:"labelledby",Ya:"level",Za:"live",ab:"multiline",bb:"multiselectable",ib:"orientation",jb:"owns",lb:"posinset",mb:"pressed",nb:"readonly",pb:"relevant",qb:"required",rb:"rowindex",sb:"selected",tb:"setsize",ub:"sort",zb:"valuemax",Ab:"valuemin",
Bb:"valuenow",Cb:"valuetext"};var ab;function bb(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function cb(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var db={};function eb(){if(db!==db)throw Error("Bad secret");};var fb=globalThis.trustedTypes,gb;function hb(){var a=null;if(!fb)return a;try{var b=function(c){return c};a=fb.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){throw c;}return a}function ib(){gb===void 0&&(gb=hb());return gb};function jb(a){eb();this.oa=a}jb.prototype.toString=function(){return this.oa+""};function kb(a){var b=ib();a=b?b.createScriptURL(a):a;return new jb(a)};var lb=t([""]),mb=u(["\x00"],["\\0"]),nb=u(["\n"],["\\n"]),ob=u(["\x00"],["\\u0000"]),pb=t([""]),qb=u(["\x00"],["\\0"]),rb=u(["\n"],["\\n"]),sb=u(["\x00"],["\\u0000"]);
function tb(a,b){if(!Array.isArray(a)||!Array.isArray(a.raw)||a.length!==a.raw.length||!ub&&a===a.raw||!(ub&&!vb||H(a))||b+1!==a.length)throw new TypeError("\n    ############################## ERROR ##############################\n\n    It looks like you are trying to call a template tag function (fn`...`)\n    using the normal function syntax (fn(...)), which is not supported.\n\n    The functions in the safevalues library are not designed to be called\n    like normal functions, and doing so invalidates the security guarantees\n    that safevalues provides.\n\n    If you are stuck and not sure how to proceed, please reach out to us\n    instead through:\n     - go/ise-hardening-yaqs (preferred) // LINE-INTERNAL\n     - g/ise-hardening // LINE-INTERNAL\n     - https://github.com/google/safevalues/issues\n\n    ############################## ERROR ##############################");}
function H(a){return Object.isFrozen(a)&&Object.isFrozen(a.raw)}function wb(a){return a.toString().indexOf("`")===-1}var ub=wb(function(a){return a(lb)})||wb(function(a){return a(mb)})||wb(function(a){return a(nb)})||wb(function(a){return a(ob)}),vb=H(pb)&&H(qb)&&H(rb)&&H(sb);function I(a){eb();this.da=a}I.prototype.toString=function(){return this.da};new I("about:blank");new I("about:invalid#zClosurez");function xb(a){this.ma=a}function J(a){return new xb(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var yb=[J("data"),J("http"),J("https"),J("mailto"),J("ftp"),new xb(function(a){return/^[^:]*([/?#]|$)/.test(a)})],zb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i,Ab=[];function Bb(){}Cb(function(a){console.warn("A URL with content '"+a+"' was sanitized away.")});function Cb(a){Ab.indexOf(a)===-1&&Ab.push(a);Bb=function(b){Ab.forEach(function(c){c(b)})}};function K(a){eb();this.ca=a}K.prototype.toString=function(){return this.ca+""};function Db(a){var b=ib();a=b?b.createHTML(a):a;return new K(a)};var Eb={Ia:0,Da:1,Ea:2,0:"FORMATTED_HTML_CONTENT",1:"EMBEDDED_INTERNAL_CONTENT",2:"EMBEDDED_TRUSTED_EXTERNAL_CONTENT"};function Fb(a,b){b=Error.call(this,a+" cannot be used with intent "+Eb[b]);this.message=b.message;"stack"in b&&(this.stack=b.stack);this.type=a;this.name="TypeCannotBeUsedWithIframeIntentError"}ka(Fb,Error);function Gb(a){if(a instanceof K)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");return Db(a)};function L(a){var b=ma.apply(1,arguments);tb(a,b.length);if(b.length===0)return kb(a[0]);var c=a[0].toLowerCase();if(/^data:/.test(c))throw Error("Data URLs cannot have expressions in the template literal input.");if(/^https:\/\//.test(c)||/^\/\//.test(c)){var d=c.indexOf("//")+2;var e=c.indexOf("/",d);if(e<=d)throw Error("Can't interpolate data in a url's origin, Please make sure to fully specify the origin, terminated with '/'.");d=c.substring(d,e);if(!/^[0-9a-z.:-]+$/i.test(d))throw Error("The origin contains unsupported characters.");
if(!/^[^:]*(:[0-9]+)?$/i.test(d))throw Error("Invalid port number.");if(!/(^|\.)[a-z][^.]*$/i.test(d))throw Error("The top-level domain must start with a letter.");d=!0}else d=!1;if(!d)if(/^\//.test(c))if(c==="/"||c.length>1&&c[1]!=="/"&&c[1]!=="\\")d=!0;else throw Error("The path start in the url is invalid.");else d=!1;if(!(d=d||RegExp("^[^:\\s\\\\/]+/").test(c)))if(/^about:blank/.test(c)){if(c!=="about:blank"&&!/^about:blank#/.test(c))throw Error("The about url is invalid.");d=!0}else d=!1;if(!d)throw Error("Trying to interpolate expressions in an unsupported url format.");
c=a[0];for(d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return kb(c)};var Hb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function Ib(a,b,c){function d(h){h&&b.appendChild(typeof h==="string"?a.createTextNode(h):h)}for(var e=1;e<c.length;e++){var f=c[e];if(!x(f)||y(f)&&f.nodeType>0)d(f);else{a:{if(f&&typeof f.length=="number"){if(y(f)){var k=typeof f.item=="function"||typeof f.item=="string";break a}if(typeof f==="function"){k=typeof f.item=="function";break a}}k=!1}Ba(k?Ca(f):f,d)}}}function Jb(a){D(a,"Node cannot be null or undefined.");return a.nodeType==9?a:a.ownerDocument||a.document}
function Kb(){this.H=w.document||document}m=Kb.prototype;m.getElementsByTagName=function(a,b){return(b||this.H).getElementsByTagName(String(a))};m.setProperties=function(a,b){bb(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:Hb.hasOwnProperty(d)?a.setAttribute(Hb[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})};
m.createElement=function(a){var b=this.H;a=String(a);b.contentType==="application/xhtml+xml"&&(a=a.toLowerCase());return b.createElement(a)};m.createTextNode=function(a){return this.H.createTextNode(String(a))};m.getWindow=function(){return this.H.defaultView};m.appendChild=function(a,b){D(a!=null&&b!=null,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};m.append=function(a,b){Ib(Jb(a),a,arguments)};m.canHaveChildren=function(a){if(a.nodeType!=1)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
m.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};m.getChildren=function(a){return a.children!=void 0?a.children:Array.prototype.filter.call(a.childNodes,function(b){return b.nodeType==1})};m.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function Lb(a,b,c){Array.isArray(c)&&(c=c.join(" "));var d=Mb(b);c===""||c==void 0?(ab||(c={},ab=(c.atomic=!1,c.autocomplete="none",c.dropeffect="none",c.haspopup=!1,c.live="off",c.multiline=!1,c.multiselectable=!1,c.orientation="vertical",c.readonly=!1,c.relevant="additions text",c.required=!1,c.sort="none",c.busy=!1,c.disabled=!1,c.hidden=!1,c.invalid="false",c)),c=ab,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function Mb(a){D(a,"ARIA attribute cannot be empty.");a:{for(b in $a)if($a[b]==a){var b=!0;break a}b=!1}D(b,"No such ARIA attribute "+a);return"aria-"+a};function M(){this.G=this.G;this.P=this.P}M.prototype.G=!1;M.prototype.isDisposed=function(){return this.G};M.prototype.dispose=function(){this.G||(this.G=!0,this.S())};M.prototype[Symbol.dispose]=function(){this.dispose()};M.prototype.S=function(){if(this.P)for(;this.P.length;)this.P.shift()()};function Nb(a){M.call(this);this.I=a||B||(B=new Kb);this.O={};this.X={}}z(Nb,M);Nb.prototype.S=function(){bb(this.O,this.I.removeNode,this.I);this.X=this.I=this.O=null;Nb.L.S.call(this)};var Ob=[];function N(){this.ga=new Nb}
N.prototype.speak=function(a,b){var c=this.ga;b=b||"polite";var d;if(d=c.O[b])d.removeAttribute(Mb("hidden"));else{var e=d=c.I.createElement("DIV");var f=d;f=Object.prototype.hasOwnProperty.call(f,qa)&&f[qa]||(f[qa]=++ra);e.id="goog-lr-"+f;d.style.position="absolute";d.style.top="-1000px";d.style.height="1px";d.style.overflow="hidden";Lb(d,"live",b);Lb(d,"atomic","true");c.I.H.body.appendChild(d);c.O[b]=d}e=(e=c.X[b])&&e===a?a+"\u00a0":a;a&&(c.X[b]=e);D(d!=null,"goog.dom.setTextContent expects a non-null value for node");if("textContent"in
d)d.textContent=e;else if(d.nodeType==3)d.data=String(e);else if(d.firstChild&&d.firstChild.nodeType==3){for(;d.lastChild!=d.firstChild;)d.removeChild(D(d.lastChild));d.firstChild.data=String(e)}else{for(;a=d.firstChild;)d.removeChild(a);a=Jb(d);d.appendChild(a.createTextNode(String(e)))}};function Pb(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=!1}Pb.prototype.stopPropagation=function(){};Pb.prototype.preventDefault=function(){this.defaultPrevented=!0};var Qb=function(){if(!w.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};w.addEventListener("test",c,b);w.removeEventListener("test",c,b)}catch(d){}return a}();function O(a,b){Pb.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.timeStamp=0;this.J=null;a&&this.init(a,b)}z(O,Pb);
O.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=Da||a.offsetX!==void 0?a.offsetX:a.layerX,this.offsetY=
Da||a.offsetY!==void 0?a.offsetY:a.layerY,this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.timeStamp=
a.timeStamp;this.J=a;a.defaultPrevented&&O.L.preventDefault.call(this)};O.prototype.stopPropagation=function(){O.L.stopPropagation.call(this);this.J.stopPropagation?this.J.stopPropagation():this.J.cancelBubble=!0};O.prototype.preventDefault=function(){O.L.preventDefault.call(this);var a=this.J;a.preventDefault?a.preventDefault():a.returnValue=!1};var Rb="closure_listenable_"+(Math.random()*1E6|0);var Sb=0;function Tb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.U=e;this.key=++Sb;this.removed=this.R=!1}function Ub(a){a.removed=!0;a.listener=null;a.proxy=null;a.src=null;a.U=null};function P(a){this.src=a;this.l={};this.M=0}P.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.l[f];a||(a=this.l[f]=[],this.M++);var k=Vb(a,b,d,e);k>-1?(b=a[k],c||(b.R=!1)):(b=new Tb(b,this.src,f,!!d,e),b.R=c,a.push(b));return b};P.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.l))return!1;var e=this.l[a];b=Vb(e,b,c,d);return b>-1?(Ub(e[b]),D(e.length!=null),Array.prototype.splice.call(e,b,1),e.length==0&&(delete this.l[a],this.M--),!0):!1};
function Wb(a,b){var c=b.type;if(c in a.l){var d=a.l[c],e=Aa(d,b),f;if(f=e>=0)D(d.length!=null),Array.prototype.splice.call(d,e,1);f&&(Ub(b),a.l[c].length==0&&(delete a.l[c],a.M--))}}P.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.l)if(!a||c==a){for(var d=this.l[c],e=0;e<d.length;e++)++b,Ub(d[e]);delete this.l[c];this.M--}return b};
P.prototype.hasListener=function(a,b){var c=a!==void 0,d=c?a.toString():"",e=b!==void 0;return cb(this.l,function(f){for(var k=0;k<f.length;++k)if(!(c&&f[k].type!=d||e&&f[k].capture!=b))return!0;return!1})};function Vb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.listener==b&&f.capture==!!c&&f.U==d)return e}return-1};var Xb="closure_lm_"+(Math.random()*1E6|0),Yb={},Zb=0;function $b(a,b,c,d,e){if(d&&d.once)ac(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)$b(a,b[f],c,d,e);else c=bc(c),a&&a[Rb]?a.listen(b,c,y(d)?!!d.capture:!!d,e):cc(a,b,c,!1,d,e)}
function cc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=y(e)?!!e.capture:!!e,h=dc(a);h||(a[Xb]=h=new P(a));c=h.add(b,c,d,k,f);if(!c.proxy){d=ec();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Qb||(e=k),e===void 0&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(fc(b.toString()),d);else if(a.addListener&&a.removeListener)D(b==="change","MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");
Zb++}}function ec(){function a(c){return b.call(a.src,a.listener,c)}var b=hc;return a}function ac(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)ac(a,b[f],c,d,e);else c=bc(c),a&&a[Rb]?a.ja.add(String(b),c,!0,y(d)?!!d.capture:!!d,e):cc(a,b,c,!0,d,e)}function fc(a){return a in Yb?Yb[a]:Yb[a]="on"+a}
function hc(a,b){if(a.removed)a=!0;else{b=new O(b,this);var c=a.listener,d=a.U||a.src;if(a.R&&typeof a!=="number"&&a&&!a.removed){var e=a.src;if(e&&e[Rb])Wb(e.ja,a);else{var f=a.type,k=a.proxy;e.removeEventListener?e.removeEventListener(f,k,a.capture):e.detachEvent?e.detachEvent(fc(f),k):e.addListener&&e.removeListener&&e.removeListener(k);Zb--;(f=dc(e))?(Wb(f,a),f.M==0&&(f.src=null,e[Xb]=null)):Ub(a)}}a=c.call(d,b)}return a}function dc(a){a=a[Xb];return a instanceof P?a:null}
var ic="__closure_events_fn_"+(Math.random()*1E9>>>0);function bc(a){D(a,"Listener can not be null.");if(typeof a==="function")return a;D(a.handleEvent,"An object listener must have handleEvent method.");a[ic]||(a[ic]=function(b){return a.handleEvent(b)});return a[ic]};function jc(a){if(a.C&&typeof a.C=="function")return a.C();if(typeof Map!=="undefined"&&a instanceof Map||typeof Set!=="undefined"&&a instanceof Set)return Array.from(a.values());if(typeof a==="string")return a.split("");if(x(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b}
function kc(a){if(a.T&&typeof a.T=="function")return a.T();if(!a.C||typeof a.C!="function"){if(typeof Map!=="undefined"&&a instanceof Map)return Array.from(a.keys());if(!(typeof Set!=="undefined"&&a instanceof Set)){if(x(a)||typeof a==="string"){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}}
function lc(a,b,c){if(a.forEach&&typeof a.forEach=="function")a.forEach(b,c);else if(x(a)||typeof a==="string")Array.prototype.forEach.call(a,b,c);else for(var d=kc(a),e=jc(a),f=e.length,k=0;k<f;k++)b.call(c,e[k],d&&d[k],a)};var mc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function nc(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function Q(a){this.v=this.D=this.A="";this.F=null;this.B=this.u="";this.m=this.la=!1;if(a instanceof Q){this.m=a.m;oc(this,a.A);var b=a.D;R(this);this.D=b;b=a.v;R(this);this.v=b;pc(this,a.F);b=a.u;R(this);this.u=b;qc(this,a.o.clone());a=a.B;R(this);this.B=a}else a&&(b=String(a).match(mc))?(this.m=!1,oc(this,b[1]||"",!0),a=b[2]||"",R(this),this.D=S(a),a=b[3]||"",R(this),this.v=S(a,!0),pc(this,b[4]),a=b[5]||"",R(this),this.u=S(a,!0),qc(this,b[6]||"",!0),a=b[7]||"",R(this),this.B=S(a)):(this.m=!1,this.o=
new T(null,this.m))}m=Q.prototype;m.toString=function(){var a=[],b=this.A;b&&a.push(U(b,rc,!0),":");var c=this.v;if(c||b=="file")a.push("//"),(b=this.D)&&a.push(U(b,rc,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.F,c!=null&&a.push(":",String(c));if(c=this.u)this.v&&c.charAt(0)!="/"&&a.push("/"),a.push(U(c,c.charAt(0)=="/"?sc:tc,!0));(c=this.o.toString())&&a.push("?",c);(c=this.B)&&a.push("#",U(c,uc));return a.join("")};
m.resolve=function(a){var b=this.clone(),c=!!a.A;c?oc(b,a.A):c=!!a.D;if(c){var d=a.D;R(b);b.D=d}else c=!!a.v;c?(d=a.v,R(b),b.v=d):c=a.F!=null;d=a.u;if(c)pc(b,a.F);else if(c=!!a.u){if(d.charAt(0)!="/")if(this.v&&!this.u)d="/"+d;else{var e=b.u.lastIndexOf("/");e!=-1&&(d=b.u.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var f=[],k=0;k<e.length;){var h=e[k++];h=="."?d&&k==e.length&&f.push(""):h==".."?((f.length>
1||f.length==1&&f[0]!="")&&f.pop(),d&&k==e.length&&f.push("")):(f.push(h),d=!0)}d=f.join("/")}else d=e}c?(R(b),b.u=d):c=a.o.toString()!=="";c?qc(b,a.o.clone()):c=!!a.B;c&&(a=a.B,R(b),b.B=a);return b};m.clone=function(){return new Q(this)};function oc(a,b,c){R(a);a.A=c?S(b,!0):b;a.A&&(a.A=a.A.replace(/:$/,""))}function pc(a,b){R(a);if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.F=b}else a.F=null}
function qc(a,b,c){R(a);b instanceof T?(a.o=b,a.o.Y(a.m)):(c||(b=U(b,vc)),a.o=new T(b,a.m))}m.getQuery=function(){return this.o.toString()};m.removeParameter=function(a){R(this);this.o.remove(a);return this};function R(a){if(a.la)throw Error("Tried to modify a read-only Uri");}m.Y=function(a){this.m=a;this.o&&this.o.Y(a)};function S(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""}
function U(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,wc),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function wc(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var rc=/[#\/\?@]/g,tc=/[#\?:]/g,sc=/[#\?]/g,vc=/[#\?@]/g,uc=/#/g;function T(a,b){this.i=this.g=null;this.j=a||null;this.m=!!b}function V(a){a.g||(a.g=new Map,a.i=0,a.j&&nc(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))}m=T.prototype;
m.add=function(a,b){V(this);this.j=null;a=W(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.i=E(this.i)+1;return this};m.remove=function(a){V(this);a=W(this,a);return this.g.has(a)?(this.j=null,this.i=E(this.i)-this.g.get(a).length,this.g.delete(a)):!1};m.clear=function(){this.g=this.j=null;this.i=0};function xc(a,b){V(a);b=W(a,b);return a.g.has(b)}m.forEach=function(a,b){V(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};
m.T=function(){V(this);for(var a=Array.from(this.g.values()),b=Array.from(this.g.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};m.C=function(a){V(this);var b=[];if(typeof a==="string")xc(this,a)&&(b=b.concat(this.g.get(W(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};
m.set=function(a,b){V(this);this.j=null;a=W(this,a);xc(this,a)&&(this.i=E(this.i)-this.g.get(a).length);this.g.set(a,[b]);this.i=E(this.i)+1;return this};m.get=function(a,b){if(!a)return b;a=this.C(a);return a.length>0?String(a[0]):b};
m.toString=function(){if(this.j)return this.j;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.C(d);for(var f=0;f<d.length;f++){var k=e;d[f]!==""&&(k+="="+encodeURIComponent(String(d[f])));a.push(k)}}return this.j=a.join("&")};m.clone=function(){var a=new T;a.j=this.j;this.g&&(a.g=new Map(this.g),a.i=this.i);return a};function W(a,b){b=String(b);a.m&&(b=b.toLowerCase());return b}
m.Y=function(a){a&&!this.m&&(V(this),this.j=null,this.g.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),b.length>0&&(this.j=null,this.g.set(W(this,d),Ca(b)),this.i=E(this.i)+b.length))},this));this.m=a};m.extend=function(a){for(var b=0;b<arguments.length;b++)lc(arguments[b],function(c,d){this.add(d,c)},this)};var yc=t(["https://fonts.gstatic.com/s/i/googlematerialicons/image_not_supported/v12/gm_grey-24dp/1x/gm_image_not_supported_gm_grey_24dp.png"]),zc=t(["https://www.gstatic.com/keep/backgrounds/grocery_light_thumb_0615.svg"]),Ac=t(["https://www.gstatic.com/keep/backgrounds/food_light_thumb_0615.svg"]),Bc=t(["https://www.gstatic.com/keep/backgrounds/music_light_thumb_0615.svg"]),Cc=t(["https://www.gstatic.com/keep/backgrounds/recipe_light_thumb_0615.svg"]),Dc=t(["https://www.gstatic.com/keep/backgrounds/notes_light_thumb_0615.svg"]),
Ec=t(["https://www.gstatic.com/keep/backgrounds/places_light_thumb_0615.svg"]),Fc=t(["https://www.gstatic.com/keep/backgrounds/video_light_thumb_0615.svg"]),Gc=t(["https://www.gstatic.com/keep/backgrounds/celebration_light_thumb_0715.svg"]),Hc=t(["https://www.gstatic.com/keep/backgrounds/travel_light_thumb_0615.svg"]),Ic=t(["https://fonts.gstatic.com/s/i/googlematerialicons/image_not_supported/v12/gm_grey500-24dp/1x/gm_image_not_supported_gm_grey500_24dp.png"]),Jc=t(["https://www.gstatic.com/keep/backgrounds/grocery_dark_thumb_0615.svg"]),
Kc=t(["https://www.gstatic.com/keep/backgrounds/food_dark_thumb_0615.svg"]),Lc=t(["https://www.gstatic.com/keep/backgrounds/music_dark_thumb_0615.svg"]),Mc=t(["https://www.gstatic.com/keep/backgrounds/recipe_dark_thumb_0615.svg"]),Nc=t(["https://www.gstatic.com/keep/backgrounds/notes_dark_thumb_0715.svg"]),Oc=t(["https://www.gstatic.com/keep/backgrounds/places_dark_thumb_0615.svg"]),Pc=t(["https://www.gstatic.com/keep/backgrounds/video_dark_thumb_0615.svg"]),Qc=t(["https://www.gstatic.com/keep/backgrounds/celebration_dark_thumb_0715.svg"]),
Rc=t(["https://www.gstatic.com/keep/backgrounds/travel_dark_thumb_0615.svg"]);Object.values({UNKNOWN:"unknown",Aa:"default",Ma:"groceries",Ha:"food",cb:"music",ob:"recipes",gb:"notes",kb:"places",xb:"travel",Db:"video",ua:"celebration"}).filter(function(a){return a!=="unknown"});L(yc);L(zc);L(Ac);L(Bc);L(Cc);L(Dc);L(Ec);L(Fc);L(Gc);L(Hc);L(Ic);L(Jc);L(Kc);L(Lc);L(Mc);L(Nc);L(Oc);L(Pc);L(Qc);L(Rc);function Sc(){};function Tc(){new DataView(new ArrayBuffer(8))}ka(Tc,Sc);new Tc;Object.freeze("annotationsGroup clientChanges isArchived isDirty isPinned lastSyncedText parentServerId reminder baseVersion baseNoteRevision serverId shareState roleInfo showAvailableInShoppingNotification tasks timestamps".split(" "));var Uc=t(["http://goo.gl/forms/r40gTO4BTb"]),Vc=t(["https://keep.google.com"]);(function(a){var b=ma.apply(1,arguments);tb(a,b.length);var c=a[0];var d=b.length===0;var e=c.search(/[:/?#]/);e<0||(c.charAt(e)!==":"?d=!0:(d=c.substring(0,e).toLowerCase(),d=/^[a-z][a-z\d+.-]*$/.test(d)&&d!=="javascript"));if(!d)throw Error("Trying to interpolate with unsupported prefix: "+c);c=[c];for(d=0;d<b.length;d++)c.push(String(b[d])),c.push(a[d+1]);return new I(c.join(""))})(Uc);var X=L(Vc).toString(),Wc=void 0;
Wc=Wc===void 0?yb:Wc;var Xc;a:{var Y=Wc;Y=Y===void 0?yb:Y;if(X instanceof I)Xc=X;else{for(var Yc=0;Yc<Y.length;++Yc){var Zc=Y[Yc];if(Zc instanceof xb&&Zc.ma(X)){Xc=new I(X);break a}}Xc=void 0}}Xc===void 0&&Bb(X.toString());var $c={Gb:!0};function Z(){throw Error("Do not instantiate directly");}Z.prototype.ha=null;Z.prototype.getContent=function(){return this.content};Z.prototype.toString=function(){return this.content};Z.prototype.ea=function(){if(this.ia!==$c)throw Error("Sanitized content was not of kind HTML.");return Db(this.toString())};function ad(){Z.call(this)}z(ad,Z);ad.prototype.ia=$c;var bd=function(a){function b(c){this.content=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));d!==void 0&&(c.ha=d);return c}}(ad),cd={};RegExp.prototype.hasOwnProperty("sticky");/*
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var dd=/^<(body|caption|col|colgroup|head|html|tr|td|th|tbody|thead|tfoot)>/i,ed={};function fd(){this.h=null;this.W=!1;this.Z="";this.N={};this.ba=ua(this.ka,this);chrome.runtime.onMessage.addListener(this.ba)}function gd(a){a.h=null;chrome.runtime.onMessage.removeListener(a.ba);a.W=!0}function hd(a,b,c){if(!a.W)try{chrome.runtime.sendMessage(chrome.runtime.id,{type:b,value:c},void 0)}catch(d){gd(a)}}
fd.prototype.ka=function(a,b,c){if(y(a)&&!this.W)switch(a.type){case "appHeightChange":this.h&&(this.h.style.height=a.value);break;case "dispose":gd(this);break;case "finishHide":this.h&&id(this,!1);break;case "getInitInfo":c(this.N);break;case "getSelectedText":c(window.getSelection().toString());break;case "removeIframe":this.h.parentNode.removeChild(this.h),gd(this);case "selectedTextRequest":c(window.getSelection().toString());break;case "setInitInfo":this.N=a.value;this.N.selectedText=window.getSelection().toString();
a=this.N.embedInfo;c="";b=document.getElementsByTagName("META");for(var d=0,e;e=b[d];d++)if(e.getAttribute("property")=="og:image"){c=e.getAttribute("content");break}if(!c){b=0;d=document.getElementsByTagName("IMG");e=0;for(var f;f=d[e];e++){var k=f.naturalWidth||f.width,h=f.naturalHeight||f.height;if(h>=128&&k>=128&&h*k>b){b=h*k;var g=f.src}}g&&(c=g)}c&&(g=c,g=g instanceof Q?g.clone():new Q(g),g.A||oc(g,"http"),c=g.toString());a.imageUrl=c;this.aa();break;case "speakMessage":D(!Object.isSealed(N),
"Cannot use getInstance() with a sealed constructor.");g="V";N.V&&N.hasOwnProperty(g)?g=N.V:(Ob.push(N),c=new N,N.V=c,D(N.hasOwnProperty(g),"Could not instantiate singleton."),g=c);g.speak(a.value);break;case "show":this.h&&id(this,!0);break;case "toggleVisibility":g=this.h.style.display=="none",this.h&&(this.h.style.display=="none"?(id(this,!0),this.h.contentWindow.focus(),hd(this,"show")):(hd(this,"startHide"),hd(this,"impression",9204))),c(g)}};
fd.prototype.aa=function(){if(document.readyState!="interactive"&&document.readyState!="complete")$b(document,"DOMContentLoaded",this.aa,void 0,this);else{var a=document.getElementById("keep-popup-frame");a&&a.parentNode&&a.parentNode.removeChild(a);var b=cd["notes.browseraction.soy.injects.injectedIframe"]?cd["notes.browseraction.soy.injects.injectedIframe"](ed,void 0):bd('<iframe frameborder="0" style=" height: 438px; margin: 0px; padding: 0px; position: fixed; right: 5px; top: 5px; width: 370px; z-index: 2147483647;"></iframe>');
a=B||(B=new Kb);if(b&&b.pa)a=b.pa();else{a=a.createElement("DIV");b:if(y(b)){if(b.ea){var c=b.ea();if(c instanceof K){b=c;break b}}xa("Soy template output is unsafe for use as HTML: "+b);b=Gb("zSoyz")}else b=Gb(String(b));c=b.toString();var d=c.match(dd);D(!d,"This template starts with a %s, which cannot be a child of a <div>, as required by soy internals. Consider using goog.soy.renderElement instead.\nTemplate output: %s",d&&d[0],c);if(b instanceof K)b=b.ca;else throw Error("Unexpected type when unwrapping SafeHtml");
a.innerHTML=b}a.childNodes.length==1&&(b=a.firstChild,b.nodeType==1&&(a=b));if(!y(a)||!y(a)||!y(a)||a.nodeType!==1||a.namespaceURI&&a.namespaceURI!=="http://www.w3.org/1999/xhtml"||a.tagName.toUpperCase()!=="IFRAME".toString()){b="IFRAME".toString()+"; got: ";if(y(a))try{var e=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(f){e="<object could not be stringified>"}else e=a===void 0?"undefined":a===null?"null":typeof a;xa("Argument is not an HTML Element with tag name "+
(b+e))}this.h=a;this.Z=this.h.style.cssText;this.h.id="keep-popup-frame";e=this.h;a=chrome.runtime.getURL("index.html");e.removeAttribute("srcdoc");if(a instanceof jb)throw new Fb("TrustedResourceUrl",2);b="allow-same-origin allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation".split(" ");e.setAttribute("sandbox","");for(c=0;c<b.length;c++)e.sandbox.supports&&!e.sandbox.supports(b[c])||e.sandbox.add(b[c]);if(a instanceof I)if(a instanceof I)a=
a.da;else throw Error("Unexpected type when unwrapping SafeUrl, got '"+a+"' of type '"+typeof a+"'");else(b=!zb.test(a))&&Bb(a),a=b?void 0:a;a!==void 0&&(e.src=a);this.h.allow="clipboard-write";document.body.appendChild(this.h);id(this,!0);this.h.contentWindow.focus()}};function id(a,b){a.h.style.cssText=a.Z+" display: "+(b?"block !important;":"none")}new fd;
