#!/usr/bin/env python3
# PROOF: [L3/ユーティリティ] O4→実行スクリプトが必要→phase3_specialists が担う
"""
Jules 専門家定義: Phase 3 高度分析層 (Layer 16-20: 230人)
"""
from .specialist_prompts import SpecialistDefinition, Archetype

# === Layer 16: DSL・コード生成層 (50人) ===
DSL_SPECIALISTS = [
    SpecialistDefinition(id="DSL-001", name="DSL構文検証評価者", category="dsl", archetype=Archetype.PRECISION, focus="Grammar conformance、parsing success rateを評価"),
    SpecialistDefinition(id="DSL-002", name="意味的正確性評価者", category="dsl", archetype=Archetype.PRECISION, focus="セマンティック意図一貫性を評価"),
    SpecialistDefinition(id="DSL-003", name="DSLハルシネーション検出者", category="dsl", archetype=Archetype.PRECISION, focus="存在しないAPI参照を検出"),
    SpecialistDefinition(id="DSL-004", name="制約充足評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL固有制約を評価"),
    SpecialistDefinition(id="DSL-005", name="Grammar prompting効果評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL grammarプロンプト効果を評価"),
    SpecialistDefinition(id="DSL-006", name="Few-shot学習品質評価者", category="dsl", archetype=Archetype.PRECISION, focus="提示例の質が性能に与える影響を評価"),
    SpecialistDefinition(id="DSL-007", name="ドメイン固有イディオム評価者", category="dsl", archetype=Archetype.PRECISION, focus="ドメイン慣用表現使用度を評価"),
    SpecialistDefinition(id="DSL-008", name="コード生成等価性評価者", category="dsl", archetype=Archetype.PRECISION, focus="異なるDSLで生成されたコード等価性を検証"),
    SpecialistDefinition(id="DSL-009", name="型保存評価者", category="dsl", archetype=Archetype.PRECISION, focus="型システム保存を評価"),
    SpecialistDefinition(id="DSL-010", name="パフォーマンス特性評価者", category="dsl", archetype=Archetype.PRECISION, focus="生成コードパフォーマンス特性維持を評価"),
    SpecialistDefinition(id="DSL-011", name="デバッグ可能性評価者", category="dsl", archetype=Archetype.PRECISION, focus="生成コードデバッグ可能性を評価"),
    SpecialistDefinition(id="DSL-012", name="統合テスト準備状況評価者", category="dsl", archetype=Archetype.PRECISION, focus="外部システム統合テスト準備度を評価"),
    SpecialistDefinition(id="DSL-013", name="ドキュメント生成評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSLから自動生成ドキュメント品質を評価"),
    SpecialistDefinition(id="DSL-014", name="保守負荷評価者", category="dsl", archetype=Archetype.PRECISION, focus="生成コード将来的保守負荷を評価"),
    SpecialistDefinition(id="DSL-015", name="拡張可能性評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL将来的拡張可能性を評価"),
    SpecialistDefinition(id="DSL-016", name="抽象度適合性評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL抽象度がドメインに適切かを評価"),
    SpecialistDefinition(id="DSL-017", name="クロスDSL互換性評価者", category="dsl", archetype=Archetype.PRECISION, focus="複数DSL間相互運用性を評価"),
    SpecialistDefinition(id="DSL-018", name="バージョン互換性評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSLバージョン変更対応を評価"),
    SpecialistDefinition(id="DSL-019", name="ツールエコシステムサポート評価者", category="dsl", archetype=Archetype.PRECISION, focus="IDE/linter等ツール対応を評価"),
    SpecialistDefinition(id="DSL-020", name="学習曲線評価者", category="dsl", archetype=Archetype.PRECISION, focus="新DSL習得難度を評価"),
    SpecialistDefinition(id="DSL-021", name="DSL最適化評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL固有最適化を評価"),
    SpecialistDefinition(id="DSL-022", name="生成パワー評価者", category="dsl", archetype=Archetype.CREATIVE, focus="DSL表現力を評価"),
    SpecialistDefinition(id="DSL-023", name="表現力/学習容易性トレードオフ評価者", category="dsl", archetype=Archetype.PRECISION, focus="表現力と学習容易性バランスを評価"),
    SpecialistDefinition(id="DSL-024", name="DSLエラーメッセージ品質評価者", category="dsl", archetype=Archetype.CREATIVE, focus="DSLエラーメッセージ明確さを評価"),
    SpecialistDefinition(id="DSL-025", name="DSLテスト戦略評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSLテスト戦略を評価"),
    SpecialistDefinition(id="DSL-026", name="DSLリファクタリングサポート評価者", category="dsl", archetype=Archetype.PRECISION, focus="リファクタリングツールサポートを評価"),
    SpecialistDefinition(id="DSL-027", name="DSLコード生成品質評価者", category="dsl", archetype=Archetype.PRECISION, focus="生成コード品質を評価"),
    SpecialistDefinition(id="DSL-028", name="DSLパーサー堅牢性評価者", category="dsl", archetype=Archetype.SAFETY, focus="パーサーエラー処理を評価"),
    SpecialistDefinition(id="DSL-029", name="DSLセキュリティ評価者", category="dsl", archetype=Archetype.SAFETY, focus="DSLセキュリティ脆弱性を評価"),
    SpecialistDefinition(id="DSL-030", name="DSL実行環境評価者", category="dsl", archetype=Archetype.PRECISION, focus="実行環境要件を評価"),
    SpecialistDefinition(id="DSL-031", name="コード生成トレーサビリティ評価者", category="dsl", archetype=Archetype.PRECISION, focus="生成コードと元DSLの関連付けを評価"),
    SpecialistDefinition(id="DSL-032", name="DSLモジュール化評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSLモジュール構成を評価"),
    SpecialistDefinition(id="DSL-033", name="DSL再利用性評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL部品再利用性を評価"),
    SpecialistDefinition(id="DSL-034", name="DSLデプロイメントパイプライン評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL成果物デプロイを評価"),
    SpecialistDefinition(id="DSL-035", name="DSL変換正確性評価者", category="dsl", archetype=Archetype.PRECISION, focus="DSL間変換正確性を評価"),
    SpecialistDefinition(id="DSL-036", name="DSLメタモデル評価者", category="dsl", archetype=Archetype.PRECISION, focus="メタモデル設計を評価"),
    SpecialistDefinition(id="DSL-037", name="DSL形式検証サポート評価者", category="dsl", archetype=Archetype.PRECISION, focus="形式検証ツール統合を評価"),
    SpecialistDefinition(id="DSL-038", name="DSLサンドボックス評価者", category="dsl", archetype=Archetype.SAFETY, focus="実行サンドボックス安全性を評価"),
    SpecialistDefinition(id="DSL-039", name="DSL性能プロファイリング評価者", category="dsl", archetype=Archetype.PRECISION, focus="生成コード性能プロファイリングを評価"),
    SpecialistDefinition(id="DSL-040", name="DSLインクリメンタルコンパイル評価者", category="dsl", archetype=Archetype.SPEED, focus="インクリメンタルコンパイルサポートを評価"),
    SpecialistDefinition(id="DSL-041", name="DSLキャッシング評価者", category="dsl", archetype=Archetype.SPEED, focus="生成結果キャッシングを評価"),
    SpecialistDefinition(id="DSL-042", name="DSL並列生成評価者", category="dsl", archetype=Archetype.SPEED, focus="並列コード生成を評価"),
    SpecialistDefinition(id="DSL-043", name="DSLストリーミング生成評価者", category="dsl", archetype=Archetype.SPEED, focus="ストリーミング生成サポートを評価"),
    SpecialistDefinition(id="DSL-044", name="DSLオフライン動作評価者", category="dsl", archetype=Archetype.AUTONOMY, focus="オフライン動作可能性を評価"),
    SpecialistDefinition(id="DSL-045", name="DSLプラグインアーキテクチャ評価者", category="dsl", archetype=Archetype.PRECISION, focus="プラグイン拡張性を評価"),
    SpecialistDefinition(id="DSL-046", name="DSL言語サーバー評価者", category="dsl", archetype=Archetype.PRECISION, focus="LSP(Language Server Protocol)サポートを評価"),
    SpecialistDefinition(id="DSL-047", name="DSLシンタックスハイライト評価者", category="dsl", archetype=Archetype.PRECISION, focus="シンタックスハイライト対応を評価"),
    SpecialistDefinition(id="DSL-048", name="DSL補完機能評価者", category="dsl", archetype=Archetype.PRECISION, focus="コード補完サポートを評価"),
    SpecialistDefinition(id="DSL-049", name="DSLホバー情報評価者", category="dsl", archetype=Archetype.PRECISION, focus="ホバー情報提供を評価"),
    SpecialistDefinition(id="DSL-050", name="DSL定義ジャンプ評価者", category="dsl", archetype=Archetype.PRECISION, focus="定義へのジャンプ機能を評価"),
]

# === Layer 17: 事業ロジック・形式検証層 (45人) ===
FORMAL_SPECIALISTS = [
    SpecialistDefinition(id="FV-001", name="ビジネスルール形式化評価者", category="formal", archetype=Archetype.PRECISION, focus="事業ルールを形式言語で記述を評価"),
    SpecialistDefinition(id="FV-002", name="不変条件保存評価者", category="formal", archetype=Archetype.PRECISION, focus="不変条件保存を評価"),
    SpecialistDefinition(id="FV-003", name="事前条件強制評価者", category="formal", archetype=Archetype.PRECISION, focus="事前条件チェックを評価"),
    SpecialistDefinition(id="FV-004", name="事後条件保証評価者", category="formal", archetype=Archetype.PRECISION, focus="事後条件保証を評価"),
    SpecialistDefinition(id="FV-005", name="状態遷移正確性評価者", category="formal", archetype=Archetype.PRECISION, focus="状態遷移正確性を評価"),
    SpecialistDefinition(id="FV-006", name="デッドロック自由度評価者", category="formal", archetype=Archetype.SAFETY, focus="デッドロック回避保証を評価"),
    SpecialistDefinition(id="FV-007", name="ライブロック防止評価者", category="formal", archetype=Archetype.SAFETY, focus="ライブロック防止を評価"),
    SpecialistDefinition(id="FV-008", name="競合状態不在評価者", category="formal", archetype=Archetype.SAFETY, focus="競合状態なしを評価"),
    SpecialistDefinition(id="FV-009", name="相互排除正確性評価者", category="formal", archetype=Archetype.SAFETY, focus="相互排除正確性を評価"),
    SpecialistDefinition(id="FV-010", name="原子性保証評価者", category="formal", archetype=Archetype.SAFETY, focus="アトミック性保証を評価"),
    SpecialistDefinition(id="FV-011", name="一貫性モデル検証評価者", category="formal", archetype=Archetype.PRECISION, focus="一貫性モデル検証を評価"),
    SpecialistDefinition(id="FV-012", name="順序保存評価者", category="formal", archetype=Archetype.PRECISION, focus="順序保存保証を評価"),
    SpecialistDefinition(id="FV-013", name="ロールバック可能性評価者", category="formal", archetype=Archetype.SAFETY, focus="ロールバック可能性を評価"),
    SpecialistDefinition(id="FV-014", name="例外処理完全性評価者", category="formal", archetype=Archetype.SAFETY, focus="例外処理完全性を評価"),
    SpecialistDefinition(id="FV-015", name="リソース割り当て正確性評価者", category="formal", archetype=Archetype.PRECISION, focus="リソース割り当て正確性を評価"),
    SpecialistDefinition(id="FV-016", name="パーミッションモデル強制評価者", category="formal", archetype=Archetype.SAFETY, focus="パーミッション/認可モデルを評価"),
    SpecialistDefinition(id="FV-017", name="暗号鍵使用評価者", category="formal", archetype=Archetype.SAFETY, focus="暗号鍵適切使用を評価"),
    SpecialistDefinition(id="FV-018", name="データフローセキュリティ評価者", category="formal", archetype=Archetype.SAFETY, focus="データフロー機密性を評価"),
    SpecialistDefinition(id="FV-019", name="SQLインジェクション防止評価者", category="formal", archetype=Archetype.SAFETY, focus="SQLインジェクション防止を評価"),
    SpecialistDefinition(id="FV-020", name="XSS防止評価者", category="formal", archetype=Archetype.SAFETY, focus="XSS防止を評価"),
    SpecialistDefinition(id="FV-021", name="CSRF保護評価者", category="formal", archetype=Archetype.SAFETY, focus="CSRF対策を評価"),
    SpecialistDefinition(id="FV-022", name="決済トランザクション原子性評価者", category="formal", archetype=Archetype.SAFETY, focus="決済トランザクション原子性を評価"),
    SpecialistDefinition(id="FV-023", name="監査証跡正確性評価者", category="formal", archetype=Archetype.PRECISION, focus="監査ログ正確性を評価"),
    SpecialistDefinition(id="FV-024", name="規制遵守証明評価者", category="formal", archetype=Archetype.SAFETY, focus="規制遵守数学的証明を評価"),
    SpecialistDefinition(id="FV-025", name="ビジネスメトリクス正確性評価者", category="formal", archetype=Archetype.PRECISION, focus="ビジネスメトリクス正確性を評価"),
    SpecialistDefinition(id="FV-026", name="リグレッションテスト有効性評価者", category="formal", archetype=Archetype.PRECISION, focus="リグレッション検査有効性を評価"),
    SpecialistDefinition(id="FV-027", name="フォールトトレランス評価者", category="formal", archetype=Archetype.SAFETY, focus="フォールトトレランスを評価"),
    SpecialistDefinition(id="FV-028", name="ビザンチン障害回復力評価者", category="formal", archetype=Archetype.SAFETY, focus="ビザンチン耐性を評価"),
    SpecialistDefinition(id="FV-029", name="データ保持ポリシー評価者", category="formal", archetype=Archetype.PRECISION, focus="データ保持ポリシー遵守を評価"),
    SpecialistDefinition(id="FV-030", name="同意管理評価者", category="formal", archetype=Archetype.SAFETY, focus="同意管理正確性を評価"),
    SpecialistDefinition(id="FV-031", name="モデルチェッキング評価者", category="formal", archetype=Archetype.PRECISION, focus="Model Checking適用を評価"),
    SpecialistDefinition(id="FV-032", name="演繹的検証評価者", category="formal", archetype=Archetype.PRECISION, focus="定理証明適用を評価"),
    SpecialistDefinition(id="FV-033", name="軽量形式手法評価者", category="formal", archetype=Archetype.PRECISION, focus="型システム/契約チェックを評価"),
    SpecialistDefinition(id="FV-034", name="LTL/CTL検証評価者", category="formal", archetype=Archetype.PRECISION, focus="時相論理検証を評価"),
    SpecialistDefinition(id="FV-035", name="Hoare論理適用評価者", category="formal", archetype=Archetype.PRECISION, focus="Hoare logic適用を評価"),
    SpecialistDefinition(id="FV-036", name="契約プログラミング評価者", category="formal", archetype=Archetype.PRECISION, focus="Design by Contract適用を評価"),
    SpecialistDefinition(id="FV-037", name="形式仕様言語評価者", category="formal", archetype=Archetype.PRECISION, focus="B-method/Z/TLA+適用を評価"),
    SpecialistDefinition(id="FV-038", name="シンボリック実行評価者", category="formal", archetype=Archetype.PRECISION, focus="symbolic execution適用を評価"),
    SpecialistDefinition(id="FV-039", name="抽象解釈評価者", category="formal", archetype=Archetype.PRECISION, focus="abstract interpretation適用を評価"),
    SpecialistDefinition(id="FV-040", name="SMT solver活用評価者", category="formal", archetype=Archetype.PRECISION, focus="SMT solver活用を評価"),
    SpecialistDefinition(id="FV-041", name="プロパティベーステスト評価者", category="formal", archetype=Archetype.PRECISION, focus="property-based testing適用を評価"),
    SpecialistDefinition(id="FV-042", name="ファジング評価者", category="formal", archetype=Archetype.SAFETY, focus="fuzz testing適用を評価"),
    SpecialistDefinition(id="FV-043", name="ミューテーションテスト評価者", category="formal", archetype=Archetype.PRECISION, focus="mutation testing適用を評価"),
    SpecialistDefinition(id="FV-044", name="境界値分析評価者", category="formal", archetype=Archetype.PRECISION, focus="boundary value analysis適用を評価"),
    SpecialistDefinition(id="FV-045", name="等価クラス分割評価者", category="formal", archetype=Archetype.PRECISION, focus="equivalence partitioning適用を評価"),
]

# === Layer 18: 機械学習パイプライン品質層 (55人) ===
ML_SPECIALISTS = [
    SpecialistDefinition(id="ML-001", name="スキーマ検証評価者", category="ml", archetype=Archetype.PRECISION, focus="データスキーマ整合性を評価"),
    SpecialistDefinition(id="ML-002", name="データ鮮度評価者", category="ml", archetype=Archetype.PRECISION, focus="データの鮮度を評価"),
    SpecialistDefinition(id="ML-003", name="欠損値戦略評価者", category="ml", archetype=Archetype.PRECISION, focus="欠落値処理を評価"),
    SpecialistDefinition(id="ML-004", name="外れ値検出評価者", category="ml", archetype=Archetype.PRECISION, focus="外れ値検出を評価"),
    SpecialistDefinition(id="ML-005", name="分布シフト検出者", category="ml", archetype=Archetype.PRECISION, focus="訓練-本番間分布シフトを検出"),
    SpecialistDefinition(id="ML-006", name="ラベルノイズ検出者", category="ml", archetype=Archetype.PRECISION, focus="ラベルノイズを検出"),
    SpecialistDefinition(id="ML-007", name="データ漏洩検出者", category="ml", archetype=Archetype.SAFETY, focus="訓練/テストデータ混在を検出"),
    SpecialistDefinition(id="ML-008", name="重複行検出者", category="ml", archetype=Archetype.PRECISION, focus="重複行を検出"),
    SpecialistDefinition(id="ML-009", name="クラス不均衡測定者", category="ml", archetype=Archetype.PRECISION, focus="クラス不均衡度を測定"),
    SpecialistDefinition(id="ML-010", name="データ型一貫性評価者", category="ml", archetype=Archetype.PRECISION, focus="データ型一貫性を評価"),
    SpecialistDefinition(id="ML-011", name="値範囲検証評価者", category="ml", archetype=Archetype.PRECISION, focus="値の範囲を確認"),
    SpecialistDefinition(id="ML-012", name="カテゴリ一意性評価者", category="ml", archetype=Archetype.PRECISION, focus="カテゴリ変数一意性を評価"),
    SpecialistDefinition(id="ML-013", name="時系列データ正確性評価者", category="ml", archetype=Archetype.PRECISION, focus="時系列データ順序を評価"),
    SpecialistDefinition(id="ML-014", name="結合正確性評価者", category="ml", archetype=Archetype.PRECISION, focus="データ結合正確性を評価"),
    SpecialistDefinition(id="ML-015", name="集約正確性評価者", category="ml", archetype=Archetype.PRECISION, focus="集約関数正確性を評価"),
    SpecialistDefinition(id="ML-016", name="前処理再現可能性評価者", category="ml", archetype=Archetype.PRECISION, focus="前処理再現可能性を評価"),
    SpecialistDefinition(id="ML-017", name="特徴エンジニアリングロジック評価者", category="ml", archetype=Archetype.PRECISION, focus="特徴エンジニアリング論理を評価"),
    SpecialistDefinition(id="ML-018", name="正規化正確性評価者", category="ml", archetype=Archetype.PRECISION, focus="正規化正確性を評価"),
    SpecialistDefinition(id="ML-019", name="エンコーディング正確性評価者", category="ml", archetype=Archetype.PRECISION, focus="エンコーディング正確性を評価"),
    SpecialistDefinition(id="ML-020", name="次元削減評価者", category="ml", archetype=Archetype.PRECISION, focus="次元削減後情報保有を評価"),
    SpecialistDefinition(id="ML-021", name="特徴相関評価者", category="ml", archetype=Archetype.PRECISION, focus="特徴間相関を評価"),
    SpecialistDefinition(id="ML-022", name="交互作用検出者", category="ml", archetype=Archetype.PRECISION, focus="交互作用項を検出"),
    SpecialistDefinition(id="ML-023", name="特徴重要度評価者", category="ml", archetype=Archetype.PRECISION, focus="特徴重要度を評価"),
    SpecialistDefinition(id="ML-024", name="外れ値処理戦略評価者", category="ml", archetype=Archetype.PRECISION, focus="外れ値処理戦略を評価"),
    SpecialistDefinition(id="ML-025", name="欠損値補完評価者", category="ml", archetype=Archetype.PRECISION, focus="欠落値補完方法を評価"),
    SpecialistDefinition(id="ML-026", name="スケーリング一貫性評価者", category="ml", archetype=Archetype.PRECISION, focus="スケーリング一貫性を評価"),
    SpecialistDefinition(id="ML-027", name="カテゴリ処理評価者", category="ml", archetype=Archetype.PRECISION, focus="カテゴリ変数扱いを評価"),
    SpecialistDefinition(id="ML-028", name="時系列特徴抽出評価者", category="ml", archetype=Archetype.PRECISION, focus="時系列特徴抽出を評価"),
    SpecialistDefinition(id="ML-029", name="特徴選択方法評価者", category="ml", archetype=Archetype.PRECISION, focus="特徴選択方法を評価"),
    SpecialistDefinition(id="ML-030", name="データパイプライン監視評価者", category="ml", archetype=Archetype.PRECISION, focus="パイプライン実行状態を評価"),
    SpecialistDefinition(id="ML-031", name="訓練/テスト分割戦略評価者", category="ml", archetype=Archetype.PRECISION, focus="訓練/テスト分割を評価"),
    SpecialistDefinition(id="ML-032", name="交差検証方法論評価者", category="ml", archetype=Archetype.PRECISION, focus="K-fold CV正確性を評価"),
    SpecialistDefinition(id="ML-033", name="ハイパーパラメータチューニング評価者", category="ml", archetype=Archetype.PRECISION, focus="ハイパーパラメータ最適化を評価"),
    SpecialistDefinition(id="ML-034", name="アルゴリズム選択根拠評価者", category="ml", archetype=Archetype.PRECISION, focus="アルゴリズム選択理由を評価"),
    SpecialistDefinition(id="ML-035", name="モデルキャリブレーション評価者", category="ml", archetype=Archetype.PRECISION, focus="モデルキャリブレーションを評価"),
    SpecialistDefinition(id="ML-036", name="汎化性能評価者", category="ml", archetype=Archetype.PRECISION, focus="汎化性能を評価"),
    SpecialistDefinition(id="ML-037", name="過学習検出者", category="ml", archetype=Archetype.PRECISION, focus="過学習を検出"),
    SpecialistDefinition(id="ML-038", name="過小学習検出者", category="ml", archetype=Archetype.PRECISION, focus="過小学習を検出"),
    SpecialistDefinition(id="ML-039", name="クラス不均衡処理評価者", category="ml", archetype=Archetype.PRECISION, focus="不均衡クラス対応を評価"),
    SpecialistDefinition(id="ML-040", name="アンサンブル方法正確性評価者", category="ml", archetype=Archetype.PRECISION, focus="アンサンブル方法正確性を評価"),
    SpecialistDefinition(id="ML-041", name="特徴重要度ランキング評価者", category="ml", archetype=Archetype.PRECISION, focus="特徴重要度ランキングを評価"),
    SpecialistDefinition(id="ML-042", name="予測信頼度評価者", category="ml", archetype=Archetype.PRECISION, focus="予測信頼度スコアを評価"),
    SpecialistDefinition(id="ML-043", name="モデルバージョニング評価者", category="ml", archetype=Archetype.PRECISION, focus="モデルバージョン管理を評価"),
    SpecialistDefinition(id="ML-044", name="説明可能性評価者", category="ml", archetype=Archetype.PRECISION, focus="モデル説明可能性を評価"),
    SpecialistDefinition(id="ML-045", name="公平性メトリクス評価者", category="ml", archetype=Archetype.SAFETY, focus="公平性メトリクスを評価"),
    SpecialistDefinition(id="ML-046", name="データドリフト検出者", category="ml", archetype=Archetype.PRECISION, focus="データドリフトを検出"),
    SpecialistDefinition(id="ML-047", name="モデル性能劣化検出者", category="ml", archetype=Archetype.PRECISION, focus="モデル性能低下を検出"),
    SpecialistDefinition(id="ML-048", name="特徴利用可能性監視評価者", category="ml", archetype=Archetype.PRECISION, focus="特徴データ利用可能性を評価"),
    SpecialistDefinition(id="ML-049", name="予測遅延評価者", category="ml", archetype=Archetype.SPEED, focus="予測遅延を評価"),
    SpecialistDefinition(id="ML-050", name="推論インフラ評価者", category="ml", archetype=Archetype.PRECISION, focus="推論インフラストラクチャを評価"),
    SpecialistDefinition(id="ML-051", name="モデルロールバック能力評価者", category="ml", archetype=Archetype.SAFETY, focus="モデルロールバック可能性を評価"),
    SpecialistDefinition(id="ML-052", name="A/Bテストフレームワーク評価者", category="ml", archetype=Archetype.PRECISION, focus="A/Bテストフレームワークを評価"),
    SpecialistDefinition(id="ML-053", name="フィードバックループ評価者", category="ml", archetype=Archetype.PRECISION, focus="ユーザーフィードバック収集を評価"),
    SpecialistDefinition(id="ML-054", name="再訓練スケジュール評価者", category="ml", archetype=Archetype.PRECISION, focus="再訓練スケジュールを評価"),
    SpecialistDefinition(id="ML-055", name="MLインシデント対応評価者", category="ml", archetype=Archetype.SAFETY, focus="インシデント対応を評価"),
]

# === Layer 19: 統計的正当性層 (40人) ===
STATS_SPECIALISTS = [
    SpecialistDefinition(id="ST-001", name="仮説構成評価者", category="stats", archetype=Archetype.PRECISION, focus="帰無/対立仮説明確性を評価"),
    SpecialistDefinition(id="ST-002", name="有意水準設定評価者", category="stats", archetype=Archetype.PRECISION, focus="α設定正当化を評価"),
    SpecialistDefinition(id="ST-003", name="検定方法適切性評価者", category="stats", archetype=Archetype.PRECISION, focus="検定選択を評価"),
    SpecialistDefinition(id="ST-004", name="前提条件検証評価者", category="stats", archetype=Archetype.PRECISION, focus="正規性/等分散性/独立性を評価"),
    SpecialistDefinition(id="ST-005", name="P値解釈評価者", category="stats", archetype=Archetype.PRECISION, focus="P値誤解釈防止を評価"),
    SpecialistDefinition(id="ST-006", name="効果量評価者", category="stats", archetype=Archetype.PRECISION, focus="Cohen's d等効果量を評価"),
    SpecialistDefinition(id="ST-007", name="検出力分析評価者", category="stats", archetype=Archetype.PRECISION, focus="統計的検出力を評価"),
    SpecialistDefinition(id="ST-008", name="サンプルサイズ決定評価者", category="stats", archetype=Archetype.PRECISION, focus="サンプルサイズ決定を評価"),
    SpecialistDefinition(id="ST-009", name="信頼区間計算評価者", category="stats", archetype=Archetype.PRECISION, focus="信頼区間計算を評価"),
    SpecialistDefinition(id="ST-010", name="多重比較補正評価者", category="stats", archetype=Archetype.PRECISION, focus="Bonferroni等補正を評価"),
    SpecialistDefinition(id="ST-011", name="ベイズ推論評価者", category="stats", archetype=Archetype.PRECISION, focus="ベイズ推論適用を評価"),
    SpecialistDefinition(id="ST-012", name="事前分布選択評価者", category="stats", archetype=Archetype.PRECISION, focus="事前分布選択を評価"),
    SpecialistDefinition(id="ST-013", name="MCMC診断評価者", category="stats", archetype=Archetype.PRECISION, focus="MCMC収束診断を評価"),
    SpecialistDefinition(id="ST-014", name="モデル比較評価者", category="stats", archetype=Archetype.PRECISION, focus="AIC/BIC等モデル比較を評価"),
    SpecialistDefinition(id="ST-015", name="回帰診断評価者", category="stats", archetype=Archetype.PRECISION, focus="回帰診断を評価"),
    SpecialistDefinition(id="ST-016", name="残差分析評価者", category="stats", archetype=Archetype.PRECISION, focus="残差分析を評価"),
    SpecialistDefinition(id="ST-017", name="多重共線性評価者", category="stats", archetype=Archetype.PRECISION, focus="VIF等多重共線性を評価"),
    SpecialistDefinition(id="ST-018", name="異常値影響評価者", category="stats", archetype=Archetype.PRECISION, focus="異常値影響を評価"),
    SpecialistDefinition(id="ST-019", name="交絡変数評価者", category="stats", archetype=Archetype.PRECISION, focus="交絡変数を評価"),
    SpecialistDefinition(id="ST-020", name="選択バイアス評価者", category="stats", archetype=Archetype.PRECISION, focus="選択バイアスを評価"),
    SpecialistDefinition(id="ST-021", name="生存バイアス評価者", category="stats", archetype=Archetype.PRECISION, focus="生存バイアスを評価"),
    SpecialistDefinition(id="ST-022", name="出版バイアス評価者", category="stats", archetype=Archetype.PRECISION, focus="出版バイアスを評価"),
    SpecialistDefinition(id="ST-023", name="再現性評価者", category="stats", archetype=Archetype.PRECISION, focus="統計的再現性を評価"),
    SpecialistDefinition(id="ST-024", name="事前登録評価者", category="stats", archetype=Archetype.PRECISION, focus="分析計画事前登録を評価"),
    SpecialistDefinition(id="ST-025", name="p-hacking検出者", category="stats", archetype=Archetype.SAFETY, focus="p-hackingを検出"),
    SpecialistDefinition(id="ST-026", name="HARKing検出者", category="stats", archetype=Archetype.SAFETY, focus="HARKingを検出"),
    SpecialistDefinition(id="ST-027", name="データ透明性評価者", category="stats", archetype=Archetype.PRECISION, focus="データ透明性を評価"),
    SpecialistDefinition(id="ST-028", name="コード透明性評価者", category="stats", archetype=Archetype.PRECISION, focus="分析コード透明性を評価"),
    SpecialistDefinition(id="ST-029", name="感度分析評価者", category="stats", archetype=Archetype.PRECISION, focus="感度分析を評価"),
    SpecialistDefinition(id="ST-030", name="ロバストネス検査評価者", category="stats", archetype=Archetype.PRECISION, focus="ロバストネス検査を評価"),
    SpecialistDefinition(id="ST-031", name="ブートストラップ評価者", category="stats", archetype=Archetype.PRECISION, focus="ブートストラップ適用を評価"),
    SpecialistDefinition(id="ST-032", name="並べ替え検定評価者", category="stats", archetype=Archetype.PRECISION, focus="並べ替え検定適用を評価"),
    SpecialistDefinition(id="ST-033", name="ノンパラメトリック検定評価者", category="stats", archetype=Archetype.PRECISION, focus="ノンパラメトリック検定を評価"),
    SpecialistDefinition(id="ST-034", name="時系列分析評価者", category="stats", archetype=Archetype.PRECISION, focus="時系列分析を評価"),
    SpecialistDefinition(id="ST-035", name="自己相関評価者", category="stats", archetype=Archetype.PRECISION, focus="自己相関を評価"),
    SpecialistDefinition(id="ST-036", name="季節調整評価者", category="stats", archetype=Archetype.PRECISION, focus="季節調整を評価"),
    SpecialistDefinition(id="ST-037", name="傾向分析評価者", category="stats", archetype=Archetype.PRECISION, focus="傾向分析を評価"),
    SpecialistDefinition(id="ST-038", name="予測区間評価者", category="stats", archetype=Archetype.PRECISION, focus="予測区間を評価"),
    SpecialistDefinition(id="ST-039", name="因果推論評価者", category="stats", archetype=Archetype.PRECISION, focus="因果推論を評価"),
    SpecialistDefinition(id="ST-040", name="傾向スコア評価者", category="stats", archetype=Archetype.PRECISION, focus="傾向スコアを評価"),
]

# === Layer 20: 学習・移送可能性層 (40人) ===
TRANSFER_SPECIALISTS = [
    SpecialistDefinition(id="TR-001", name="転移学習適用性評価者", category="transfer", archetype=Archetype.PRECISION, focus="転移学習適用可能性を評価"),
    SpecialistDefinition(id="TR-002", name="ドメイン適応評価者", category="transfer", archetype=Archetype.PRECISION, focus="ドメイン適応を評価"),
    SpecialistDefinition(id="TR-003", name="ファインチューニング戦略評価者", category="transfer", archetype=Archetype.PRECISION, focus="ファインチューニング戦略を評価"),
    SpecialistDefinition(id="TR-004", name="特徴抽出評価者", category="transfer", archetype=Archetype.PRECISION, focus="特徴抽出を評価"),
    SpecialistDefinition(id="TR-005", name="層固定戦略評価者", category="transfer", archetype=Archetype.PRECISION, focus="層固定戦略を評価"),
    SpecialistDefinition(id="TR-006", name="学習率スケジューリング評価者", category="transfer", archetype=Archetype.PRECISION, focus="学習率スケジューリングを評価"),
    SpecialistDefinition(id="TR-007", name="壊滅的忘却防止評価者", category="transfer", archetype=Archetype.SAFETY, focus="壊滅的忘却を防止"),
    SpecialistDefinition(id="TR-008", name="マルチタスク学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="マルチタスク学習を評価"),
    SpecialistDefinition(id="TR-009", name="メタ学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="メタ学習を評価"),
    SpecialistDefinition(id="TR-010", name="Few-shot学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="Few-shot学習を評価"),
    SpecialistDefinition(id="TR-011", name="Zero-shot学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="Zero-shot学習を評価"),
    SpecialistDefinition(id="TR-012", name="継続学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="継続学習を評価"),
    SpecialistDefinition(id="TR-013", name="カリキュラム学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="カリキュラム学習を評価"),
    SpecialistDefinition(id="TR-014", name="自己教師あり学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="自己教師あり学習を評価"),
    SpecialistDefinition(id="TR-015", name="対照学習評価者", category="transfer", archetype=Archetype.PRECISION, focus="対照学習を評価"),
    SpecialistDefinition(id="TR-016", name="蒸留評価者", category="transfer", archetype=Archetype.PRECISION, focus="知識蒸留を評価"),
    SpecialistDefinition(id="TR-017", name="モデル圧縮評価者", category="transfer", archetype=Archetype.PRECISION, focus="モデル圧縮を評価"),
    SpecialistDefinition(id="TR-018", name="量子化評価者", category="transfer", archetype=Archetype.PRECISION, focus="量子化を評価"),
    SpecialistDefinition(id="TR-019", name="プルーニング評価者", category="transfer", archetype=Archetype.PRECISION, focus="プルーニングを評価"),
    SpecialistDefinition(id="TR-020", name="ドメインシフト検出者", category="transfer", archetype=Archetype.PRECISION, focus="ドメインシフトを検出"),
    SpecialistDefinition(id="TR-021", name="ソースドメイン選択評価者", category="transfer", archetype=Archetype.PRECISION, focus="ソースドメイン選択を評価"),
    SpecialistDefinition(id="TR-022", name="ターゲットドメイン分析評価者", category="transfer", archetype=Archetype.PRECISION, focus="ターゲットドメイン分析を評価"),
    SpecialistDefinition(id="TR-023", name="負の転移検出者", category="transfer", archetype=Archetype.SAFETY, focus="負の転移を検出"),
    SpecialistDefinition(id="TR-024", name="転移可能性測定者", category="transfer", archetype=Archetype.PRECISION, focus="転移可能性を測定"),
    SpecialistDefinition(id="TR-025", name="事前訓練モデル選択評価者", category="transfer", archetype=Archetype.PRECISION, focus="事前訓練モデル選択を評価"),
    SpecialistDefinition(id="TR-026", name="適応層設計評価者", category="transfer", archetype=Archetype.PRECISION, focus="適応層設計を評価"),
    SpecialistDefinition(id="TR-027", name="ドメイン不変特徴評価者", category="transfer", archetype=Archetype.PRECISION, focus="ドメイン不変特徴を評価"),
    SpecialistDefinition(id="TR-028", name="ドメイン固有特徴評価者", category="transfer", archetype=Archetype.PRECISION, focus="ドメイン固有特徴を評価"),
    SpecialistDefinition(id="TR-029", name="マルチソース転移評価者", category="transfer", archetype=Archetype.PRECISION, focus="マルチソース転移を評価"),
    SpecialistDefinition(id="TR-030", name="階層的転移評価者", category="transfer", archetype=Archetype.PRECISION, focus="階層的転移を評価"),
    SpecialistDefinition(id="TR-031", name="クロスモーダル転移評価者", category="transfer", archetype=Archetype.PRECISION, focus="クロスモーダル転移を評価"),
    SpecialistDefinition(id="TR-032", name="言語間転移評価者", category="transfer", archetype=Archetype.PRECISION, focus="言語間転移を評価"),
    SpecialistDefinition(id="TR-033", name="タスク間転移評価者", category="transfer", archetype=Archetype.PRECISION, focus="タスク間転移を評価"),
    SpecialistDefinition(id="TR-034", name="概念的知識転移評価者", category="transfer", archetype=Archetype.PRECISION, focus="概念的知識転移を評価"),
    SpecialistDefinition(id="TR-035", name="手続き的知識転移評価者", category="transfer", archetype=Archetype.PRECISION, focus="手続き的知識転移を評価"),
    SpecialistDefinition(id="TR-036", name="転移効率評価者", category="transfer", archetype=Archetype.SPEED, focus="転移効率を評価"),
    SpecialistDefinition(id="TR-037", name="転移コスト評価者", category="transfer", archetype=Archetype.PRECISION, focus="転移コストを評価"),
    SpecialistDefinition(id="TR-038", name="転移安定性評価者", category="transfer", archetype=Archetype.PRECISION, focus="転移安定性を評価"),
    SpecialistDefinition(id="TR-039", name="転移汎化評価者", category="transfer", archetype=Archetype.PRECISION, focus="転移汎化を評価"),
    SpecialistDefinition(id="TR-040", name="転移ロバストネス評価者", category="transfer", archetype=Archetype.PRECISION, focus="転移ロバストネスを評価"),
]

# Phase 3 Layer 16-20 合計: 50 + 45 + 55 + 40 + 40 = 230人
PHASE3_SPECIALISTS = (
    DSL_SPECIALISTS +
    FORMAL_SPECIALISTS +
    ML_SPECIALISTS +
    STATS_SPECIALISTS +
    TRANSFER_SPECIALISTS
)
