#!/usr/bin/env python3
# PROOF: [L3/ユーティリティ] O4→実行スクリプトが必要→phase2_specialists が担う
"""
Jules 専門家定義: Phase 2 運用・実務層 (Layer 7-15: 290人)
"""
from .specialist_prompts import SpecialistDefinition, Archetype

# === Layer 7: 運用・可観測性層 (40人) ===
OBSERVABILITY_SPECIALISTS = [
    SpecialistDefinition(id="OB-001", name="ログレベル戦略評価者", category="observability", archetype=Archetype.PRECISION, focus="DEBUG/INFO/WARN/ERRORの適切な分類を評価"),
    SpecialistDefinition(id="OB-002", name="構造化ログ実装評価者", category="observability", archetype=Archetype.PRECISION, focus="JSON/protobuf形式のログ構造を評価"),
    SpecialistDefinition(id="OB-003", name="トレースID伝播評価者", category="observability", archetype=Archetype.PRECISION, focus="分散トレーシングのContext propagationを評価"),
    SpecialistDefinition(id="OB-004", name="メトリクス粒度評価者", category="observability", archetype=Archetype.PRECISION, focus="時系列データの粒度とcardinality爆発防止を評価"),
    SpecialistDefinition(id="OB-005", name="スパン作成戦略評価者", category="observability", archetype=Archetype.PRECISION, focus="過度なinstrumentationによるオーバーヘッドを評価"),
    SpecialistDefinition(id="OB-006", name="ホットパス/コールドパス評価者", category="observability", archetype=Archetype.PRECISION, focus="トレース対象領域の選別を評価"),
    SpecialistDefinition(id="OB-007", name="サンプリング戦略評価者", category="observability", archetype=Archetype.PRECISION, focus="Probabilistic vs Deterministicサンプリングを評価"),
    SpecialistDefinition(id="OB-008", name="アラート閾値評価者", category="observability", archetype=Archetype.PRECISION, focus="false positive/negative の平衡を評価"),
    SpecialistDefinition(id="OB-009", name="SLO/SLI定義評価者", category="observability", archetype=Archetype.PRECISION, focus="ユーザー中心のSLO定義を評価"),
    SpecialistDefinition(id="OB-010", name="Dashboard可読性評価者", category="observability", archetype=Archetype.CREATIVE, focus="情報密度と認知負荷のバランスを評価"),
    SpecialistDefinition(id="OB-011", name="ログ集約戦略評価者", category="observability", archetype=Archetype.PRECISION, focus="Centralized vs Distributedログ戦略を評価"),
    SpecialistDefinition(id="OB-012", name="トレースバックエンド評価者", category="observability", archetype=Archetype.PRECISION, focus="Jaeger/Zipkin/Tempo等の選択を評価"),
    SpecialistDefinition(id="OB-013", name="メトリクス保持ポリシー評価者", category="observability", archetype=Archetype.PRECISION, focus="hot/warm/coldストレージ戦略を評価"),
    SpecialistDefinition(id="OB-014", name="カスタムメトリクス設計評価者", category="observability", archetype=Archetype.PRECISION, focus="ビジネスKPIメトリクス実装を評価"),
    SpecialistDefinition(id="OB-015", name="Correlation ID使用評価者", category="observability", archetype=Archetype.PRECISION, focus="リクエスト全体の追跡可能性を評価"),
    SpecialistDefinition(id="OB-016", name="エラー率追跡評価者", category="observability", archetype=Archetype.PRECISION, focus="一時的/永続的エラーの分類を評価"),
    SpecialistDefinition(id="OB-017", name="レイテンシパーセンタイル評価者", category="observability", archetype=Archetype.PRECISION, focus="p50/p95/p99/p99.9の監視を評価"),
    SpecialistDefinition(id="OB-018", name="リソース利用率監視評価者", category="observability", archetype=Archetype.PRECISION, focus="CPU/Memory/Disk I/O/Networkの詳細化を評価"),
    SpecialistDefinition(id="OB-019", name="ヘルスチェック設計評価者", category="observability", archetype=Archetype.SAFETY, focus="Readiness/Liveness probes設計を評価"),
    SpecialistDefinition(id="OB-020", name="カナリアデプロイ監視評価者", category="observability", archetype=Archetype.SAFETY, focus="段階的ロールアウト時の異常検出を評価"),
    SpecialistDefinition(id="OB-021", name="ログフォーマット一貫性評価者", category="observability", archetype=Archetype.PRECISION, focus="ログメッセージの形式統一を評価"),
    SpecialistDefinition(id="OB-022", name="メトリクス命名規則評価者", category="observability", archetype=Archetype.PRECISION, focus="Prometheus命名規則遵守を評価"),
    SpecialistDefinition(id="OB-023", name="トレースサンプリング効率評価者", category="observability", archetype=Archetype.PRECISION, focus="tail latencyへのサンプリング影響を評価"),
    SpecialistDefinition(id="OB-024", name="アラート重複排除評価者", category="observability", archetype=Archetype.PRECISION, focus="アラートノイズ削減を評価"),
    SpecialistDefinition(id="OB-025", name="ダッシュボード応答性評価者", category="observability", archetype=Archetype.SPEED, focus="ダッシュボードのクエリ性能を評価"),
    SpecialistDefinition(id="OB-026", name="ログローテーション設定評価者", category="observability", archetype=Archetype.PRECISION, focus="ログファイル管理を評価"),
    SpecialistDefinition(id="OB-027", name="メトリクスカーディナリティ評価者", category="observability", archetype=Archetype.PRECISION, focus="高カーディナリティラベル使用を検出"),
    SpecialistDefinition(id="OB-028", name="分散トレーシング範囲評価者", category="observability", archetype=Archetype.PRECISION, focus="サービス間トレース網羅性を評価"),
    SpecialistDefinition(id="OB-029", name="障害検出時間評価者", category="observability", archetype=Archetype.SAFETY, focus="MTTD(Mean Time To Detect)を評価"),
    SpecialistDefinition(id="OB-030", name="アラートエスカレーション評価者", category="observability", archetype=Archetype.SAFETY, focus="エスカレーションポリシーを評価"),
    SpecialistDefinition(id="OB-031", name="ログ検索性能評価者", category="observability", archetype=Archetype.SPEED, focus="ログクエリ応答時間を評価"),
    SpecialistDefinition(id="OB-032", name="メトリクス集計精度評価者", category="observability", archetype=Archetype.PRECISION, focus="集計関数の正確性を評価"),
    SpecialistDefinition(id="OB-033", name="トレースデータ保持評価者", category="observability", archetype=Archetype.PRECISION, focus="トレースデータ保持期間を評価"),
    SpecialistDefinition(id="OB-034", name="アラート疲労検出者", category="observability", archetype=Archetype.SAFETY, focus="アラートfalse positive疲労を検出"),
    SpecialistDefinition(id="OB-035", name="SLOバジェット消費評価者", category="observability", archetype=Archetype.PRECISION, focus="エラーバジェット消費率を評価"),
    SpecialistDefinition(id="OB-036", name="合成監視設計評価者", category="observability", archetype=Archetype.PRECISION, focus="Synthetic monitoring設計を評価"),
    SpecialistDefinition(id="OB-037", name="リアルユーザー監視評価者", category="observability", archetype=Archetype.PRECISION, focus="RUM(Real User Monitoring)設計を評価"),
    SpecialistDefinition(id="OB-038", name="プロファイリング統合評価者", category="observability", archetype=Archetype.PRECISION, focus="継続的プロファイリング統合を評価"),
    SpecialistDefinition(id="OB-039", name="コスト最適化評価者", category="observability", archetype=Archetype.PRECISION, focus="可観測性コスト最適化を評価"),
    SpecialistDefinition(id="OB-040", name="アノマリー検出設定評価者", category="observability", archetype=Archetype.PRECISION, focus="異常検出アルゴリズム設定を評価"),
]

# === Layer 8: 技術的債務追跡層 (35人) ===
TECH_DEBT_SPECIALISTS = [
    SpecialistDefinition(id="TD-001", name="循環的複雑度評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="Cyclomatic complexity (>15は危険)を評価"),
    SpecialistDefinition(id="TD-002", name="認知的複雑度評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="人間的理解の難しさを評価"),
    SpecialistDefinition(id="TD-003", name="コードチャーン率評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="変更頻度が高い部分を特定"),
    SpecialistDefinition(id="TD-004", name="コード重複評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="Copy-pasteによる重複(>5%は問題)を検出"),
    SpecialistDefinition(id="TD-005", name="技術的債務比率評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="TDR = 修正時間/開発時間 (目標<5%)を評価"),
    SpecialistDefinition(id="TD-006", name="ホットスポット特定者", category="tech_debt", archetype=Archetype.PRECISION, focus="複雑かつ頻繁に変更される領域を特定"),
    SpecialistDefinition(id="TD-007", name="保守性インデックス評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="総合保守性スコア(0-100)を評価"),
    SpecialistDefinition(id="TD-008", name="コメント比率評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="ドキュメント不足を検出"),
    SpecialistDefinition(id="TD-009", name="テストカバレッジ債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="未テスト領域を可視化"),
    SpecialistDefinition(id="TD-010", name="アーキテクチャ劣化評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="依存関係の循環性、層の崩壊を検出"),
    SpecialistDefinition(id="TD-011", name="ビルド時間債務評価者", category="tech_debt", archetype=Archetype.SPEED, focus="ビルド時間の増加トレンドを評価"),
    SpecialistDefinition(id="TD-012", name="ドキュメント陳腐化評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="ドキュメントと実装のズレを検出"),
    SpecialistDefinition(id="TD-013", name="API非推奨管理評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="古いAPIの段階的廃止戦略を評価"),
    SpecialistDefinition(id="TD-014", name="レガシーコード島評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="孤立した古いコードを特定"),
    SpecialistDefinition(id="TD-015", name="債務利息コスト評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="将来のコスト推定を評価"),
    SpecialistDefinition(id="TD-016", name="リファクタリング工数見積者", category="tech_debt", archetype=Archetype.PRECISION, focus="リファクタリング工数を見積もり"),
    SpecialistDefinition(id="TD-017", name="ファイル別複雑度評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="ファイル粒度での複雑度バランスを評価"),
    SpecialistDefinition(id="TD-018", name="依存関係地獄回避評価者", category="tech_debt", archetype=Archetype.SAFETY, focus="依存関係の版管理問題を検出"),
    SpecialistDefinition(id="TD-019", name="セキュリティ債務評価者", category="tech_debt", archetype=Archetype.SAFETY, focus="セキュリティ脆弱性の遅延修正を検出"),
    SpecialistDefinition(id="TD-020", name="パフォーマンス債務評価者", category="tech_debt", archetype=Archetype.SPEED, focus="パフォーマンス問題の未対応を検出"),
    SpecialistDefinition(id="TD-021", name="フレームワーク更新債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="メジャーバージョン遅延を評価"),
    SpecialistDefinition(id="TD-022", name="DBスキーマ進化評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="スキーマの歴史的負債を評価"),
    SpecialistDefinition(id="TD-023", name="監視盲点評価者", category="tech_debt", archetype=Archetype.SAFETY, focus="監視されていないコード部分を検出"),
    SpecialistDefinition(id="TD-024", name="技術決定記録評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="ADR(Architecture Decision Record)を評価"),
    SpecialistDefinition(id="TD-025", name="コードスタイル一貫性債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="スタイル違反の蓄積を評価"),
    SpecialistDefinition(id="TD-026", name="モジュール性劣化評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="モジュール結合度の増加を検出"),
    SpecialistDefinition(id="TD-027", name="テスト債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="テストコードの品質低下を評価"),
    SpecialistDefinition(id="TD-028", name="依存バージョン遅延評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="依存ライブラリの更新遅れを評価"),
    SpecialistDefinition(id="TD-029", name="オンボーディング債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="新規開発者の学習曲線を評価"),
    SpecialistDefinition(id="TD-030", name="知識サイロ評価者", category="tech_debt", archetype=Archetype.SAFETY, focus="ドメイン知識の集中(バス係数)を評価"),
    SpecialistDefinition(id="TD-031", name="ロギング/監視債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="本番環境の可観測性不足を評価"),
    SpecialistDefinition(id="TD-032", name="エラーハンドリング債務評価者", category="tech_debt", archetype=Archetype.SAFETY, focus="甘い例外処理を検出"),
    SpecialistDefinition(id="TD-033", name="設定管理債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="設定の硬化度、マジックナンバーを評価"),
    SpecialistDefinition(id="TD-034", name="SQLクエリ債務評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="インデックス欠落、N+1問題を評価"),
    SpecialistDefinition(id="TD-035", name="債務可視化評価者", category="tech_debt", archetype=Archetype.PRECISION, focus="ダッシュボードの公開度を評価"),
]

# === Layer 9: 分散システム層 (45人) ===
DISTRIBUTED_SPECIALISTS = [
    SpecialistDefinition(id="DS-001", name="原子性レベル評価者", category="distributed", archetype=Archetype.PRECISION, focus="単一doc vs multi-doc transactionを評価"),
    SpecialistDefinition(id="DS-002", name="一貫性モデル評価者", category="distributed", archetype=Archetype.PRECISION, focus="Strong vs Eventual一貫性選択を評価"),
    SpecialistDefinition(id="DS-003", name="分離レベル評価者", category="distributed", archetype=Archetype.PRECISION, focus="Serializable/RR/RC/RU適切性を評価"),
    SpecialistDefinition(id="DS-004", name="永続性保証評価者", category="distributed", archetype=Archetype.SAFETY, focus="WAL等の永続性設定を評価"),
    SpecialistDefinition(id="DS-005", name="分散トランザクションパターン評価者", category="distributed", archetype=Archetype.PRECISION, focus="Saga/Event sourcing/2PCを評価"),
    SpecialistDefinition(id="DS-006", name="Sagaオーケストレーション評価者", category="distributed", archetype=Archetype.PRECISION, focus="choreography vs orchestrationを評価"),
    SpecialistDefinition(id="DS-007", name="イベントソーシング完全性評価者", category="distributed", archetype=Archetype.PRECISION, focus="イベント履歴の記録度を評価"),
    SpecialistDefinition(id="DS-008", name="CDC実装評価者", category="distributed", archetype=Archetype.PRECISION, focus="Change Data Capture戦略を評価"),
    SpecialistDefinition(id="DS-009", name="分散ロック戦略評価者", category="distributed", archetype=Archetype.SAFETY, focus="Optimistic/Pessimisticロックを評価"),
    SpecialistDefinition(id="DS-010", name="ロック陳腐化検出者", category="distributed", archetype=Archetype.SAFETY, focus="古いロックの自動解放を評価"),
    SpecialistDefinition(id="DS-011", name="スナップショット分離評価者", category="distributed", archetype=Archetype.PRECISION, focus="Read一貫性を評価"),
    SpecialistDefinition(id="DS-012", name="書き込み競合解決評価者", category="distributed", archetype=Archetype.PRECISION, focus="LWW/カスタムロジックを評価"),
    SpecialistDefinition(id="DS-013", name="Quorum一貫性評価者", category="distributed", archetype=Archetype.PRECISION, focus="Write/Read quorumバランスを評価"),
    SpecialistDefinition(id="DS-014", name="ネットワーク分断耐性評価者", category="distributed", archetype=Archetype.SAFETY, focus="Partition時のdegradation modeを評価"),
    SpecialistDefinition(id="DS-015", name="ビザンチン障害耐性評価者", category="distributed", archetype=Archetype.SAFETY, focus="悪意あるノードへの耐性を評価"),
    SpecialistDefinition(id="DS-016", name="結果整合性時間評価者", category="distributed", archetype=Archetype.PRECISION, focus="一貫性到達期間を評価"),
    SpecialistDefinition(id="DS-017", name="冪等性キー使用評価者", category="distributed", archetype=Archetype.SAFETY, focus="リトライの安全性を評価"),
    SpecialistDefinition(id="DS-018", name="重複排除ウィンドウ評価者", category="distributed", archetype=Archetype.PRECISION, focus="重複排除の時間枠を評価"),
    SpecialistDefinition(id="DS-019", name="リトライ戦略差別化評価者", category="distributed", archetype=Archetype.PRECISION, focus="一時的/永続的エラー分類を評価"),
    SpecialistDefinition(id="DS-020", name="指数バックオフ実装評価者", category="distributed", archetype=Archetype.PRECISION, focus="リトライのバースト防止を評価"),
    SpecialistDefinition(id="DS-021", name="サーキットブレーカーパターン評価者", category="distributed", archetype=Archetype.SAFETY, focus="カスケード障害防止を評価"),
    SpecialistDefinition(id="DS-022", name="バルクヘッド分離評価者", category="distributed", archetype=Archetype.SAFETY, focus="リソース隔離を評価"),
    SpecialistDefinition(id="DS-023", name="タイムアウト設定評価者", category="distributed", archetype=Archetype.PRECISION, focus="タイムアウトカスケードを評価"),
    SpecialistDefinition(id="DS-024", name="グレースフルデグラデーション評価者", category="distributed", archetype=Archetype.SAFETY, focus="サービス品質段階的低下を評価"),
    SpecialistDefinition(id="DS-025", name="データ調整評価者", category="distributed", archetype=Archetype.PRECISION, focus="定期的一貫性チェックを評価"),
    SpecialistDefinition(id="DS-026", name="コンセンサスプロトコル安全性評価者", category="distributed", archetype=Archetype.SAFETY, focus="Raft/Paxos安全性を評価"),
    SpecialistDefinition(id="DS-027", name="レプリケーション遅延監視評価者", category="distributed", archetype=Archetype.PRECISION, focus="レプリカ遅延追跡を評価"),
    SpecialistDefinition(id="DS-028", name="読み取りレプリカ陳腐化評価者", category="distributed", archetype=Archetype.PRECISION, focus="読み取り専用レプリカ古さ許容度を評価"),
    SpecialistDefinition(id="DS-029", name="書き込み転送戦略評価者", category="distributed", archetype=Archetype.PRECISION, focus="single-writerパターンを評価"),
    SpecialistDefinition(id="DS-030", name="災害復旧テスト評価者", category="distributed", archetype=Archetype.SAFETY, focus="DRテスト頻度と成功率を評価"),
    SpecialistDefinition(id="DS-031", name="バックアップ一貫性検証評価者", category="distributed", archetype=Archetype.SAFETY, focus="バックアップ整合性を評価"),
    SpecialistDefinition(id="DS-032", name="ポイントインタイムリカバリ評価者", category="distributed", archetype=Archetype.SAFETY, focus="特定時点復帰可能性を評価"),
    SpecialistDefinition(id="DS-033", name="クロスリージョンレプリケーション評価者", category="distributed", archetype=Archetype.PRECISION, focus="地理的冗長性戦略を評価"),
    SpecialistDefinition(id="DS-034", name="データローカリティ評価者", category="distributed", archetype=Archetype.PRECISION, focus="ローカルデータ vs グローバルアクセスを評価"),
    SpecialistDefinition(id="DS-035", name="単調読み取り/書き込み一貫性評価者", category="distributed", archetype=Archetype.PRECISION, focus="クライアント側一貫性を評価"),
    SpecialistDefinition(id="DS-036", name="因果一貫性実装評価者", category="distributed", archetype=Archetype.PRECISION, focus="因果関係のあるイベント順序を評価"),
    SpecialistDefinition(id="DS-037", name="ベクタークロック評価者", category="distributed", archetype=Archetype.PRECISION, focus="分散タイムスタンプ戦略を評価"),
    SpecialistDefinition(id="DS-038", name="CRDT評価者", category="distributed", archetype=Archetype.PRECISION, focus="Conflict-free replicated data typesを評価"),
    SpecialistDefinition(id="DS-039", name="OT評価者", category="distributed", archetype=Archetype.PRECISION, focus="Operational transformationを評価"),
    SpecialistDefinition(id="DS-040", name="カスケード障害防止評価者", category="distributed", archetype=Archetype.SAFETY, focus="障害連鎖的拡大防止を評価"),
    SpecialistDefinition(id="DS-041", name="グレースフルシャットダウン評価者", category="distributed", archetype=Archetype.SAFETY, focus="ノード停止時データ保護を評価"),
    SpecialistDefinition(id="DS-042", name="分散ヘルスチェック評価者", category="distributed", archetype=Archetype.SAFETY, focus="複数ノードからの健全性判定を評価"),
    SpecialistDefinition(id="DS-043", name="サービス間依存関係監視評価者", category="distributed", archetype=Archetype.PRECISION, focus="マイクロサービス依存関係可視化を評価"),
    SpecialistDefinition(id="DS-044", name="サービスメッシュ設定評価者", category="distributed", archetype=Archetype.PRECISION, focus="Istio/Linkerd設定を評価"),
    SpecialistDefinition(id="DS-045", name="分散トレーシング完全性評価者", category="distributed", archetype=Archetype.PRECISION, focus="end-to-endトレース完全性を評価"),
]

# === Layer 10: パフォーマンス・スケーラビリティ層 (50人) ===
PERFORMANCE_SPECIALISTS = [
    SpecialistDefinition(id="PF-001", name="CPUバウンドワークロード検出者", category="performance", archetype=Archetype.PRECISION, focus="CPU利用率>80%の持続を検出"),
    SpecialistDefinition(id="PF-002", name="I/Oバウンドワークロード検出者", category="performance", archetype=Archetype.PRECISION, focus="I/O wait timeを測定"),
    SpecialistDefinition(id="PF-003", name="メモリバウンド検出者", category="performance", archetype=Archetype.PRECISION, focus="Cache miss rate増加、swap使用を検出"),
    SpecialistDefinition(id="PF-004", name="アルゴリズム複雑度分析者", category="performance", archetype=Archetype.PRECISION, focus="Big-O分析、不適切なアルゴリズムを検出"),
    SpecialistDefinition(id="PF-005", name="プロファイリングオーバーヘッド評価者", category="performance", archetype=Archetype.PRECISION, focus="Profiler自体のオーバーヘッドを評価"),
    SpecialistDefinition(id="PF-006", name="ホットパス特定者", category="performance", archetype=Archetype.PRECISION, focus="実行時間80%を占めるコードを特定"),
    SpecialistDefinition(id="PF-007", name="コールドパス最適化必要性評価者", category="performance", archetype=Archetype.PRECISION, focus="最適化ROIを判定"),
    SpecialistDefinition(id="PF-008", name="多層キャッシュ戦略評価者", category="performance", archetype=Archetype.PRECISION, focus="L1/L2/L3キャッシング戦略を評価"),
    SpecialistDefinition(id="PF-009", name="キャッシュ無効化正確性評価者", category="performance", archetype=Archetype.PRECISION, focus="TTL/LRU/Write-through設定を評価"),
    SpecialistDefinition(id="PF-010", name="キャッシュポイズニング脆弱性評価者", category="performance", archetype=Archetype.SAFETY, focus="有害キャッシュデータを検出"),
    SpecialistDefinition(id="PF-011", name="静的メモリリーク検出者", category="performance", archetype=Archetype.SAFETY, focus="静的解析によるメモリリークを検出"),
    SpecialistDefinition(id="PF-012", name="動的メモリリーク検出者", category="performance", archetype=Archetype.SAFETY, focus="動的解析によるメモリリークを検出"),
    SpecialistDefinition(id="PF-013", name="メモリリーク分類者", category="performance", archetype=Archetype.PRECISION, focus="MUST-LEAK/LIKELY-NOT-LEAKを分類"),
    SpecialistDefinition(id="PF-014", name="バッファオーバーフロー防止評価者", category="performance", archetype=Archetype.SAFETY, focus="Bounds checkingを評価"),
    SpecialistDefinition(id="PF-015", name="スタックオーバーフロー防止評価者", category="performance", archetype=Archetype.SAFETY, focus="再帰深度制限を評価"),
    SpecialistDefinition(id="PF-016", name="コネクションプール最適化評価者", category="performance", archetype=Archetype.PRECISION, focus="Min/Max connection count設定を評価"),
    SpecialistDefinition(id="PF-017", name="N+1クエリ検出者", category="performance", archetype=Archetype.PRECISION, focus="Eager loading必要性を検出"),
    SpecialistDefinition(id="PF-018", name="インデックス最適化推奨者", category="performance", archetype=Archetype.PRECISION, focus="Missing/unused indexesを検出"),
    SpecialistDefinition(id="PF-019", name="クエリプランキャッシュ陳腐化評価者", category="performance", archetype=Archetype.PRECISION, focus="古いクエリプラン影響を評価"),
    SpecialistDefinition(id="PF-020", name="SQL JOIN戦略評価者", category="performance", archetype=Archetype.PRECISION, focus="Hash/Nested loop/Sort-merge選択を評価"),
    SpecialistDefinition(id="PF-021", name="DB統計陳腐化評価者", category="performance", archetype=Archetype.PRECISION, focus="インデックス統計更新頻度を評価"),
    SpecialistDefinition(id="PF-022", name="パーティショニング/シャーディング効果評価者", category="performance", archetype=Archetype.PRECISION, focus="テーブル分割効果を評価"),
    SpecialistDefinition(id="PF-023", name="データ型不一致評価者", category="performance", archetype=Archetype.PRECISION, focus="型変換オーバーヘッドを検出"),
    SpecialistDefinition(id="PF-024", name="ソートアルゴリズム選択評価者", category="performance", archetype=Archetype.PRECISION, focus="Quicksort/Mergesort選択を評価"),
    SpecialistDefinition(id="PF-025", name="正規表現性能評価者", category="performance", archetype=Archetype.PRECISION, focus="Catastrophic backtracking防止を評価"),
    SpecialistDefinition(id="PF-026", name="文字列操作効率評価者", category="performance", archetype=Archetype.PRECISION, focus="String concatenation効率を評価"),
    SpecialistDefinition(id="PF-027", name="ループ最適化機会評価者", category="performance", archetype=Archetype.PRECISION, focus="Loop unrolling/vectorizationを評価"),
    SpecialistDefinition(id="PF-028", name="関数呼び出しオーバーヘッド評価者", category="performance", archetype=Archetype.PRECISION, focus="Inline expansion候補を特定"),
    SpecialistDefinition(id="PF-029", name="メモリ割り当て/解放オーバーヘッド評価者", category="performance", archetype=Archetype.PRECISION, focus="malloc/free頻度を評価"),
    SpecialistDefinition(id="PF-030", name="ページフォルト評価者", category="performance", archetype=Archetype.PRECISION, focus="メモリアクセスパターン最適化を評価"),
    SpecialistDefinition(id="PF-031", name="CPUキャッシュライン衝突評価者", category="performance", archetype=Archetype.PRECISION, focus="False sharing検出"),
    SpecialistDefinition(id="PF-032", name="SIMD/ベクトル化機会評価者", category="performance", archetype=Archetype.PRECISION, focus="並列化可能ループを特定"),
    SpecialistDefinition(id="PF-033", name="GPU高速化候補評価者", category="performance", archetype=Archetype.PRECISION, focus="CUDA/OpenCL移行対象を評価"),
    SpecialistDefinition(id="PF-034", name="負荷テスト準備状況評価者", category="performance", archetype=Archetype.PRECISION, focus="負荷試験環境準備度を評価"),
    SpecialistDefinition(id="PF-035", name="スケーラビリティテスト方法論評価者", category="performance", archetype=Archetype.PRECISION, focus="垂直/水平スケーリングテストを評価"),
    SpecialistDefinition(id="PF-036", name="ストレステスト結果解釈者", category="performance", archetype=Archetype.PRECISION, focus="ボトルネック特定、破断点検出"),
    SpecialistDefinition(id="PF-037", name="プロファイリングデータ鮮度評価者", category="performance", archetype=Archetype.PRECISION, focus="古いプロファイルデータ使用可能性を評価"),
    SpecialistDefinition(id="PF-038", name="ベンチマークスイート網羅性評価者", category="performance", archetype=Archetype.PRECISION, focus="代表的ワークロード選定を評価"),
    SpecialistDefinition(id="PF-039", name="パフォーマンス回帰検出者", category="performance", archetype=Archetype.PRECISION, focus="CI/CDでの自動検出を評価"),
    SpecialistDefinition(id="PF-040", name="レイテンシテール最適化評価者", category="performance", archetype=Archetype.PRECISION, focus="p99 latency改善を評価"),
    SpecialistDefinition(id="PF-041", name="スループット飽和点評価者", category="performance", archetype=Archetype.PRECISION, focus="リソース飽和時スループットを評価"),
    SpecialistDefinition(id="PF-042", name="電力効率評価者", category="performance", archetype=Archetype.PRECISION, focus="ワットあたりスループットを評価"),
    SpecialistDefinition(id="PF-043", name="ネットワーク最適化評価者", category="performance", archetype=Archetype.PRECISION, focus="TCPチューニングを評価"),
    SpecialistDefinition(id="PF-044", name="ディスクI/O最適化評価者", category="performance", archetype=Archetype.PRECISION, focus="Sequential/random access最適化を評価"),
    SpecialistDefinition(id="PF-045", name="バッチ/リアルタイムトレードオフ評価者", category="performance", archetype=Archetype.PRECISION, focus="バッチ処理影響を評価"),
    SpecialistDefinition(id="PF-046", name="GC(ガベージコレクション)チューニング評価者", category="performance", archetype=Archetype.PRECISION, focus="GC pause time最適化を評価"),
    SpecialistDefinition(id="PF-047", name="メモリプール評価者", category="performance", archetype=Archetype.PRECISION, focus="オブジェクトプール使用を評価"),
    SpecialistDefinition(id="PF-048", name="スレッドプールサイジング評価者", category="performance", archetype=Archetype.PRECISION, focus="スレッドプールサイズ最適化を評価"),
    SpecialistDefinition(id="PF-049", name="非同期処理効率評価者", category="performance", archetype=Archetype.PRECISION, focus="async/await効率を評価"),
    SpecialistDefinition(id="PF-050", name="リソース枯渇検出者", category="performance", archetype=Archetype.SAFETY, focus="コネクション/ファイルハンドル枯渇を検出"),
]

# === 追加層の定義はphase2_remaining.pyに続く ===

# Phase 2 Layer 7-10 合計: 40 + 35 + 45 + 50 = 170人
PHASE2_LAYER_7_10_SPECIALISTS = (
    OBSERVABILITY_SPECIALISTS +
    TECH_DEBT_SPECIALISTS +
    DISTRIBUTED_SPECIALISTS +
    PERFORMANCE_SPECIALISTS
)
