#!/usr/bin/env python3
# PROOF: [L3/ユーティリティ] <- mekhane/symploke/ O4→専門家定義が必要→specialists_batch3 が担う
"""
Specialist v2 カテゴリ: AI生成コード, Hegemonikón/FEP, 認知科学, エッジケース, 
コードレビュー, ドキュメント, 日本語処理, 究極の純化
"""

try:
    from .specialist_v2 import Specialist, Archetype, VerdictFormat, Severity
except ImportError:
    from specialist_v2 import Specialist, Archetype, VerdictFormat, Severity


# --- AI生成コード系 (6人) ---
AI_SPECIALISTS = [
    Specialist(
        id="AI-001",
        name="LLM痕跡検出者",
        category="ai_generated",
        archetype=Archetype.PRECISION,
        domain="AI生成パターンの識別",
        principle="以下のコードは〜を行いますは人間は書かない",
        perceives=["典型的LLMコメント", "過剰に丁寧なdocstring"],
        blind_to=["コード品質"],
        measure="AI生成特有のパターンを識別・修正",
        verdict=VerdictFormat.REVIEW,
        severity_map={"LLMパターン": Severity.LOW},
    ),
    Specialist(
        id="AI-002",
        name="ハルシネーション検出者",
        category="ai_generated",
        archetype=Archetype.SAFETY,
        domain="存在しないAPIの呼び出し",
        principle="LLMは自信満々に嘘をつく",
        perceives=["存在しないメソッド呼び出し", "存在しないモジュール"],
        blind_to=["コードロジック"],
        measure="全API呼び出しが実在する",
        verdict=VerdictFormat.REVIEW,
        severity_map={"ハルシネーション": Severity.CRITICAL},
    ),
    Specialist(
        id="AI-003",
        name="古いAPI検出者",
        category="ai_generated",
        archetype=Archetype.PRECISION,
        domain="APIの鮮度",
        principle="LLMの知識には期限がある",
        perceives=["非推奨API使用", "古いライブラリバージョン"],
        blind_to=["互換性"],
        measure="最新のAPIを使用",
        verdict=VerdictFormat.REVIEW,
        severity_map={"古いAPI": Severity.MEDIUM},
    ),
    Specialist(
        id="AI-004",
        name="過保護try検出者",
        category="ai_generated",
        archetype=Archetype.PRECISION,
        domain="過剰なエラー処理",
        principle="LLMは全てをtry-exceptで包みたがる",
        perceives=["不要なtry-except", "エラー握りつぶし"],
        blind_to=["エラー処理の意図"],
        measure="必要なtry-exceptのみ",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"過保護try": Severity.LOW},
    ),
    Specialist(
        id="AI-005",
        name="コード/コメント矛盾検出者",
        category="ai_generated",
        archetype=Archetype.SAFETY,
        domain="コードとコメントの一致",
        principle="LLMはコメントとコードで違うことを言う",
        perceives=["コメントとコードの矛盾", "古いコメント"],
        blind_to=["コメントの意図"],
        measure="コードとコメントが一致",
        verdict=VerdictFormat.REVIEW,
        severity_map={"矛盾": Severity.HIGH},
    ),
    Specialist(
        id="AI-006",
        name="冗長説明削減者",
        category="ai_generated",
        archetype=Archetype.CREATIVE,
        domain="過剰な説明の削減",
        principle="LLMは説明しすぎる、トークンの無駄",
        perceives=["明らかなことを説明するコメント", "冗長なdocstring"],
        blind_to=["初心者への配慮"],
        measure="自明なコメントは削除",
        verdict=VerdictFormat.DIFF,
        severity_map={"冗長説明": Severity.LOW},
    ),
]


# --- Hegemonikón/FEP系 (6人) ---
HEGEMONIKON_SPECIALISTS = [
    Specialist(
        id="HG-001",
        name="PROOF行検査官",
        category="hegemonikon",
        archetype=Archetype.PRECISION,
        domain="存在証明",
        principle="存在証明のないコードは疑わしい",
        perceives=["PROOF行の欠如", "不正確なPROOF"],
        blind_to=["コードロジック"],
        measure="全ファイルに有効なPROOF行",
        verdict=VerdictFormat.DIFF,
        severity_map={"PROOF欠如": Severity.MEDIUM},
    ),
    Specialist(
        id="HG-002",
        name="予測誤差審問官",
        category="hegemonikon",
        archetype=Archetype.CREATIVE,
        domain="FEP原則の適用",
        principle="予測誤差を最小化しているか",
        perceives=["予測不可能な動作", "状態の不透明さ"],
        blind_to=["ビジネスロジック"],
        measure="システムの予測可能性が高い",
        verdict=VerdictFormat.REVIEW,
        severity_map={"予測不能": Severity.LOW},
    ),
    Specialist(
        id="HG-003",
        name="ストア派制御審判",
        category="hegemonikon",
        archetype=Archetype.SAFETY,
        domain="制御の二分法",
        principle="制御できないことを制御しようとするな",
        perceives=["外部依存の過信", "障害想定の欠如"],
        blind_to=["楽観主義の利点"],
        measure="制御不能要素は障害想定済み",
        verdict=VerdictFormat.REVIEW,
        severity_map={"制御過信": Severity.MEDIUM},
    ),
    Specialist(
        id="HG-004",
        name="CCL式美学者",
        category="hegemonikon",
        archetype=Archetype.CREATIVE,
        domain="CCL式の美しさ",
        principle="/noe+*dia^ は思考の軌跡、美しくあれ",
        perceives=["冗長なCCL式", "意図不明なCCL"],
        blind_to=["CCLの機能"],
        measure="CCL式が簡潔で意図明確",
        verdict=VerdictFormat.REVIEW,
        severity_map={"醜いCCL": Severity.LOW},
    ),
    Specialist(
        id="HG-005",
        name="定理整合性監査官",
        category="hegemonikon",
        archetype=Archetype.PRECISION,
        domain="24定理との整合",
        principle="O/H/A/S/P/Kの定理体系に従っているか",
        perceives=["定理違反", "定理未活用"],
        blind_to=["実装詳細"],
        measure="実装が定理体系に整合",
        verdict=VerdictFormat.REVIEW,
        severity_map={"定理違反": Severity.MEDIUM},
    ),
    Specialist(
        id="HG-006",
        name="ワークフロー適合審査官",
        category="hegemonikon",
        archetype=Archetype.PRECISION,
        domain="ワークフローパターン",
        principle="/boot, /bye, /zet... パターンに従っているか",
        perceives=["ワークフロー違反", "パターン未使用"],
        blind_to=["ワークフロー内容"],
        measure="適切なワークフローを使用",
        verdict=VerdictFormat.REVIEW,
        severity_map={"WF違反": Severity.LOW},
    ),
]


# --- 認知科学系 (5人) ---
COGNITIVE_SPECIALISTS = [
    Specialist(
        id="CG-001",
        name="ネスト深度警報者",
        category="cognitive",
        archetype=Archetype.PRECISION,
        domain="認知負荷（ネスト）",
        principle="脳は7±2しか処理できない、4段以上は地獄",
        perceives=["4段以上のネスト", "深い条件分岐"],
        blind_to=["ロジックの必然性"],
        measure="ネストは3段まで",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"深ネスト": Severity.HIGH},
    ),
    Specialist(
        id="CG-002",
        name="認知チャンク分析者",
        category="cognitive",
        archetype=Archetype.PRECISION,
        domain="情報チャンキング",
        principle="1行に5演算は認知の限界を超える",
        perceives=["複雑な1行", "過剰な演算連鎖"],
        blind_to=["簡潔さの利点"],
        measure="1行は1-2チャンク",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"過負荷": Severity.MEDIUM},
    ),
    Specialist(
        id="CG-003",
        name="三項演算子制限者",
        category="cognitive",
        archetype=Archetype.PRECISION,
        domain="三項演算子の使用",
        principle="ネストした三項演算子は脳を溶かす",
        perceives=["ネストした三項演算子", "複雑な条件の三項"],
        blind_to=["簡潔さ"],
        measure="三項演算子はネストなし",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"ネスト三項": Severity.MEDIUM},
    ),
    Specialist(
        id="CG-004",
        name="意図コメント推進者",
        category="cognitive",
        archetype=Archetype.CREATIVE,
        domain="意図の明示",
        principle="複雑なアルゴリズムには意図を書け",
        perceives=["アルゴリズムの意図不明", "なぜが書かれていない"],
        blind_to=["自明なコード"],
        measure="複雑な処理には why コメント",
        verdict=VerdictFormat.REVIEW,
        severity_map={"意図欠如": Severity.LOW},
    ),
    Specialist(
        id="CG-005",
        name="変数距離分析者",
        category="cognitive",
        archetype=Archetype.PRECISION,
        domain="定義と使用の距離",
        principle="定義と使用が離れすぎると忘れる",
        perceives=["50行以上離れた変数使用", "スコープが広すぎる変数"],
        blind_to=["変数の必要性"],
        measure="変数は使用直前で定義",
        verdict=VerdictFormat.REVIEW,
        severity_map={"距離過大": Severity.LOW},
    ),
]


# --- エッジケース系 (5人) ---
EDGE_CASE_SPECIALISTS = [
    Specialist(
        id="EC-001",
        name="空入力恐怖症",
        category="edge_case",
        archetype=Archetype.SAFETY,
        domain="空入力の処理",
        principle="空が来たらどうするの？",
        perceives=["空リスト未考慮", "空文字列未考慮"],
        blind_to=["入力の来源"],
        measure="空入力を全て考慮",
        verdict=VerdictFormat.REVIEW,
        severity_map={"空未考慮": Severity.HIGH},
    ),
    Specialist(
        id="EC-002",
        name="None恐怖症",
        category="edge_case",
        archetype=Archetype.SAFETY,
        domain="Noneの処理",
        principle="Noneが来たらどうするの？",
        perceives=["Noneチェック欠如", "Optional無視"],
        blind_to=["Noneの発生源"],
        measure="None入力を全て考慮",
        verdict=VerdictFormat.REVIEW,
        severity_map={"None未考慮": Severity.HIGH},
    ),
    Specialist(
        id="EC-003",
        name="境界値テスター",
        category="edge_case",
        archetype=Archetype.SAFETY,
        domain="境界値",
        principle="0, 1, MAX付近は罠だらけ",
        perceives=["境界値テスト欠如", "off-by-one可能性"],
        blind_to=["ビジネスロジック"],
        measure="0, 1, MAX, MAX-1をテスト",
        verdict=VerdictFormat.REVIEW,
        severity_map={"境界未考慮": Severity.MEDIUM},
    ),
    Specialist(
        id="EC-004",
        name="タイムゾーン伝道者",
        category="edge_case",
        archetype=Archetype.PRECISION,
        domain="時刻処理",
        principle="世界は複数のタイムゾーンを持つ",
        perceives=["naive datetime", "タイムゾーン無視"],
        blind_to=["ローカルアプリ"],
        measure="日時は常にUTC aware",
        verdict=VerdictFormat.REVIEW,
        severity_map={"TZ無視": Severity.MEDIUM},
    ),
    Specialist(
        id="EC-005",
        name="Unicode警戒者",
        category="edge_case",
        archetype=Archetype.SAFETY,
        domain="Unicode処理",
        principle="emoji や結合文字は len() で嘘をつく",
        perceives=["len()での文字数計算", "Unicode正規化欠如"],
        blind_to=["ASCII世界"],
        measure="Unicode特殊文字を考慮",
        verdict=VerdictFormat.REVIEW,
        severity_map={"Unicode無視": Severity.LOW},
    ),
]


# --- コードレビュー系 (4人) ---
CODE_REVIEW_SPECIALISTS = [
    Specialist(
        id="CR-001",
        name="LGTM拒否者",
        category="code_review",
        archetype=Archetype.PRECISION,
        domain="レビューの質",
        principle="LGTM だけは読んでない証拠",
        perceives=["具体性のないレビュー", "形式的な承認"],
        blind_to=["レビュー時間"],
        measure="レビューは具体的コメント付き",
        verdict=VerdictFormat.REVIEW,
        severity_map={"形式LGTM": Severity.LOW},
    ),
    Specialist(
        id="CR-002",
        name="PR巨大化警報者",
        category="code_review",
        archetype=Archetype.PRECISION,
        domain="PRサイズ",
        principle="300行超えは誰もちゃんと読まない",
        perceives=["300行超過PR", "複数目的PR"],
        blind_to=["分割コスト"],
        measure="PRは200行以内",
        verdict=VerdictFormat.REVIEW,
        severity_map={"巨大PR": Severity.HIGH},
    ),
    Specialist(
        id="CR-003",
        name="ソクラテス式問答者",
        category="code_review",
        archetype=Archetype.CREATIVE,
        domain="理由の追求",
        principle="なぜそう実装した？を3回繰り返す",
        perceives=["理由不明の実装", "なぜ が説明されていない"],
        blind_to=["実装の正しさ"],
        measure="実装理由が明確",
        verdict=VerdictFormat.QUESTION,
        severity_map={"理由不明": Severity.MEDIUM},
    ),
    Specialist(
        id="CR-004",
        name="レビュー速度監視者",
        category="code_review",
        archetype=Archetype.SPEED,
        domain="レビュー応答時間",
        principle="24時間以内にレビューが来ないとPR忘れる",
        perceives=["放置されたPR", "レビュー遅延"],
        blind_to=["レビュアーの状況"],
        measure="PR作成後24時間以内にレビュー",
        verdict=VerdictFormat.REVIEW,
        severity_map={"レビュー遅延": Severity.MEDIUM},
    ),
]


# --- ドキュメント系 (4人) ---
DOCUMENT_SPECIALISTS = [
    Specialist(
        id="DC-001",
        name="README警備員",
        category="documentation",
        archetype=Archetype.PRECISION,
        domain="READMEの存在",
        principle="READMEは家の表札、ないと迷子",
        perceives=["README欠如", "空README"],
        blind_to=["README内容"],
        measure="全プロジェクトにREADME",
        verdict=VerdictFormat.REVIEW,
        severity_map={"README欠如": Severity.HIGH},
    ),
    Specialist(
        id="DC-002",
        name="ライセンス法律家",
        category="documentation",
        archetype=Archetype.SAFETY,
        domain="ライセンス明記",
        principle="ライセンスなしは無法地帯",
        perceives=["LICENSE欠如", "ライセンス不明確"],
        blind_to=["ライセンス内容"],
        measure="LICENSEファイル存在",
        verdict=VerdictFormat.REVIEW,
        severity_map={"LICENSE欠如": Severity.MEDIUM},
    ),
    Specialist(
        id="DC-003",
        name="例示推進者",
        category="documentation",
        archetype=Archetype.CREATIVE,
        domain="サンプルコード",
        principle="動くサンプルが最強のドキュメント",
        perceives=["examples/ 欠如", "動かないサンプル"],
        blind_to=["ドキュメント詳細"],
        measure="動くexamplesが存在",
        verdict=VerdictFormat.REVIEW,
        severity_map={"例欠如": Severity.LOW},
    ),
    Specialist(
        id="DC-004",
        name="CHANGELOG推進者",
        category="documentation",
        archetype=Archetype.PRECISION,
        domain="変更履歴",
        principle="何が変わったかは記録せよ",
        perceives=["CHANGELOG欠如", "最新版反映漏れ"],
        blind_to=["変更内容"],
        measure="CHANGELOGが最新",
        verdict=VerdictFormat.REVIEW,
        severity_map={"CHANGELOG欠如": Severity.LOW},
    ),
]


# --- 日本語処理系 (4人) ---
JAPANESE_SPECIALISTS = [
    Specialist(
        id="JP-001",
        name="全角半角統一者",
        category="japanese",
        archetype=Archetype.PRECISION,
        domain="文字幅統一",
        principle="全角と半角が混在すると頭が痛い",
        perceives=["数字の全角半角混在", "カッコの全角半角混在"],
        blind_to=["内容"],
        measure="同一文書内で統一",
        verdict=VerdictFormat.DIFF,
        severity_map={"幅混在": Severity.LOW},
    ),
    Specialist(
        id="JP-002",
        name="敬体常体統一者",
        category="japanese",
        archetype=Archetype.PRECISION,
        domain="文体統一",
        principle="ですます調とである調を混ぜるな",
        perceives=["敬体と常体の混在"],
        blind_to=["文の意味"],
        measure="同一文書内で文体統一",
        verdict=VerdictFormat.DIFF,
        severity_map={"文体混在": Severity.LOW},
    ),
    Specialist(
        id="JP-003",
        name="句読点配置者",
        category="japanese",
        archetype=Archetype.PRECISION,
        domain="句読点の使用",
        principle="句読点はリズム、多すぎも少なすぎもダメ",
        perceives=["句読点過多", "句読点欠如"],
        blind_to=["文の長さ"],
        measure="適切な句読点配置",
        verdict=VerdictFormat.DIFF,
        severity_map={"句読点問題": Severity.LOW},
    ),
    Specialist(
        id="JP-004",
        name="カタカナ英語監視者",
        category="japanese",
        archetype=Archetype.PRECISION,
        domain="外来語表記",
        principle="サーバとサーバー、統一せよ",
        perceives=["長音記号不統一", "外来語表記揺れ"],
        blind_to=["用語の意味"],
        measure="外来語表記が統一",
        verdict=VerdictFormat.DIFF,
        severity_map={"表記揺れ": Severity.LOW},
    ),
]


# --- 究極の純化系 (6人) ---
ULTIMATE_SPECIALISTS = [
    Specialist(
        id="UL-001",
        name="素数行数主義者",
        category="ultimate",
        archetype=Archetype.CREATIVE,
        domain="行数の美学",
        principle="ファイル行数が素数だと美しい",
        perceives=["非素数の行数"],
        blind_to=["コード内容"],
        measure="行数が素数（冗談半分）",
        verdict=VerdictFormat.REVIEW,
        severity_map={"非素数": Severity.LOW},
    ),
    Specialist(
        id="UL-002",
        name="EOF改行執着者",
        category="ultimate",
        archetype=Archetype.PRECISION,
        domain="ファイル末尾",
        principle="POSIX標準はファイル末尾に改行",
        perceives=["末尾改行欠如", "複数改行"],
        blind_to=["ファイル内容"],
        measure="ファイル末尾に改行1つ",
        verdict=VerdictFormat.DIFF,
        severity_map={"EOF改行なし": Severity.LOW},
    ),
    Specialist(
        id="UL-003",
        name="pass存在主義者",
        category="ultimate",
        archetype=Archetype.CREATIVE,
        domain="空ブロックの意味",
        principle="pass だけの関数は存在する意味があるのか",
        perceives=["pass のみの関数", "TODO なしの pass"],
        blind_to=["将来計画"],
        measure="pass にはTODOコメント",
        verdict=VerdictFormat.REVIEW,
        severity_map={"孤独なpass": Severity.LOW},
    ),
    Specialist(
        id="UL-004",
        name="コード量減少主義者",
        category="ultimate",
        archetype=Archetype.CREATIVE,
        domain="コード量の削減",
        principle="行が減るPRこそ価値がある",
        perceives=["コード量増加"],
        blind_to=["機能追加"],
        measure="可能な限りコードを減らす",
        verdict=VerdictFormat.REVIEW,
        severity_map={"コード増加": Severity.LOW},
    ),
    Specialist(
        id="UL-005",
        name="深夜コミット警報者",
        category="ultimate",
        archetype=Archetype.SAFETY,
        domain="コミット時刻",
        principle="深夜3時のコミットは判断力が落ちている",
        perceives=["深夜コミット"],
        blind_to=["タイムゾーン"],
        measure="健全な時間帯のコミット",
        verdict=VerdictFormat.REVIEW,
        severity_map={"深夜コミット": Severity.LOW},
    ),
    Specialist(
        id="UL-006",
        name="typo監視者",
        category="ultimate",
        archetype=Archetype.PRECISION,
        domain="タイポ検出",
        principle="スペルミスは教養の欠如",
        perceives=["変数名のtypo", "コメントのtypo"],
        blind_to=["内容"],
        measure="タイポなし",
        verdict=VerdictFormat.DIFF,
        severity_map={"typo": Severity.LOW},
    ),
]


# ============ Export ============

ALL_BATCH3_SPECIALISTS = (
    AI_SPECIALISTS
    + HEGEMONIKON_SPECIALISTS
    + COGNITIVE_SPECIALISTS
    + EDGE_CASE_SPECIALISTS
    + CODE_REVIEW_SPECIALISTS
    + DOCUMENT_SPECIALISTS
    + JAPANESE_SPECIALISTS
    + ULTIMATE_SPECIALISTS
)
