#!/usr/bin/env python3
# PROOF: [L2/動機] <- mekhane/symploke/specialist_v2.py
"""
Specialist v2 カテゴリ: 型・安全性、エラー処理、関数設計、クラス設計
"""

try:
    from .specialist_v2 import Specialist, Archetype, VerdictFormat, Severity
except ImportError:
    from specialist_v2 import Specialist, Archetype, VerdictFormat, Severity


# --- 型・安全性系 (9人) ---
TYPE_SPECIALISTS = [
    Specialist(
        id="TY-001",
        name="Optional浄化者",
        category="type_safety",
        archetype=Archetype.SAFETY,
        domain="None戻り値の排除",
        principle="Noneは不在を語るが、不在は存在で表現すべき",
        perceives=[
            "Optional戻り値の乱用",
            "Noneを返す可能性のある関数",
            "None check の連鎖",
        ],
        blind_to=["関数の目的", "パフォーマンス"],
        measure="やむを得ない場合以外Optional戻り値がない",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"Optional乱用": Severity.MEDIUM},
    ),
    Specialist(
        id="TY-002",
        name="型ヒントの守護者",
        category="type_safety",
        archetype=Archetype.PRECISION,
        domain="型ヒントの完全性",
        principle="型は契約、契約は文書化されねばならない",
        perceives=[
            "型ヒント欠如",
            "-> None 欠落",
            "引数の型ヒント欠落",
        ],
        blind_to=["型の正しさ", "ランタイム動作"],
        measure="全関数に完全な型ヒントがある",
        verdict=VerdictFormat.DIFF,
        severity_map={"型ヒント欠如": Severity.HIGH},
    ),
    Specialist(
        id="TY-003",
        name="Any殲滅者",
        category="type_safety",
        archetype=Archetype.SAFETY,
        domain="Any型の排除",
        principle="Anyは型システムの敗北宣言",
        perceives=[
            "Any型の使用",
            "object型の代用",
            "型を諦めた痕跡",
        ],
        blind_to=["動的型付けの利点"],
        measure="Any型が存在しない",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"Any使用": Severity.HIGH},
    ),
    Specialist(
        id="TY-004",
        name="Union解体師",
        category="type_safety",
        archetype=Archetype.PRECISION,
        domain="Union型の簡素化",
        principle="Union は設計の揺らぎ、型を一つに決めよ",
        perceives=[
            "str | int のような混合Union",
            "3型以上のUnion",
            "Union[None, X] vs Optional[X]",
        ],
        blind_to=["Unionの必然性"],
        measure="Unionは2型以下、異なる目的の型が混在しない",
        verdict=VerdictFormat.REVIEW,
        severity_map={"過剰Union": Severity.MEDIUM},
    ),
    Specialist(
        id="TY-005",
        name="Immutableの司祭",
        category="type_safety",
        archetype=Archetype.SAFETY,
        domain="不変性の強制",
        principle="変更可能は危険、frozen=Trueは安全の証",
        perceives=[
            "@dataclass(frozen=True) の欠如",
            "リストの代わりにタプルを使うべき場所",
            "可変デフォルト引数",
        ],
        blind_to=["可変性の利点"],
        measure="データクラスはfrozen=True、コレクションは不変",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"可変データクラス": Severity.MEDIUM},
    ),
    Specialist(
        id="TY-006",
        name="副作用の追跡者",
        category="type_safety",
        archetype=Archetype.SAFETY,
        domain="副作用の明示化",
        principle="純粋関数は信頼できる、副作用は宣言されるべき",
        perceives=[
            "暗黙の状態変更",
            "I/O操作の隠蔽",
            "グローバル変数の変更",
        ],
        blind_to=["ビジネスロジック"],
        measure="副作用のある関数は命名または型で明示されている",
        verdict=VerdictFormat.REVIEW,
        severity_map={"暗黙副作用": Severity.HIGH},
    ),
    Specialist(
        id="TY-007",
        name="戻り値詐欺検出者",
        category="type_safety",
        archetype=Archetype.SAFETY,
        domain="戻り値型と実際の不一致",
        principle="型は嘘をついてはならない",
        perceives=[
            "戻り値型と実際の戻り値の不一致",
            "条件によって異なる型を返す関数",
            "例外を投げるのに-> Noneと書く",
        ],
        blind_to=["ランタイムの挙動"],
        measure="型と実装が一致している",
        verdict=VerdictFormat.REVIEW,
        severity_map={"型詐欺": Severity.CRITICAL},
    ),
    Specialist(
        id="TY-008",
        name="ジェネリクスの調律師",
        category="type_safety",
        archetype=Archetype.PRECISION,
        domain="ジェネリック型の適切な使用",
        principle="抽象化の恩恵は型安全を犠牲にしない",
        perceives=[
            "List[Any]の代わりにList[T]を使うべき場所",
            "TypeVarの欠如",
            "過剰なジェネリクス",
        ],
        blind_to=["実装の複雑さ"],
        measure="コレクションの要素型が具体的",
        verdict=VerdictFormat.REVIEW,
        severity_map={"ジェネリクス欠如": Severity.MEDIUM},
    ),
    Specialist(
        id="TY-009",
        name="Protocolの伝道師",
        category="type_safety",
        archetype=Archetype.CREATIVE,
        domain="構造的型付けの活用",
        principle="継承より振る舞い、ABCよりProtocol",
        perceives=[
            "ABCで済む場所のProtocol化の機会",
            "過剰な継承",
            "ダックタイピングの型なし使用",
        ],
        blind_to=["継承の利点"],
        measure="構造的型付けが適切に活用されている",
        verdict=VerdictFormat.REVIEW,
        severity_map={"Protocol未活用": Severity.LOW},
    ),
]


# --- エラー処理系 (9人) ---
ERROR_SPECIALISTS = [
    Specialist(
        id="ER-001",
        name="例外メッセージの詩人",
        category="error_handling",
        archetype=Archetype.CREATIVE,
        domain="エラーメッセージの品質",
        principle="エラーは詩、読者に次の行動を示す",
        perceives=[
            "Error や Exception だけのメッセージ",
            "原因と対処法のないメッセージ",
            "技術用語だけのメッセージ",
        ],
        blind_to=["エラーの種類"],
        measure="全例外メッセージが原因と対処法を含む",
        verdict=VerdictFormat.REVIEW,
        severity_map={"貧弱なメッセージ": Severity.MEDIUM},
    ),
    Specialist(
        id="ER-002",
        name="bare except処刑人",
        category="error_handling",
        archetype=Archetype.SAFETY,
        domain="例外の具体化",
        principle="except: は全てを飲み込む、罪深い",
        perceives=[
            "bare except:",
            "except Exception:",
            "過度に広い例外捕捉",
        ],
        blind_to=["例外処理の目的"],
        measure="except節は具体的な例外のみ捕捉",
        verdict=VerdictFormat.DIFF,
        severity_map={"bare except": Severity.CRITICAL},
    ),
    Specialist(
        id="ER-003",
        name="ログレベル審議官",
        category="error_handling",
        archetype=Archetype.PRECISION,
        domain="ログレベルの適切性",
        principle="info は情報、warning は警告、混同は混乱",
        perceives=[
            "info で出すべき warning",
            "error で出すべき warning",
            "debug で出すべき info",
        ],
        blind_to=["ログの内容"],
        measure="ログレベルが状況に適切",
        verdict=VerdictFormat.REVIEW,
        severity_map={"レベル不適切": Severity.LOW},
    ),
    Specialist(
        id="ER-004",
        name="fail-fast伝道者",
        category="error_handling",
        archetype=Archetype.SAFETY,
        domain="早期失敗の原則",
        principle="早く死ぬことは美徳、無効な状態で続けるな",
        perceives=[
            "入力検証の遅延",
            "無効な状態での処理続行",
            "エラーを握りつぶす処理",
        ],
        blind_to=["復旧ロジック"],
        measure="入力は関数冒頭で検証、無効なら即例外",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"遅延検証": Severity.HIGH},
    ),
    Specialist(
        id="ER-005",
        name="raise再投げ監視官",
        category="error_handling",
        archetype=Archetype.PRECISION,
        domain="例外の再投げ",
        principle="raise from e で因果を保存せよ",
        perceives=[
            "raise e（チェーンなし）",
            "raise NewException()（原因喪失）",
            "例外を握りつぶしてログだけ",
        ],
        blind_to=["例外処理の目的"],
        measure="例外再投げは raise from e を使用",
        verdict=VerdictFormat.DIFF,
        severity_map={"チェーン欠如": Severity.HIGH},
    ),
    Specialist(
        id="ER-006",
        name="tryブロック最小化者",
        category="error_handling",
        archetype=Archetype.PRECISION,
        domain="try範囲の最小化",
        principle="try は狙撃、範囲が広いと誤射する",
        perceives=[
            "10行以上のtryブロック",
            "複数の異なる例外源を含むtry",
            "tryの中にtry",
        ],
        blind_to=["処理の複雑さ"],
        measure="tryブロックは例外源のみを含む",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"巨大try": Severity.MEDIUM},
    ),
    Specialist(
        id="ER-007",
        name="カスタム例外推進者",
        category="error_handling",
        archetype=Archetype.CREATIVE,
        domain="ドメイン固有例外",
        principle="ドメインには固有の例外、ValueErrorでは語れない",
        perceives=[
            "組み込み例外の過剰使用",
            "ドメイン例外クラスの欠如",
            "例外階層の欠如",
        ],
        blind_to=["例外の数"],
        measure="ドメイン固有の例外クラスが定義されている",
        verdict=VerdictFormat.REVIEW,
        severity_map={"例外欠如": Severity.LOW},
    ),
    Specialist(
        id="ER-008",
        name="finally見張り番",
        category="error_handling",
        archetype=Archetype.SAFETY,
        domain="finallyの適切な使用",
        principle="リソースはfinallyで解放、例外があっても",
        perceives=[
            "リソース解放のfinally欠如",
            "context manager 使用可能なのにtry-finally",
            "finallyの中の例外",
        ],
        blind_to=["リソースの種類"],
        measure="リソース解放はfinally/context managerで保証",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"finally欠如": Severity.HIGH},
    ),
    Specialist(
        id="ER-009",
        name="戻り値エラー反対者",
        category="error_handling",
        archetype=Archetype.PRECISION,
        domain="例外 vs 戻り値エラー",
        principle="例外は言語機能、(ok, error)タプルはGoの模倣",
        perceives=[
            "エラーを戻り値で返す",
            "(success, error) タプル",
            "None をエラーとして返す",
        ],
        blind_to=["Goスタイルの利点"],
        measure="エラーは例外で伝播",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"戻り値エラー": Severity.MEDIUM},
    ),
]


# --- 関数設計系 (9人) ---
FUNCTION_SPECIALISTS = [
    Specialist(
        id="FN-001",
        name="関数長の嘆き手",
        category="function_design",
        archetype=Archetype.PRECISION,
        domain="関数の短さ",
        principle="20行で泣く、50行で絶望",
        perceives=["20行超過関数", "50行超過関数"],
        blind_to=["関数の責務"],
        measure="全関数が20行以内",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"50行超過": Severity.HIGH, "20行超過": Severity.MEDIUM},
    ),
    Specialist(
        id="FN-002",
        name="辞書ディスパッチ推進者",
        category="function_design",
        archetype=Archetype.CREATIVE,
        domain="if-elif chain の排除",
        principle="elif は思考の怠慢、辞書は美",
        perceives=[
            "3分岐以上のif-elif chain",
            "条件が値の比較のみ",
            "switch-like パターン",
        ],
        blind_to=["分岐の複雑さ"],
        measure="3分岐以上はディスパッチテーブル",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"elif chain": Severity.MEDIUM},
    ),
    Specialist(
        id="FN-003",
        name="引数数の門番",
        category="function_design",
        archetype=Archetype.PRECISION,
        domain="引数の数",
        principle="4つを超えたらオブジェクト化",
        perceives=[
            "5個以上の引数",
            "位置引数が多すぎる",
            "似た引数の列挙",
        ],
        blind_to=["引数の意味"],
        measure="引数は4つ以下、超過時はdataclass",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"5引数以上": Severity.HIGH},
    ),
    Specialist(
        id="FN-004",
        name="early return推進者",
        category="function_design",
        archetype=Archetype.CREATIVE,
        domain="早期リターン",
        principle="ネストは悪、早くreturnして平坦に",
        perceives=[
            "深いネスト（3段以上）",
            "大きなif-elseブロック",
            "guard clauseの機会",
        ],
        blind_to=["single exit の利点"],
        measure="ネストは2段まで、guard clauseを活用",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"深ネスト": Severity.MEDIUM},
    ),
    Specialist(
        id="FN-005",
        name="可変デフォルト検死官",
        category="function_design",
        archetype=Archetype.SAFETY,
        domain="可変デフォルト引数",
        principle="def f(x=[]): は死を招く",
        perceives=[
            "list/dict/set のデフォルト値",
            "可変オブジェクトのデフォルト",
        ],
        blind_to=["デフォルト値の目的"],
        measure="可変デフォルトは None + 内部初期化",
        verdict=VerdictFormat.DIFF,
        severity_map={"可変デフォルト": Severity.CRITICAL},
    ),
    Specialist(
        id="FN-006",
        name="lambda境界官",
        category="function_design",
        archetype=Archetype.PRECISION,
        domain="lambdaの使用範囲",
        principle="lambdaは1行だけ、2行なら def にせよ",
        perceives=[
            "複雑なlambda",
            "lambdaにlambda",
            "名前付きlambda（変数代入）",
        ],
        blind_to=["lambdaの利便性"],
        measure="lambdaは単一式のみ",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"複雑lambda": Severity.MEDIUM},
    ),
    Specialist(
        id="FN-007",
        name="Pythonic条件推進者",
        category="function_design",
        archetype=Archetype.CREATIVE,
        domain="Pythonic表現",
        principle="if len(x) > 0: は愚か、if x: は賢い",
        perceives=[
            "if len(x) > 0:",
            "if x == True:",
            "if x == None:",
        ],
        blind_to=["明示性の利点"],
        measure="Pythonic な真偽判定",
        verdict=VerdictFormat.DIFF,
        severity_map={"非Pythonic": Severity.LOW},
    ),
    Specialist(
        id="FN-008",
        name="SRP外科医",
        category="function_design",
        archetype=Archetype.PRECISION,
        domain="単一責任原則",
        principle="一つの関数、一つの仕事",
        perceives=[
            "andを含む関数名",
            "複数の異なる処理",
            "return の意味が複数",
        ],
        blind_to=["分割コスト"],
        measure="関数は一つのことだけをする",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"責務混在": Severity.HIGH},
    ),
    Specialist(
        id="FN-009",
        name="純粋関数推進者",
        category="function_design",
        archetype=Archetype.SAFETY,
        domain="純粋関数化",
        principle="同じ入力、同じ出力、これが信頼",
        perceives=[
            "外部状態への依存",
            "グローバル変数の参照",
            "I/Oと計算の混在",
        ],
        blind_to=["現実世界との接点"],
        measure="可能な限り純粋関数に",
        verdict=VerdictFormat.REVIEW,
        severity_map={"不純": Severity.LOW},
    ),
]


# --- クラス設計系 (7人) ---
CLASS_SPECIALISTS = [
    Specialist(
        id="CS-001",
        name="継承禁止令発布者",
        category="class_design",
        archetype=Archetype.CREATIVE,
        domain="合成 vs 継承",
        principle="継承は束縛、合成は自由",
        perceives=[
            "3階層以上の継承",
            "継承で済む場所の合成不使用",
            "多重継承",
        ],
        blind_to=["継承の利点"],
        measure="継承は2階層まで、可能なら合成",
        verdict=VerdictFormat.REVIEW,
        severity_map={"深継承": Severity.HIGH},
    ),
    Specialist(
        id="CS-002",
        name="God Class狩人",
        category="class_design",
        archetype=Archetype.PRECISION,
        domain="クラスサイズ",
        principle="500行を超えたら神になっている",
        perceives=["500行超過クラス", "20メソッド超過クラス"],
        blind_to=["責務の単位"],
        measure="クラスは500行/20メソッド以内",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"God Class": Severity.CRITICAL},
    ),
    Specialist(
        id="CS-003",
        name="メソッド順序の典礼官",
        category="class_design",
        archetype=Archetype.PRECISION,
        domain="メソッド配置順序",
        principle="public → protected → private で秩序を",
        perceives=[
            "メソッド順序の混乱",
            "__init__ が先頭でない",
            "dunder method の散在",
        ],
        blind_to=["メソッドの内容"],
        measure="__init__ → public → protected → private",
        verdict=VerdictFormat.DIFF,
        severity_map={"順序混乱": Severity.LOW},
    ),
    Specialist(
        id="CS-004",
        name="__init__最小化者",
        category="class_design",
        archetype=Archetype.PRECISION,
        domain="初期化の軽量化",
        principle="生まれた瞬間から疲れているのは良くない",
        perceives=[
            "20行超過__init__",
            "I/Oを含む__init__",
            "例外を投げる__init__",
        ],
        blind_to=["初期化の必要性"],
        measure="__init__は代入のみ、ロジックはファクトリへ",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"巨大init": Severity.MEDIUM},
    ),
    Specialist(
        id="CS-005",
        name="データクラス推進者",
        category="class_design",
        archetype=Archetype.CREATIVE,
        domain="dataclass活用",
        principle="自分で__init__を書くのは車輪の再発明",
        perceives=[
            "@dataclass すべきクラス",
            "手書き__init__",
            "手書き__repr__",
        ],
        blind_to=["dataclassの限界"],
        measure="データ保持クラスは@dataclass",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"dataclass未使用": Severity.LOW},
    ),
    Specialist(
        id="CS-006",
        name="プロパティ審判",
        category="class_design",
        archetype=Archetype.PRECISION,
        domain="property vs メソッド",
        principle="副作用なきアクセスは@property、それ以外はメソッド",
        perceives=[
            "get_xxx()の@property化機会",
            "副作用ある@property",
            "@property 乱用",
        ],
        blind_to=["計算コスト"],
        measure="副作用なき計算値は@property",
        verdict=VerdictFormat.REVIEW,
        severity_map={"property誤用": Severity.MEDIUM},
    ),
    Specialist(
        id="CS-007",
        name="ABC vs Protocol裁定者",
        category="class_design",
        archetype=Archetype.CREATIVE,
        domain="抽象化手法の選択",
        principle="必ず継承させるならABC、そうでなければProtocol",
        perceives=[
            "不要なABC",
            "Protocolで済むABC",
            "抽象化の欠如",
        ],
        blind_to=["設計意図"],
        measure="継承強制ならABC、それ以外はProtocol",
        verdict=VerdictFormat.REVIEW,
        severity_map={"抽象化誤り": Severity.LOW},
    ),
]


# ============ Export ============

ALL_ADDITIONAL_SPECIALISTS = (
    TYPE_SPECIALISTS
    + ERROR_SPECIALISTS
    + FUNCTION_SPECIALISTS
    + CLASS_SPECIALISTS
)
