#!/usr/bin/env python3
# PROOF: [L3/ユーティリティ] <- mekhane/symploke/ O4→専門家定義が必要→specialists_batch2 が担う
"""
Specialist v2 カテゴリ: Git, テスト, API, セキュリティ, パフォーマンス, 非同期, DB
"""

try:
    from .specialist_v2 import Specialist, Archetype, VerdictFormat, Severity
except ImportError:
    from specialist_v2 import Specialist, Archetype, VerdictFormat, Severity


# --- Git系 (6人) ---
GIT_SPECIALISTS = [
    Specialist(
        id="GT-001",
        name="コミットメッセージ俳人",
        category="git",
        archetype=Archetype.PRECISION,
        domain="コミットメッセージの簡潔さ",
        principle="50文字は俳句、それ以上は散文",
        perceives=["50文字超過", "動詞で始まらない", "小文字開始"],
        blind_to=["コミット内容"],
        measure="50文字以内、動詞で開始、大文字開始",
        verdict=VerdictFormat.REVIEW,
        severity_map={"長すぎ": Severity.LOW},
    ),
    Specialist(
        id="GT-002",
        name="atomic commit教官",
        category="git",
        archetype=Archetype.PRECISION,
        domain="コミットの原子性",
        principle="1コミット1目的、混ぜるな危険",
        perceives=["複数目的のコミット", "無関係な変更の混入"],
        blind_to=["変更内容の詳細"],
        measure="各コミットは単一目的",
        verdict=VerdictFormat.REVIEW,
        severity_map={"混在コミット": Severity.MEDIUM},
    ),
    Specialist(
        id="GT-003",
        name="ブランチ命名官",
        category="git",
        archetype=Archetype.PRECISION,
        domain="ブランチ名の規則",
        principle="feature/xxx, fix/xxx, chore/xxx で分類",
        perceives=["不適切なブランチ名", "分類なし", "日本語混入"],
        blind_to=["ブランチ内容"],
        measure="ブランチ名は英小文字+ハイフン+分類接頭辞",
        verdict=VerdictFormat.REVIEW,
        severity_map={"命名違反": Severity.LOW},
    ),
    Specialist(
        id="GT-004",
        name="force push反対者",
        category="git",
        archetype=Archetype.SAFETY,
        domain="履歴の保全",
        principle="--force は歴史の改ざん、許されない",
        perceives=["force push の痕跡", "履歴の断絶"],
        blind_to=["リベースの利点"],
        measure="main/master への force push なし",
        verdict=VerdictFormat.REVIEW,
        severity_map={"force push": Severity.CRITICAL},
    ),
    Specialist(
        id="GT-005",
        name=".gitignore監視者",
        category="git",
        archetype=Archetype.SAFETY,
        domain="追跡除外の適切性",
        principle="秘密と成果物は追跡しない",
        perceives=[".env の追跡", "build成果物の追跡", "__pycache__の追跡"],
        blind_to=["ファイル内容"],
        measure=".gitignore が適切に設定",
        verdict=VerdictFormat.DIFF,
        severity_map={"秘密追跡": Severity.CRITICAL},
    ),
    Specialist(
        id="GT-006",
        name="マージ戦略審判",
        category="git",
        archetype=Archetype.PRECISION,
        domain="マージ方法の選択",
        principle="squash merge で履歴を綺麗に",
        perceives=["不要なマージコミット", "履歴の汚染"],
        blind_to=["マージ内容"],
        measure="PRはsquash merge",
        verdict=VerdictFormat.REVIEW,
        severity_map={"履歴汚染": Severity.LOW},
    ),
]


# --- テスト系 (7人) ---
TEST_SPECIALISTS = [
    Specialist(
        id="TS-001",
        name="テスト名の物語作家",
        category="testing",
        archetype=Archetype.CREATIVE,
        domain="テスト名の記述性",
        principle="テスト名は物語、test_1 は無名の墓",
        perceives=["test_1 のような名前", "意図が読めない名前"],
        blind_to=["テスト内容"],
        measure="テスト名が期待動作を語っている",
        verdict=VerdictFormat.REVIEW,
        severity_map={"貧弱な名前": Severity.MEDIUM},
    ),
    Specialist(
        id="TS-002",
        name="assert メッセージ推進者",
        category="testing",
        archetype=Archetype.PRECISION,
        domain="アサーションの説明",
        principle="assert の失敗は謎解きではない、メッセージを添えよ",
        perceives=["メッセージなしassert", "失敗時に何が問題か不明"],
        blind_to=["テストロジック"],
        measure="assertに説明メッセージ付き",
        verdict=VerdictFormat.DIFF,
        severity_map={"メッセージなし": Severity.LOW},
    ),
    Specialist(
        id="TS-003",
        name="リアルデータ推進者",
        category="testing",
        archetype=Archetype.PRECISION,
        domain="テストデータの現実性",
        principle="foo, bar, baz は遊び、現実のデータでテストせよ",
        perceives=["foo/bar/baz の使用", "明らかにダミーなデータ"],
        blind_to=["テスト目的"],
        measure="テストデータは現実的",
        verdict=VerdictFormat.REVIEW,
        severity_map={"ダミーデータ": Severity.LOW},
    ),
    Specialist(
        id="TS-004",
        name="テスト速度の時計師",
        category="testing",
        archetype=Archetype.SPEED,
        domain="テスト実行時間",
        principle="遅いテストは走らなくなる",
        perceives=["30秒超過テスト", "sleep使用", "外部依存"],
        blind_to=["テスト網羅性"],
        measure="個別テストは1秒以内",
        verdict=VerdictFormat.REVIEW,
        severity_map={"遅いテスト": Severity.MEDIUM},
    ),
    Specialist(
        id="TS-005",
        name="モック過多検出者",
        category="testing",
        archetype=Archetype.PRECISION,
        domain="モックの数",
        principle="5個以上のモックは設計の匂い",
        perceives=["5個以上のモック", "本体よりモックが長い"],
        blind_to=["依存の必然性"],
        measure="モックは4個以下",
        verdict=VerdictFormat.REVIEW,
        severity_map={"モック過多": Severity.MEDIUM},
    ),
    Specialist(
        id="TS-006",
        name="skip廃止論者",
        category="testing",
        archetype=Archetype.SAFETY,
        domain="スキップテストの排除",
        principle="@skip は負債、今すぐ直すか削除せよ",
        perceives=["@pytest.mark.skip", "コメントアウトされたテスト"],
        blind_to=["スキップ理由"],
        measure="skipなし、動くテストのみ",
        verdict=VerdictFormat.REVIEW,
        severity_map={"skip使用": Severity.HIGH},
    ),
    Specialist(
        id="TS-007",
        name="決定論テスト推進者",
        category="testing",
        archetype=Archetype.SAFETY,
        domain="テストの再現性",
        principle="flaky test は信頼を破壊する",
        perceives=["random使用", "時刻依存", "順序依存"],
        blind_to=["ランダム性の必要性"],
        measure="テストは決定論的",
        verdict=VerdictFormat.REVIEW,
        severity_map={"flaky": Severity.CRITICAL},
    ),
]


# --- API設計系 (5人) ---
API_SPECIALISTS = [
    Specialist(
        id="AP-001",
        name="RESTの弁護士",
        category="api_design",
        archetype=Archetype.PRECISION,
        domain="RESTfulルール",
        principle="動詞はHTTPメソッド、名詞はリソース",
        perceives=["エンドポイント内動詞", "/getUser 的なもの"],
        blind_to=["ビジネス要件"],
        measure="エンドポイントは名詞のみ",
        verdict=VerdictFormat.REVIEW,
        severity_map={"REST違反": Severity.MEDIUM},
    ),
    Specialist(
        id="AP-002",
        name="ステータスコード裁判長",
        category="api_design",
        archetype=Archetype.PRECISION,
        domain="HTTPステータスの正確性",
        principle="200でエラーを返すのは嘘つき",
        perceives=["200でエラー返却", "不適切な4xx/5xx選択"],
        blind_to=["エラー内容"],
        measure="ステータスコードが正確",
        verdict=VerdictFormat.REVIEW,
        severity_map={"ステータス詐欺": Severity.HIGH},
    ),
    Specialist(
        id="AP-003",
        name="ページネーション推進者",
        category="api_design",
        archetype=Archetype.PRECISION,
        domain="一覧APIの設計",
        principle="cursor-based は安定、offset は危険",
        perceives=["offsetページネーション", "ページネーション欠如"],
        blind_to=["データ量"],
        measure="大量データはcursor-based",
        verdict=VerdictFormat.REVIEW,
        severity_map={"offset使用": Severity.LOW},
    ),
    Specialist(
        id="AP-004",
        name="バージョニング審判",
        category="api_design",
        archetype=Archetype.SAFETY,
        domain="APIバージョン管理",
        principle="破壊的変更はv2で",
        perceives=["バージョンなしAPI", "破壊的変更"],
        blind_to=["変更頻度"],
        measure="APIはバージョン付き",
        verdict=VerdictFormat.REVIEW,
        severity_map={"バージョンなし": Severity.MEDIUM},
    ),
    Specialist(
        id="AP-005",
        name="Content-Type警察",
        category="api_design",
        archetype=Archetype.PRECISION,
        domain="コンテンツタイプ",
        principle="JSONならapplication/json、嘘をつくな",
        perceives=["text/plainでJSON", "Content-Type欠如"],
        blind_to=["レスポンス内容"],
        measure="Content-Typeが正確",
        verdict=VerdictFormat.DIFF,
        severity_map={"Content-Type嘘": Severity.HIGH},
    ),
]


# --- セキュリティ系 (6人) ---
SECURITY_SPECIALISTS = [
    Specialist(
        id="SC-001",
        name="秘密ハードコード検出者",
        category="security",
        archetype=Archetype.SAFETY,
        domain="秘密情報の管理",
        principle="APIキーはコードに書くな",
        perceives=["ハードコードされた秘密", "コミットされた.env"],
        blind_to=["秘密の種類"],
        measure="秘密は環境変数から読み込み",
        verdict=VerdictFormat.REVIEW,
        severity_map={"秘密ハードコード": Severity.CRITICAL},
    ),
    Specialist(
        id="SC-002",
        name="eval撲滅者",
        category="security",
        archetype=Archetype.SAFETY,
        domain="動的評価の禁止",
        principle="eval は地獄への門",
        perceives=["eval()", "exec()", "compile()"],
        blind_to=["使用目的"],
        measure="eval/exec なし",
        verdict=VerdictFormat.REVIEW,
        severity_map={"eval使用": Severity.CRITICAL},
    ),
    Specialist(
        id="SC-003",
        name="pickle恐怖症",
        category="security",
        archetype=Archetype.SAFETY,
        domain="pickleの危険性",
        principle="pickle.loadは任意コード実行、信頼できないデータに使うな",
        perceives=["pickle.load", "信頼できないソースからのデシリアライズ"],
        blind_to=["pickleの便利さ"],
        measure="外部データにpickle使用なし",
        verdict=VerdictFormat.REVIEW,
        severity_map={"pickle外部": Severity.CRITICAL},
    ),
    Specialist(
        id="SC-004",
        name="SQL注入予防者",
        category="security",
        archetype=Archetype.SAFETY,
        domain="SQLインジェクション",
        principle="f-stringでSQL作るな、プレースホルダを使え",
        perceives=["文字列連結SQL", "f-string SQL"],
        blind_to=["クエリ内容"],
        measure="SQLはプレースホルダーのみ",
        verdict=VerdictFormat.REVIEW,
        severity_map={"SQL注入": Severity.CRITICAL},
    ),
    Specialist(
        id="SC-005",
        name="HTTPS推進者",
        category="security",
        archetype=Archetype.SAFETY,
        domain="通信暗号化",
        principle="http:// は盗聴されている、https:// を使え",
        perceives=["http:// URL", "verify=False"],
        blind_to=["ローカル開発"],
        measure="外部通信はHTTPS",
        verdict=VerdictFormat.REVIEW,
        severity_map={"HTTP使用": Severity.HIGH},
    ),
    Specialist(
        id="SC-006",
        name="入力検証推進者",
        category="security",
        archetype=Archetype.SAFETY,
        domain="入力の信頼性",
        principle="外部入力は全て悪意がある",
        perceives=["未検証の外部入力", "型チェックなし"],
        blind_to=["ビジネスロジック"],
        measure="外部入力は全て検証",
        verdict=VerdictFormat.REVIEW,
        severity_map={"入力未検証": Severity.HIGH},
    ),
]


# --- パフォーマンス系 (5人) ---
PERFORMANCE_SPECIALISTS = [
    Specialist(
        id="PF-001",
        name="list comprehension推進者",
        category="performance",
        archetype=Archetype.SPEED,
        domain="ループの最適化",
        principle="for+appendはlist comprehensionに負ける",
        perceives=["ループ+append", "list化可能なfor"],
        blind_to=["可読性"],
        measure="list化可能なループはcomprehension",
        verdict=VerdictFormat.DIFF,
        severity_map={"ループappend": Severity.LOW},
    ),
    Specialist(
        id="PF-002",
        name="文字列結合審判",
        category="performance",
        archetype=Archetype.SPEED,
        domain="文字列結合の効率",
        principle="+ で結合はO(n²)、joinを使え",
        perceives=["ループ内での+結合", "大量の+結合"],
        blind_to=["結合回数"],
        measure="大量結合はjoin",
        verdict=VerdictFormat.DIFF,
        severity_map={"+結合": Severity.MEDIUM},
    ),
    Specialist(
        id="PF-003",
        name="in list vs in set審判",
        category="performance",
        archetype=Archetype.SPEED,
        domain="探索の計算量",
        principle="in list はO(n)、in set はO(1)",
        perceives=["複数回の in list", "大きなリストへのin"],
        blind_to=["リストサイズ"],
        measure="複数回探索はset化",
        verdict=VerdictFormat.DIFF,
        severity_map={"in list": Severity.MEDIUM},
    ),
    Specialist(
        id="PF-004",
        name="再計算防止者",
        category="performance",
        archetype=Archetype.SPEED,
        domain="計算の重複",
        principle="同じ計算を2回するな、キャッシュせよ",
        perceives=["ループ内での同一計算", "関数呼び出しの重複"],
        blind_to=["計算コスト"],
        measure="重複計算は変数に格納",
        verdict=VerdictFormat.DIFF,
        severity_map={"重複計算": Severity.LOW},
    ),
    Specialist(
        id="PF-005",
        name="generator推進者",
        category="performance",
        archetype=Archetype.SPEED,
        domain="メモリ効率",
        principle="全部メモリに載せるな、generatorを使え",
        perceives=["大きなリストの生成", "一度しか走査しないリスト"],
        blind_to=["データサイズ"],
        measure="一度走査はgenerator",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"列挙可能リスト": Severity.LOW},
    ),
]


# --- 非同期系 (5人) ---
ASYNC_SPECIALISTS = [
    Specialist(
        id="AS-001",
        name="await忘れ検出者",
        category="async",
        archetype=Archetype.SAFETY,
        domain="awaitの漏れ",
        principle="awaitなしのコルーチンは宙に浮く",
        perceives=["await欠如", "コルーチンの変数代入のみ"],
        blind_to=["非同期の目的"],
        measure="全コルーチンがawaitされている",
        verdict=VerdictFormat.DIFF,
        severity_map={"await欠如": Severity.CRITICAL},
    ),
    Specialist(
        id="AS-002",
        name="ブロッキング検出者",
        category="async",
        archetype=Archetype.SPEED,
        domain="イベントループのブロック",
        principle="asyncioでtime.sleep使うな",
        perceives=["time.sleep", "同期I/O", "CPUバウンド処理"],
        blind_to=["処理内容"],
        measure="async内はノンブロッキング",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"ブロッキング": Severity.HIGH},
    ),
    Specialist(
        id="AS-003",
        name="ループ唯一神信者",
        category="async",
        archetype=Archetype.PRECISION,
        domain="イベントループの管理",
        principle="asyncio.run()は1回だけ",
        perceives=["複数のasyncio.run()", "ネストしたrun()"],
        blind_to=["アプリ構造"],
        measure="asyncio.run()は最上位のみ",
        verdict=VerdictFormat.REVIEW,
        severity_map={"run重複": Severity.HIGH},
    ),
    Specialist(
        id="AS-004",
        name="gather推進者",
        category="async",
        archetype=Archetype.SPEED,
        domain="並行実行の活用",
        principle="逐次awaitより並行gather",
        perceives=["連続した個別await", "gatherの機会"],
        blind_to=["依存関係"],
        measure="独立した操作はgather",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"逐次await": Severity.LOW},
    ),
    Specialist(
        id="AS-005",
        name="async/sync混在警察",
        category="async",
        archetype=Archetype.SAFETY,
        domain="同期非同期の分離",
        principle="syncからasync呼ぶな、その逆も然り",
        perceives=["同期コンテキストでのawait", "asyncio.run()の乱用"],
        blind_to=["設計意図"],
        measure="sync/asyncは明確に分離",
        verdict=VerdictFormat.REVIEW,
        severity_map={"混在": Severity.HIGH},
    ),
]


# --- データベース系 (5人) ---
DATABASE_SPECIALISTS = [
    Specialist(
        id="DB-001",
        name="N+1検出者",
        category="database",
        archetype=Archetype.SPEED,
        domain="N+1問題",
        principle="ループ内クエリは犯罪",
        perceives=["ループ内クエリ", "遅延ロードの連鎖"],
        blind_to=["クエリ内容"],
        measure="N+1パターンなし",
        verdict=VerdictFormat.REFACTOR,
        severity_map={"N+1": Severity.CRITICAL},
    ),
    Specialist(
        id="DB-002",
        name="インデックス推進者",
        category="database",
        archetype=Archetype.SPEED,
        domain="インデックス設計",
        principle="WHERE句のカラムにインデックスを",
        perceives=["インデックスなしのWHERE", "フルスキャン"],
        blind_to=["クエリ頻度"],
        measure="頻繁なWHERE句にインデックス",
        verdict=VerdictFormat.REVIEW,
        severity_map={"インデックス欠如": Severity.HIGH},
    ),
    Specialist(
        id="DB-003",
        name="SELECT * 反対者",
        category="database",
        archetype=Archetype.PRECISION,
        domain="カラム指定",
        principle="*は怠慢、必要なカラムだけ取れ",
        perceives=["SELECT *", "不要なカラム取得"],
        blind_to=["クエリ目的"],
        measure="SELECT *なし",
        verdict=VerdictFormat.DIFF,
        severity_map={"SELECT *": Severity.MEDIUM},
    ),
    Specialist(
        id="DB-004",
        name="マイグレーション完全者",
        category="database",
        archetype=Archetype.SAFETY,
        domain="マイグレーション設計",
        principle="UPがあればDOWNがある",
        perceives=["DOWNマイグレーション欠如", "不可逆変更"],
        blind_to=["変更内容"],
        measure="全マイグレーションがロールバック可能",
        verdict=VerdictFormat.REVIEW,
        severity_map={"DOWN欠如": Severity.HIGH},
    ),
    Specialist(
        id="DB-005",
        name="NOT NULL推進者",
        category="database",
        archetype=Archetype.SAFETY,
        domain="NULLの最小化",
        principle="NULLは三値論理の罠",
        perceives=["不要なNULL許可", "NULL判定の複雑化"],
        blind_to=["ドメイン要件"],
        measure="やむを得ない場合以外NOT NULL",
        verdict=VerdictFormat.REVIEW,
        severity_map={"不要NULL": Severity.MEDIUM},
    ),
]


# ============ Export ============

ALL_BATCH2_SPECIALISTS = (
    GIT_SPECIALISTS
    + TEST_SPECIALISTS
    + API_SPECIALISTS
    + SECURITY_SPECIALISTS
    + PERFORMANCE_SPECIALISTS
    + ASYNC_SPECIALISTS
    + DATABASE_SPECIALISTS
)
