# プロンプトパターン本質的マッピング

> **CCL**: `/mek+ :redesign`  
> **目的**: 安直なラベル貼りではなく、定理体系での意味的対応

---

## 本質分析

### 1. Chain-of-Thought (CoT)

| 要素 | 本質 |
|:-----|:-----|
| **構造** | 問題 → 分解 → 段階的推論 → 答え |
| **核心** | **道筋 (Hodos)** を明示的に辿る |
| **定理対応** | P2 Hodos + O3 Zētēsis |

**CCL**: `/zet+ _F:{/hod _/dia-} _/gno`

> 「問いを深く分解し、各段階で道筋を辿り簡易判定、最後に原則抽出」

---

### 2. Tree-of-Thought (ToT)

| 要素 | 本質 |
|:-----|:-----|
| **構造** | 分岐 → 複数経路評価 → 最良選択 |
| **核心** | **軌道 (Trokhia)** の探索と評価 |
| **定理対応** | P3 Trokhia + A2 Krisis |

**CCL**: `/zet* _F:{/tro _/dia} _/sta`

> 「問いを展開し、各軌道を判定、基準で最良選択」

---

### 3. ReAct (Reasoning-Acting)

| 要素 | 本質 |
|:-----|:-----|
| **構造** | 観察 → 推論 → 行動 → (繰り返し) |
| **核心** | **探求-行為サイクル** |
| **定理対応** | O3 Zētēsis ~ O4 Energeia |

**CCL**: `~(/sop _/noe _/ene _/dia-)`

> 「調査→深い認識→行動→簡易判定を振動」

---

### 4. Reflection

| 要素 | 本質 |
|:-----|:-----|
| **構造** | 生成 → 自己批評 → 改善 |
| **核心** | **冷徹な鏡 (Cold Mirror)** |
| **定理対応** | A2 Krisis (cold_mirror mode) |

**CCL**: `/ene _/dia --mode=cold_mirror _/s+`

> 「実行→冷徹な批評→設計改善」
> **注**: これは `/dia` の既存派生で表現可能

---

### 5. Step-Back Prompting

| 要素 | 本質 |
|:-----|:-----|
| **構造** | 抽象化 → 一般原則 → 具体適用 |
| **核心** | **メタ→具体の降下** |
| **定理対応** | S-series ^ → S-series |

**CCL**: `/s^ _/gno _/s`

> 「メタ俯瞰→原則抽出→具体設計」

---

### 6. Cognitive Verifier

| 要素 | 本質 |
|:-----|:-----|
| **構造** | 分解 → 各部検証 → 統合 |
| **核心** | **分割統治の検証** |
| **定理対応** | O3 Zētēsis + A2 Krisis |

**CCL**: `/zet+ _F:{/dia+} _/epi`

> 「深い問い分解→各部詳細判定→知識確立」

---

## マクロ vs WF 派生

| パターン | 推奨形態 | 理由 |
|:---------|:---------|:-----|
| CoT | `/noe --mode=cot` | **WF 派生** — `/noe` の推論強化 |
| ToT | `/noe --mode=tot` | **WF 派生** — `/noe` の探索強化 |
| ReAct | `@react` | **マクロ** — 固定サイクル |
| Reflection | `/dia --mode=cold_mirror` | **既存派生** — 追加不要 |
| Step-Back | `/s --mode=stepback` | **WF 派生** — `/s` の抽象化強化 |
| Verifier | `/dia --mode=verify` | **WF 派生** — `/dia` の分解検証 |

---

## 結論: 実装すべきもの

### WF 派生 (4 件)

| Parent | Mode | Description |
|:-------|:-----|:------------|
| `/noe` | `--mode=cot` | 道筋明示の段階推論 |
| `/noe` | `--mode=tot` | 軌道探索と評価 |
| `/s` | `--mode=stepback` | メタ→具体の降下 |
| `/dia` | `--mode=verify` | 分割統治検証 |

### マクロ (1 件)

| Name | CCL | Description |
|:-----|:----|:------------|
| `@react` | `~(/sop_/noe_/ene_/dia-)` | 観察-推論-行動-判定サイクル |

---

*Generated by `/mek+ :redesign` 2026-01-29*
