# Jules API Integration Research Results

> Perplexity 調査 2026-01-27

## 🎯 結論サマリー

**Claude を親、Jules API を子（18並列ワーカー）** とする設計は **実装可能**。

| 項目 | 結論 |
|-----|-----|
| Jules API | 同時実行上限 50（Ultra）で 18並列は安全 ✅ |
| 呼び出し方 | **MCP HTTP** が最適（Claude Code 2025年11月対応）|
| 並列戦略 | Asyncio + ThreadPoolExecutor ポーリング式 |
| レート制限 | 18キー分散で月 300 タスク（Ultra）に対応 |
| 実装期間 | Phase 1-4 で 4-5週間 |

---

## 📋 Jules API 仕様

### エンドポイント

| Endpoint | Method | Purpose |
|----------|--------|---------|
| `https://jules.googleapis.com/v1alpha/sessions` | POST | セッション作成 |
| `https://jules.googleapis.com/v1alpha/sessions/{id}` | GET | 進捗確認（ポーリング） |
| `https://jules.googleapis.com/v1alpha/sources` | GET | リポジトリ一覧取得 |

### 認証

```http
X-Goog-Api-Key: YOUR_API_KEY
```

**制限**: 1ユーザー = 3キーまで

### 制限事項

| Tier | Daily Tasks | Concurrent | Cost |
|------|------------|-----------|------|
| Free | 15 | 3 | $0 |
| Pro | 100 | 15 | $19.99/month |
| **Ultra** | 300 | **50** | $124.99/month |

---

## 🔄 呼び出し方法比較

| 方式 | MCP HTTP | HTTP 直接 | GitHub Actions |
|-----|----------|----------|---|
| 遅延 | ~150-200ms | ~100ms | ~2-5秒 |
| 実装難度 | 中 | 低 | 高 |
| エラーハンドリング | ✅ 標準化 | ❌ 手動 | ✅ 堅牢 |
| **推奨度** | 🥇 **最適** | 🥈 迅速 | 🥉 堅牢 |

---

## 🏗️ 推奨アーキテクチャ

```
┌──────────────────────────────────────────────────────┐
│ Claude (Antigravity IDE)                             │
│ - Strategic Layer: タスク分割・優先順位              │
└────────────────┬─────────────────────────────────────┘
                 ↓
    ┌─────────────────────────────┐
    │ MCP Wrapper Service         │
    │ (FastAPI)                   │
    │ • 18 API キー ローテーション │
    │ • Polling Manager           │
    │ • Result Aggregator         │
    └────────┬────────────────────┘
             ↓
    ┌─────────────────────────────┐
    │ Jules API V1                │
    │ 18並列セッション実行        │
    └─────────────────────────────┘
```

---

## 🔗 根拠リンク

- [Jules API 公式](https://developers.google.com/jules/api)
- [Claude Code MCP](https://code.claude.com/docs/en/mcp)
- [Claude リモート MCP 対応 (2025-11)](https://www.infoq.com/jp/news/2025/11/anthropic-claude-remote-mcp/)

---

*Generated by Hegemonikón O3 Zētēsis 2026-01-27*
