# Task: A2 Krisis `lex` Derivative + Feedback Mechanism

> **Session**: 2026-01-30 11:34 JST
> **Objective**: CLL/mek+ 運用下で、プロンプトエンジニアリングの教養 Skill を追加し、AIチャット履歴からの改善フィードバック機構を実装する。

---

## Scope Definition

### 1. Skill 追加

- [/] プロンプトエンジニアリングの教養教育 Skill を新規作成
- [ ] 言葉遣い・推奨フレーズ・使い分けの解説機構
- [ ] 「◯◯を教えて」vs「◯◯を考えて」の作用機序解説フォーマット

### 2. Feedback 機構

- [ ] チャット履歴入力からの表現解析
- [ ] 改善すべき表現の抽出ロジック
- [ ] 技法提案の出力フォーマット設計

### 3. CLL/mek+ 統合

- [ ] CCL signature 定義
- [ ] 派生モード設計 (comp/inve/adap 対応)
- [ ] ワークフロー連携定義

---

## Key Deliverables

| 成果物 | 形式 | 保存先 |
|:-------|:-----|:-------|
| A2 派生追加 | SKILL.md | `.agent/skills/akribeia/a2-krisis/` |
| 作用機序解説フォーマット | MD | SKILL.md 内 |
| フィードバック機構仕様 | MD | SKILL.md 内 |
| 実装計画 | implementation_plan.md | brain/ |

---

## Progress

- [x] /boot Phase 1 完了（正本読込）
- [x] /boot Phase 2-4 Handoff/tools.yaml 確認
- [/] 実装計画策定中

---

*Generated by Hegemonikón /boot → PLANNING*
