# Jules Synedrion v2: Orthogonal Perspectives Matrix
# 
# 20 Domains × 6 Axes = 120 Structurally Orthogonal Perspectives
#
# Usage:
#   from mekhane.ergasterion.synedrion.perspectives import load_perspectives
#   perspectives = load_perspectives()
#   prompt = perspectives.get_prompt("Resource", "O")

version: "2.0"
lineage: "Synedrion v1 (866 experts) → v2 (120 orthogonal perspectives via Hegemonikón theorem grid)"

# ==============================================================================
# DOMAINS (What to look at)
# ==============================================================================
# 20 review domains derived from software engineering best practices
# Each domain is a distinct area of concern

domains:
  - id: "Resource"
    name: "リソースライフサイクル"
    description: "接続、ファイルハンドル、メモリ管理のライフサイクル"
    keywords: ["connection", "file handle", "memory", "lifecycle", "cleanup", "close"]
    
  - id: "Error"
    name: "エラーハンドリング"
    description: "例外処理、リトライ、フォールバック戦略"
    keywords: ["exception", "retry", "fallback", "error", "catch", "raise"]
    
  - id: "Concurrency"
    name: "並行処理"
    description: "競合状態、デッドロック、同期機構"
    keywords: ["async", "await", "lock", "semaphore", "race condition", "deadlock"]
    
  - id: "API"
    name: "API契約"
    description: "入出力の型、境界値、契約の遵守"
    keywords: ["input", "output", "type", "boundary", "contract", "validation"]
    
  - id: "Security"
    name: "セキュリティ"
    description: "認証、権限、インジェクション攻撃"
    keywords: ["auth", "permission", "injection", "sanitize", "token", "credential"]
    
  - id: "Observability"
    name: "可観測性"
    description: "ログ、メトリクス、トレース"
    keywords: ["log", "metric", "trace", "monitor", "alert", "dashboard"]
    
  - id: "Configuration"
    name: "設定管理"
    description: "環境変数、設定ファイル、デフォルト値"
    keywords: ["env", "config", "setting", "default", "override", "secret"]
    
  - id: "Dependency"
    name: "依存関係"
    description: "外部ライブラリ、バージョン互換性"
    keywords: ["import", "package", "version", "compatibility", "dependency"]
    
  - id: "CodeStyle"
    name: "コードスタイル"
    description: "命名規則、構造、可読性"
    keywords: ["naming", "structure", "readability", "convention", "format"]
    
  - id: "Documentation"
    name: "ドキュメント"
    description: "コメント、docstring、README"
    keywords: ["comment", "docstring", "readme", "documentation", "explain"]
    
  - id: "Testing"
    name: "テスト"
    description: "テストカバレッジ、エッジケース、モック"
    keywords: ["test", "coverage", "mock", "assert", "edge case", "fixture"]
    
  - id: "Performance"
    name: "パフォーマンス"
    description: "速度、メモリ使用量、最適化"
    keywords: ["speed", "memory", "optimize", "cache", "latency", "throughput"]
    
  - id: "Scalability"
    name: "スケーラビリティ"
    description: "水平/垂直スケーリング、負荷分散"
    keywords: ["scale", "horizontal", "vertical", "load", "distribute", "shard"]
    
  - id: "Maintainability"
    name: "保守性"
    description: "理解しやすさ、変更しやすさ"
    keywords: ["maintain", "understand", "change", "refactor", "modular"]
    
  - id: "Reliability"
    name: "信頼性"
    description: "障害耐性、冪等性、復旧"
    keywords: ["reliable", "fault", "idempotent", "recover", "resilient"]
    
  - id: "Usability"
    name: "使いやすさ"
    description: "API設計、エルゴノミクス、開発者体験"
    keywords: ["usable", "ergonomic", "developer experience", "intuitive", "api design"]
    
  - id: "Compatibility"
    name: "互換性"
    description: "後方互換、破壊的変更、移行"
    keywords: ["compatible", "backward", "breaking", "migration", "deprecate"]
    
  - id: "Architecture"
    name: "アーキテクチャ"
    description: "設計パターン、責務分離、モジュール構成"
    keywords: ["architecture", "pattern", "separation", "module", "layer"]
    
  - id: "DataFlow"
    name: "データフロー"
    description: "入力から出力への変換フロー"
    keywords: ["flow", "transform", "pipeline", "input", "output", "data"]
    
  - id: "EdgeCase"
    name: "エッジケース"
    description: "境界値、異常系、予期しない入力"
    keywords: ["edge", "boundary", "abnormal", "unexpected", "corner case"]

# ==============================================================================
# AXES (How to look at it)
# ==============================================================================
# All 24 Hegemonikón theorems as cognitive lenses
# Each theorem provides a unique perspective for code review
# Generated via /mek (tekhne-maker) Hegemonikón Mode

axes:
  # ---------------------------------------------------------------------------
  # O-series: Ousia (Pure Theorems) — 認識・理解・洞察
  # ---------------------------------------------------------------------------
  - id: "O1"
    series: "Ousia"
    theorem: "Noēsis"
    name: "深い認識"
    question: "What is the deep, non-discursive understanding?"
    focus: "このコードの本質的な目的は何か？直観的に何を理解すべきか？"
    
  - id: "O2"
    series: "Ousia"
    theorem: "Boulēsis"
    name: "意志・目的"
    question: "What is the rational intention?"
    focus: "このコードが達成しようとしている意図は明確か？"
    
  - id: "O3"
    series: "Ousia"
    theorem: "Zētēsis"
    name: "探求"
    question: "What questions remain unanswered?"
    focus: "未解決の問い・不確実性・調査が必要な領域は何か？"
    
  - id: "O4"
    series: "Ousia"
    theorem: "Energeia"
    name: "行為・活動"
    question: "Is the action aligned with intention?"
    focus: "実際の動作は意図と一致しているか？行動は完結しているか？"

  # ---------------------------------------------------------------------------
  # S-series: Schema (Strategy Theorems) — 計画・戦略・測定
  # ---------------------------------------------------------------------------
  - id: "S1"
    series: "Schema"
    theorem: "Metron"
    name: "尺度"
    question: "Is the scale appropriate?"
    focus: "このコードの粒度・スケールは適切か？過剰か不足か？"
    
  - id: "S2"
    series: "Schema"
    theorem: "Mekhanē"
    name: "方法"
    question: "Are the methods appropriate?"
    focus: "使用されている手法・技術は適切か？より良い方法はあるか？"
    
  - id: "S3"
    series: "Schema"
    theorem: "Stathmos"
    name: "基準"
    question: "Are success criteria defined?"
    focus: "成功・失敗の基準は明確か？評価可能か？"
    
  - id: "S4"
    series: "Schema"
    theorem: "Praxis"
    name: "実践"
    question: "Is theory applied correctly?"
    focus: "設計と実装は一致しているか？理論が実践に落とし込まれているか？"

  # ---------------------------------------------------------------------------
  # H-series: Hormē (Impulse Theorems) — 衝動・信念・直感
  # ---------------------------------------------------------------------------
  - id: "H1"
    series: "Hormē"
    theorem: "Propatheia"
    name: "前感情"
    question: "What is the gut feeling?"
    focus: "直感的に違和感はないか？無意識のパターン認識は何を示すか？"
    
  - id: "H2"
    series: "Hormē"
    theorem: "Pistis"
    name: "確信"
    question: "How confident should we be?"
    focus: "このコードの信頼性はどの程度か？どこに不確実性があるか？"
    
  - id: "H3"
    series: "Hormē"
    theorem: "Orexis"
    name: "欲求"
    question: "What is the underlying desire?"
    focus: "このコードが満たそうとしている欲求・ニーズは何か？"
    
  - id: "H4"
    series: "Hormē"
    theorem: "Doxa"
    name: "信念"
    question: "What assumptions are made?"
    focus: "暗黙の仮定・信念は何か？それは妥当か？"

  # ---------------------------------------------------------------------------
  # P-series: Perigraphē (Environment Theorems) — 環境・境界・経路
  # ---------------------------------------------------------------------------
  - id: "P1"
    series: "Perigraphē"
    theorem: "Khōra"
    name: "場"
    question: "What is the scope?"
    focus: "このコードのスコープ・境界は明確か？責務の切り分けは？"
    
  - id: "P2"
    series: "Perigraphē"
    theorem: "Hodos"
    name: "道"
    question: "Is the path correct?"
    focus: "実行パス・フローは適切か？分岐は妥当か？"
    
  - id: "P3"
    series: "Perigraphē"
    theorem: "Trokhia"
    name: "軌道"
    question: "What is the lifecycle?"
    focus: "このコードのライフサイクル・軌道は？初期化から破棄まで正しいか？"
    
  - id: "P4"
    series: "Perigraphē"
    theorem: "Tekhnē"
    name: "技法"
    question: "Is the technique appropriate?"
    focus: "使用されている技法・パターンは適切か？"

  # ---------------------------------------------------------------------------
  # K-series: Kairos (Context Theorems) — 時間・機会・文脈
  # ---------------------------------------------------------------------------
  - id: "K1"
    series: "Kairos"
    theorem: "Eukairia"
    name: "好機"
    question: "Is this the right time?"
    focus: "このコードを書く・変更するタイミングは適切か？"
    
  - id: "K2"
    series: "Kairos"
    theorem: "Chronos"
    name: "時間"
    question: "Are time constraints considered?"
    focus: "時間制約・期限は考慮されているか？タイムアウトは適切か？"
    
  - id: "K3"
    series: "Kairos"
    theorem: "Telos"
    name: "目的"
    question: "Is the purpose achieved?"
    focus: "このコードの目的は達成されるか？手段と目的が入れ替わっていないか？"
    
  - id: "K4"
    series: "Kairos"
    theorem: "Sophia"
    name: "知恵"
    question: "Is past wisdom applied?"
    focus: "過去の知恵・ベストプラクティスは活用されているか？"

  # ---------------------------------------------------------------------------
  # A-series: Akribeia (Precision Theorems) — 精度・判断・校正
  # ---------------------------------------------------------------------------
  - id: "A1"
    series: "Akribeia"
    theorem: "Pathos"
    name: "情念"
    question: "Is there emotional bias?"
    focus: "このコードに感情的なバイアス・過剰反応はないか？"
    
  - id: "A2"
    series: "Akribeia"
    theorem: "Krisis"
    name: "判定"
    question: "Is the judgment correct?"
    focus: "条件分岐・判断ロジックは正しいか？"
    
  - id: "A3"
    series: "Akribeia"
    theorem: "Gnōmē"
    name: "格言"
    question: "Are principles followed?"
    focus: "原則・格言・ベストプラクティスに従っているか？"
    
  - id: "A4"
    series: "Akribeia"
    theorem: "Epistēmē"
    name: "知識"
    question: "Is it based on verified knowledge?"
    focus: "確実な知識に基づいているか？推測ではないか？"

# ==============================================================================
# PROMPT TEMPLATE
# ==============================================================================
# Template for generating perspective-specific review prompts

prompt_template: |
  You are a {domain_name} specialist reviewing code through the lens of {axis_name} ({theorem}).
  
  ## Your Unique Perspective
  
  **Domain Focus:** {domain_description}
  **Cognitive Lens:** {axis_question}
  
  ## Review Protocol
  
  1. **Analyze** the code specifically from your perspective:
     - {axis_focus}
  
  2. **Identify** issues ONLY within your domain × axis intersection:
     - Domain keywords to watch: {domain_keywords}
     - Cognitive question to answer: {axis_question}
  
  3. **Report** findings in structured format:
     - Severity: [Critical / Major / Minor / Info]
     - Location: [file:line]
     - Issue: [specific finding]
     - Recommendation: [concrete action]
  
  ## Critical Rules
  
  - ❌ Do NOT report issues outside your domain ({domain_id})
  - ❌ Do NOT use cognitive lenses other than {axis_id} ({theorem})
  - ❌ Do NOT duplicate findings that another perspective would report
  - ✅ Report ONLY what YOU uniquely see from {domain_id} × {axis_id}
  
  ## Silence Protocol
  
  If you find nothing from your unique perspective, respond:
  
  ```
  SILENCE: No issues found from {domain_id} × {axis_id} perspective
  ```
  
  This is a valid outcome. Do not invent issues.

# ==============================================================================
# METADATA
# ==============================================================================

metadata:
  total_perspectives: 480  # 20 domains × 24 axes (full theorem coverage)
  redundancy: "0 (structurally orthogonal via direct product)"
  coverage: "Complete (20 domains × 24 theorems = full Hegemonikón coverage)"
  batch_size: 60  # Jules API rate limit per batch
  batches_required: 8  # 480 / 60 = 8 batches
