/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(g,k){g=g.split(".");for(var f=a,e;g.length&&(e=g.shift());)g.length||k===void 0?f=f[e]&&f[e]!==Object.prototype[e]?f[e]:f[e]={}:f[e]=k};var c={i:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},h:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},d=c;d=c;var h={ma:"y",ua:"y G",na:"MMM y",oa:"MMMM y",va:"MM/y",L:"MMM d",M:"MMMM dd",O:"M/d",N:"MMMM d",sa:"MMM d, y",ka:"EEE, MMM d",ta:"EEE, MMM d, y",o:"d",ra:"MMM d, h:mm\u202fa zzzz"},l=h;l=h;var m={C:["BC","AD"],B:["Before Christ","Anno Domini"],R:"JFMAMJJASOND".split(""),da:"JFMAMJJASOND".split(""),K:"January February March April May June July August September October November December".split(" "),ca:"January February March April May June July August September October November December".split(" "),Z:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),fa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ja:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ha:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ba:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ga:"Sun Mon Tue Wed Thu Fri Sat".split(" "),S:"SMTWTFS".split(""),ea:"SMTWTFS".split(""),aa:["Q1","Q2","Q3","Q4"],X:["1st quarter","2nd quarter","3rd quarter","4th quarter"],g:["AM","PM"],l:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ia:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],m:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],F:6,la:[5,
6],G:5},n=m;n=m;var p={v:".",H:",",T:"%",qa:"0",W:"+",J:"-",D:"E",V:"\u2030",I:"\u221e",P:"NaN",u:"#,##0.###",Y:"#E0",U:"#,##0%",j:"\u00a4#,##0.00",A:"USD"},q=p;q=p;b("I18N_DATETIMESYMBOLS_ERAS",n.C);b("I18N_DATETIMESYMBOLS_ERANAMES",n.B);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",n.R);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",n.da);b("I18N_DATETIMESYMBOLS_MONTHS",n.K);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",n.ca);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",n.Z);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",n.fa);b("I18N_DATETIMESYMBOLS_WEEKDAYS",n.ja);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",n.ha);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",n.ba);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",n.ga);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",n.S);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",n.ea);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",n.aa);b("I18N_DATETIMESYMBOLS_QUARTERS",n.X);b("I18N_DATETIMESYMBOLS_AMPMS",n.g);b("I18N_DATETIMESYMBOLS_DATEFORMATS",n.l);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",n.ia);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",n.m);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",n.F);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",n.la);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",n.G);b("I18N_DATETIMEPATTERNS_YEAR_FULL",l.ma);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",l.na);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",l.oa);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",l.L);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",l.M);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",l.O);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",l.N);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",l.ka);b("I18N_DATETIMEPATTERNS_DAY_ABBR",l.o);
n.pa!==void 0&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",n.pa);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",q.v);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",q.H);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",q.T);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",q.qa);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",q.W);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",q.J);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",q.D);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",q.V);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",q.I);b("I18N_NUMBERFORMATSYMBOLS_NAN",q.P);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",q.u);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",q.Y);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",q.U);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",q.j);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",q.A);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",d.i);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",d.h);
