/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(g,k){g=g.split(".");for(var f=a,e;g.length&&(e=g.shift());)g.length||k===void 0?f=f[e]&&f[e]!==Object.prototype[e]?f[e]:f[e]={}:f[e]=k};var c={i:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},h:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}};
c={i:{1E3:{other:"0"},1E4:{other:"0"},1E5:{other:"0"},1E6:{other:"0\u00a0M"},1E7:{other:"00\u00a0M"},1E8:{other:"000\u00a0M"},1E9:{other:"0000\u00a0M"},1E10:{other:"00000\u00a0M"},1E11:{other:"000000\u00a0M"},1E12:{other:"0\u00a0B"},1E13:{other:"00\u00a0B"},1E14:{other:"000\u00a0B"}},h:{1E3:{other:"0"},1E4:{other:"0"},1E5:{other:"0"},1E6:{other:"0 milioi"},1E7:{other:"00 milioi"},1E8:{other:"000 milioi"},1E9:{other:"0000 milioi"},1E10:{other:"00000 milioi"},1E11:{other:"000000 milioi"},1E12:{other:"0 bilioi"},
1E13:{other:"00 bilioi"},1E14:{other:"000 bilioi"}}};var d={ma:"y",ta:"y G",na:"MMM y",oa:"MMMM y",ua:"MM/y",L:"MMM d",M:"MMMM dd",O:"M/d",N:"MMMM d",ra:"MMM d, y",ka:"EEE, MMM d",sa:"EEE, MMM d, y",o:"d",qa:"MMM d, h:mm\u202fa zzzz"};d={ma:"y",ta:"G y",na:"y MMM",oa:"y('e')'ko' MMMM",ua:"y/MM",L:"MMM d('a')",M:"MMMM'ren' dd('a')",O:"M/d",N:"MMMM'ren' d('a')",ra:"y MMM d('a')",ka:"MMM d('a'), EEE",sa:"y MMM d('a'), EEE",o:"d",qa:"MMM d('a') (HH:mm zzzz)"};var h={C:["BC","AD"],B:["Before Christ","Anno Domini"],R:"JFMAMJJASOND".split(""),da:"JFMAMJJASOND".split(""),K:"January February March April May June July August September October November December".split(" "),ca:"January February March April May June July August September October November December".split(" "),Z:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),fa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ja:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ha:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ba:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ga:"Sun Mon Tue Wed Thu Fri Sat".split(" "),S:"SMTWTFS".split(""),ea:"SMTWTFS".split(""),aa:["Q1","Q2","Q3","Q4"],X:["1st quarter","2nd quarter","3rd quarter","4th quarter"],g:["AM","PM"],l:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ia:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],m:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],F:6,la:[5,
6],G:5};
h={C:["K.a.","K.o."],B:["Kristo aurretik","Kristo ondoren"],R:"UOMAMEUAIUAA".split(""),da:"UOMAMEUAIUAA".split(""),K:"urtarrila otsaila martxoa apirila maiatza ekaina uztaila abuztua iraila urria azaroa abendua".split(" "),ca:"urtarrila otsaila martxoa apirila maiatza ekaina uztaila abuztua iraila urria azaroa abendua".split(" "),Z:"urt. ots. mar. api. mai. eka. uzt. abu. ira. urr. aza. abe.".split(" "),fa:"urt. ots. mar. api. mai. eka. uzt. abu. ira. urr. aza. abe.".split(" "),ja:"igandea astelehena asteartea asteazkena osteguna ostirala larunbata".split(" "),ha:"igandea astelehena asteartea asteazkena osteguna ostirala larunbata".split(" "),
ba:"ig. al. ar. az. og. or. lr.".split(" "),ga:"ig. al. ar. az. og. or. lr.".split(" "),S:"IAAAOOL".split(""),ea:"IAAAOOL".split(""),aa:["1Hh","2Hh","3Hh","4Hh"],X:["1. hiruhilekoa","2. hiruhilekoa","3. hiruhilekoa","4. hiruhilekoa"],g:["AM","PM"],l:["y('e')'ko' MMMM'ren' d('a'), EEEE","y('e')'ko' MMMM'ren' d('a')","y('e')'ko' MMM d('a')","yy/M/d"],ia:["HH:mm:ss (zzzz)","HH:mm:ss (z)","HH:mm:ss","HH:mm"],m:["{1} ({0})","{1} ({0})","{1} ({0})","{1} ({0})"],F:0,la:[5,6],G:3};var l={v:".",H:",",T:"%",pa:"0",W:"+",J:"-",D:"E",V:"\u2030",I:"\u221e",P:"NaN",u:"#,##0.###",Y:"#E0",U:"#,##0%",j:"\u00a4#,##0.00",A:"USD"};l={v:",",H:".",T:"%",pa:"0",W:"+",J:"\u2212",D:"E",V:"\u2030",I:"\u221e",P:"NaN",u:"#,##0.###",Y:"#E0",U:"%\u00a0#,##0",j:"#,##0.00\u00a0\u00a4",A:"EUR"};b("I18N_DATETIMESYMBOLS_ERAS",h.C);b("I18N_DATETIMESYMBOLS_ERANAMES",h.B);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",h.R);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",h.da);b("I18N_DATETIMESYMBOLS_MONTHS",h.K);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",h.ca);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",h.Z);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",h.fa);b("I18N_DATETIMESYMBOLS_WEEKDAYS",h.ja);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",h.ha);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",h.ba);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",h.ga);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",h.S);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",h.ea);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",h.aa);b("I18N_DATETIMESYMBOLS_QUARTERS",h.X);b("I18N_DATETIMESYMBOLS_AMPMS",h.g);b("I18N_DATETIMESYMBOLS_DATEFORMATS",h.l);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",h.ia);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",h.m);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",h.F);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",h.la);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",h.G);b("I18N_DATETIMEPATTERNS_YEAR_FULL",d.ma);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",d.na);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",d.oa);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",d.L);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",d.M);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",d.O);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",d.N);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",d.ka);b("I18N_DATETIMEPATTERNS_DAY_ABBR",d.o);
h.va!==void 0&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",h.va);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",l.v);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",l.H);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",l.T);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",l.pa);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",l.W);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",l.J);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",l.D);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",l.V);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",l.I);b("I18N_NUMBERFORMATSYMBOLS_NAN",l.P);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",l.u);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",l.Y);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",l.U);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",l.j);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",l.A);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",c.i);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",c.h);
