/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(g,k){g=g.split(".");for(var f=a,e;g.length&&(e=g.shift());)g.length||k===void 0?f=f[e]&&f[e]!==Object.prototype[e]?f[e]:f[e]={}:f[e]=k};var c={pa:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},oa:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},d=c;d=c;var h={ka:"y",ta:"y G",la:"MMM y",ma:"MMMM y",ua:"MM/y",J:"MMM d",K:"MMMM dd",M:"M/d",L:"MMMM d",ra:"MMM d, y",ia:"EEE, MMM d",sa:"EEE, MMM d, y",l:"d",qa:"MMM d, h:mm\u202fa zzzz"};h={ka:"y",ta:"y G",la:"MMM y",ma:"MMMM y",ua:"y-MM",J:"MMM d",K:"MMMM dd",M:"MM-dd",L:"MMMM d",ra:"MMM d, y",ia:"EEE, MMM d",sa:"EEE, MMM d, y",l:"d",qa:"MMM d, h:mm\u202fa zzzz"};var l={A:["BC","AD"],v:["Before Christ","Anno Domini"],O:"JFMAMJJASOND".split(""),ba:"JFMAMJJASOND".split(""),I:"January February March April May June July August September October November December".split(" "),aa:"January February March April May June July August September October November December".split(" "),X:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),da:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ha:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
fa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),Z:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ea:"Sun Mon Tue Wed Thu Fri Sat".split(" "),P:"SMTWTFS".split(""),ca:"SMTWTFS".split(""),Y:["Q1","Q2","Q3","Q4"],V:["1st quarter","2nd quarter","3rd quarter","4th quarter"],g:["AM","PM"],i:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ga:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],j:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],C:6,ja:[5,6],
D:5};
l={A:["BC","AD"],v:["Before Christ","Anno Domini"],O:"JFMAMJJASOND".split(""),ba:"JFMAMJJASOND".split(""),I:"January February March April May June July August September October November December".split(" "),aa:"January February March April May June July August September October November December".split(" "),X:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),da:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ha:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),fa:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Z:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ea:"Sun Mon Tue Wed Thu Fri Sat".split(" "),P:"SMTWTFS".split(""),ca:"SMTWTFS".split(""),Y:["Q1","Q2","Q3","Q4"],V:["1st quarter","2nd quarter","3rd quarter","4th quarter"],g:["a.m.","p.m."],i:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","y-MM-dd"],ga:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],j:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],C:6,ja:[5,6],D:5};var m={o:".",F:",",R:"%",na:"0",U:"+",H:"-",B:"E",T:"\u2030",G:"\u221e",N:"NaN",m:"#,##0.###",W:"#E0",S:"#,##0%",h:"\u00a4#,##0.00",u:"USD"};m={o:".",F:",",R:"%",na:"0",U:"+",H:"-",B:"E",T:"\u2030",G:"\u221e",N:"NaN",m:"#,##0.###",W:"#E0",S:"#,##0%",h:"\u00a4#,##0.00",u:"CAD"};b("I18N_DATETIMESYMBOLS_ERAS",l.A);b("I18N_DATETIMESYMBOLS_ERANAMES",l.v);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",l.O);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",l.ba);b("I18N_DATETIMESYMBOLS_MONTHS",l.I);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",l.aa);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",l.X);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",l.da);b("I18N_DATETIMESYMBOLS_WEEKDAYS",l.ha);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",l.fa);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",l.Z);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",l.ea);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",l.P);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",l.ca);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",l.Y);b("I18N_DATETIMESYMBOLS_QUARTERS",l.V);b("I18N_DATETIMESYMBOLS_AMPMS",l.g);b("I18N_DATETIMESYMBOLS_DATEFORMATS",l.i);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",l.ga);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",l.j);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",l.C);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",l.ja);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",l.D);b("I18N_DATETIMEPATTERNS_YEAR_FULL",h.ka);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",h.la);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",h.ma);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",h.J);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",h.K);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",h.M);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",h.L);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",h.ia);b("I18N_DATETIMEPATTERNS_DAY_ABBR",h.l);
l.va!==void 0&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",l.va);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",m.o);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",m.F);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",m.R);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",m.na);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",m.U);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",m.H);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",m.B);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",m.T);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",m.G);b("I18N_NUMBERFORMATSYMBOLS_NAN",m.N);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",m.m);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",m.W);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",m.S);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",m.h);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",m.u);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",d.pa);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",d.oa);
