"""
Hegemonikón FEP Module

Active Inference implementation based on pymdp for cognitive processes.
"""

from .fep_agent import HegemonikónFEPAgent
from .state_spaces import (
    PHANTASIA_STATES,
    ASSENT_STATES,
    HORME_STATES,
    OBSERVATION_MODALITIES,
)
from .encoding import (
    encode_input,
    encode_structured_input,
    decode_observation,
    encode_noesis_output,
    encode_boulesis_output,
    generate_fep_feedback_markdown,
)
from .persistence import (
    save_A,
    load_A,
    A_exists,
    LEARNED_A_PATH,
)
from .fep_bridge import (
    noesis_analyze,
    boulesis_analyze,
    full_inference_cycle,
    NoesisResult,
    BoulesisResult,
)
from .llm_evaluator import (
    encode_input_with_confidence,
    hierarchical_evaluate,
    evaluate_and_infer,
    EvaluationResult,
    GEMINI_AVAILABLE,
)
from .config import (
    FEPParameters,
    load_parameters,
    get_default_params,
    reload_params,
)
from .telos_checker import (
    AlignmentStatus,
    TelосResult,
    check_alignment,
    format_telos_markdown,
    encode_telos_observation,
)
from .tekhne_registry import (
    TechniqueQuadrant,
    ActionCategory,
    Technique,
    TekhnēRegistry,
    STANDARD_TECHNIQUES,
    get_registry,
    search_techniques,
    format_registry_markdown,
)
from .energeia_executor import (
    ExecutionPhase,
    ExecutionStatus,
    ExecutionContext,
    ExecutionResult,
    EnergеiaExecutor,
    format_execution_markdown,
    encode_execution_observation,
)
from .chronos_evaluator import (
    TimeScale,
    CertaintyLevel,
    SlackLevel,
    ChronosResult,
    evaluate_time,
    format_chronos_markdown,
    encode_chronos_observation,
)
from .eukairia_detector import (
    OpportunityWindow,
    OpportunityScale,
    OpportunityDecision,
    OpportunityContext,
    EukairiaResult,
    detect_opportunity,
    format_eukairia_markdown,
    encode_eukairia_observation,
)
from .perigraphe_engine import (
    KhoraDerivative,
    ScopeScale,
    KhoraResult,
    HodosDerivative,
    HodosResult,
    TrokhiaDerivative,
    TrokhiaResult,
    define_scope,
    define_path,
    define_trajectory,
    format_khora_markdown,
    format_hodos_markdown,
    format_trokhia_markdown,
    encode_perigraphe_observation,
)
from .horme_evaluator import (
    PropatheiaDerivative,
    PropatheiaResult,
    PistisDerivative,
    PistisResult,
    OrexisDerivative,
    OrexisResult,
    evaluate_propatheia,
    evaluate_pistis,
    evaluate_orexis,
    format_propatheia_markdown,
    format_pistis_markdown,
    format_orexis_markdown,
    encode_horme_observation,
)
from .akribeia_evaluator import (
    PathosDerivative,
    PathosResult,
    GnomeDerivative,
    GnomeResult,
    EpistemeDerivative,
    EpistemeResult,
    evaluate_pathos,
    extract_gnome,
    evaluate_episteme,
    format_pathos_markdown,
    format_gnome_markdown,
    format_episteme_markdown,
    encode_akribeia_observation,
)
from .zetesis_inquirer import (
    ZetesisDerivative,
    QuestionType,
    ZetesisResult,
    inquire,
    format_zetesis_markdown,
    encode_zetesis_observation,
)
from .schema_analyzer import (
    MetronDerivative,
    ScaleLevel,
    MetronResult,
    StathmosDerivative,
    CriterionPriority,
    StathmosResult,
    PraxisDerivative,
    PraxisResult,
    analyze_scale,
    define_criteria,
    plan_praxis,
    format_metron_markdown,
    format_stathmos_markdown,
    format_praxis_markdown,
    encode_schema_observation,
)
from .doxa_persistence import (
    DoxaDerivative,
    BeliefStrength,
    Belief,
    DoxaResult,
    DoxaStore,
    get_store,
    format_doxa_markdown,
    encode_doxa_observation,
)
from .sophia_researcher import (
    SophiaDerivative,
    ResearchDepth,
    ResearchQuery,
    SophiaResult,
    research,
    format_sophia_markdown,
    encode_sophia_observation,
)
from .krisis_judge import (
    KrisisDerivative,
    VerdictType,
    Objection,
    KrisisResult,
    judge,
    epochē,
    format_krisis_markdown,
    encode_krisis_observation,
)

__all__ = [
    "HegemonikónFEPAgent",
    "PHANTASIA_STATES",
    "ASSENT_STATES",
    "HORME_STATES",
    "OBSERVATION_MODALITIES",
    "encode_input",
    "encode_structured_input",
    "decode_observation",
    "save_A",
    "load_A",
    "A_exists",
    "LEARNED_A_PATH",
    "noesis_analyze",
    "boulesis_analyze",
    "full_inference_cycle",
    "NoesisResult",
    "BoulesisResult",
    "encode_input_with_confidence",
    "hierarchical_evaluate",
    "evaluate_and_infer",
    "EvaluationResult",
    "GEMINI_AVAILABLE",
    "encode_noesis_output",
    "encode_boulesis_output",
    "generate_fep_feedback_markdown",
    "FEPParameters",
    "load_parameters",
    "get_default_params",
    "reload_params",
    # K3 Telos
    "AlignmentStatus",
    "TelосResult",
    "check_alignment",
    "format_telos_markdown",
    "encode_telos_observation",
    # P4 Tekhnē
    "TechniqueQuadrant",
    "ActionCategory",
    "Technique",
    "TekhnēRegistry",
    "STANDARD_TECHNIQUES",
    "get_registry",
    "search_techniques",
    "format_registry_markdown",
    # O4 Energeia
    "ExecutionPhase",
    "ExecutionStatus",
    "ExecutionContext",
    "ExecutionResult",
    "EnergеiaExecutor",
    "format_execution_markdown",
    "encode_execution_observation",
    # K2 Chronos
    "TimeScale",
    "CertaintyLevel",
    "SlackLevel",
    "ChronosResult",
    "evaluate_time",
    "format_chronos_markdown",
    "encode_chronos_observation",
    # K1 Eukairia
    "OpportunityWindow",
    "OpportunityScale",
    "OpportunityDecision",
    "OpportunityContext",
    "EukairiaResult",
    "detect_opportunity",
    "format_eukairia_markdown",
    "encode_eukairia_observation",
    # P1-P3 Perigraphē
    "KhoraDerivative",
    "ScopeScale",
    "KhoraResult",
    "HodosDerivative",
    "HodosResult",
    "TrokhiaDerivative",
    "TrokhiaResult",
    "define_scope",
    "define_path",
    "define_trajectory",
    "format_khora_markdown",
    "format_hodos_markdown",
    "format_trokhia_markdown",
    "encode_perigraphe_observation",
    # H1-H3 Hormē
    "PropatheiaDerivative",
    "PropatheiaResult",
    "PistisDerivative",
    "PistisResult",
    "OrexisDerivative",
    "OrexisResult",
    "evaluate_propatheia",
    "evaluate_pistis",
    "evaluate_orexis",
    "format_propatheia_markdown",
    "format_pistis_markdown",
    "format_orexis_markdown",
    "encode_horme_observation",
    # A1, A3, A4 Akribeia
    "PathosDerivative",
    "PathosResult",
    "GnomeDerivative",
    "GnomeResult",
    "EpistemeDerivative",
    "EpistemeResult",
    "evaluate_pathos",
    "extract_gnome",
    "evaluate_episteme",
    "format_pathos_markdown",
    "format_gnome_markdown",
    "format_episteme_markdown",
    "encode_akribeia_observation",
    # O3 Zētēsis
    "ZetesisDerivative",
    "QuestionType",
    "ZetesisResult",
    "inquire",
    "format_zetesis_markdown",
    "encode_zetesis_observation",
    # S1 Metron, S3 Stathmos, S4 Praxis
    "MetronDerivative",
    "ScaleLevel",
    "MetronResult",
    "StathmosDerivative",
    "CriterionPriority",
    "StathmosResult",
    "PraxisDerivative",
    "PraxisResult",
    "analyze_scale",
    "define_criteria",
    "plan_praxis",
    "format_metron_markdown",
    "format_stathmos_markdown",
    "format_praxis_markdown",
    "encode_schema_observation",
    # H4 Doxa
    "DoxaDerivative",
    "BeliefStrength",
    "Belief",
    "DoxaResult",
    "DoxaStore",
    "get_store",
    "format_doxa_markdown",
    "encode_doxa_observation",
    # K4 Sophia
    "SophiaDerivative",
    "ResearchDepth",
    "ResearchQuery",
    "SophiaResult",
    "research",
    "format_sophia_markdown",
    "encode_sophia_observation",
    # A2 Krisis
    "KrisisDerivative",
    "VerdictType",
    "Objection",
    "KrisisResult",
    "judge",
    "epochē",
    "format_krisis_markdown",
    "encode_krisis_observation",
]



