
import os
import sys
from playwright.sync_api import sync_playwright

def verify_aria_labels():
    # Use absolute path to the built index.html
    current_dir = os.getcwd()
    file_path = f"file://{current_dir}/hgk/dist/index.html"
    print(f"Navigating to: {file_path}")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()

        try:
            page.goto(file_path)

            # Wait for content to load (nav is generated by JS)
            page.wait_for_selector("#tab-nav-toggle")

            print("Checking ARIA labels...")

            # 1. Check Header Elements (Static & Dynamic)
            checks = [
                ("#tab-nav-toggle", "アシスタントペイン"),
                ("#slide-trigger", "アシスタントを開く"),
                ("#assistant-clear", "クリア"),
                ("#slide-panel-close", "閉じる"),
                ("#assistant-send", "送信")
            ]

            for selector, expected_label in checks:
                element = page.locator(selector)
                if element.count() > 0:
                    label = element.get_attribute("aria-label")
                    if label == expected_label:
                        print(f"[PASS] {selector}: aria-label='{label}'")
                    else:
                        print(f"[FAIL] {selector}: Expected '{expected_label}', found '{label}'")
                else:
                    print(f"[FAIL] {selector} not found")

            # 2. Check Dynamic Navigation Buttons (Generated by main.ts)
            # Use try-except for waiting, since main.ts execution might fail if API is unreachable
            try:
                page.wait_for_selector(".rail-btn", timeout=5000)

                # Check a few rail buttons
                rail_btns = page.locator(".rail-btn")
                count = rail_btns.count()
                print(f"Found {count} rail buttons")

                for i in range(count):
                    btn = rail_btns.nth(i)
                    label = btn.get_attribute("aria-label")
                    title = btn.get_attribute("title")
                    if label:
                        print(f"[PASS] Rail Button {i}: aria-label='{label}'")
                    else:
                        print(f"[FAIL] Rail Button {i} missing aria-label (Title: {title})")

                # Check tab buttons
                page.wait_for_selector(".tab-btn", timeout=5000)
                tab_btns = page.locator(".tab-btn")
                tab_count = tab_btns.count()
                print(f"Found {tab_count} tab buttons")

                for i in range(tab_count):
                    btn = tab_btns.nth(i)
                    label = btn.get_attribute("aria-label")
                    if label:
                        print(f"[PASS] Tab Button {i}: aria-label='{label}'")
                    else:
                        print(f"[FAIL] Tab Button {i} missing aria-label")

            except Exception as e:
                print(f"Warning: Could not verify dynamic content (likely due to missing backend/API): {e}")
                print("Proceeding with static check verification.")

            # Take a screenshot for visual confirmation of the UI
            page.screenshot(path=".verification/accessibility_check.png")
            print("Screenshot saved to .verification/accessibility_check.png")

        except Exception as e:
            print(f"Error: {e}")
        finally:
            browser.close()

if __name__ == "__main__":
    verify_aria_labels()
