/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Tauri ヘルスチェック用の軽量エンドポイント。
         */
        get: operations["health_check_api_status_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full Status
         * @description 全サービスの詳細ヘルスレポート。
         *
         *     systemd/docker コマンドを呼ぶため非同期スレッドで実行。
         */
        get: operations["full_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fep/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fep Step
         * @description 推論-行動サイクルを1ステップ実行。
         */
        post: operations["fep_step_api_fep_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fep/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fep State
         * @description Agent の現在の内部状態を取得。
         */
        get: operations["fep_state_api_fep_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fep/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fep Dashboard
         * @description FEP ダッシュボードデータを取得。
         */
        get: operations["fep_dashboard_api_fep_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/postcheck/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Postcheck
         * @description ワークフロー出力の品質検証を実行。
         */
        post: operations["run_postcheck_api_postcheck_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/postcheck/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sel
         * @description 全WF の sel_enforcement を一覧表示。
         */
        get: operations["list_sel_api_postcheck_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dendron/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dendron Report
         * @description Dendron コード品質レポート。
         */
        get: operations["dendron_report_api_dendron_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dendron/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dendron Check
         * @description 個別ファイルの PROOF チェック。
         */
        post: operations["dendron_check_api_dendron_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gnosis/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gnosis Search
         * @description Gnōsis ベクトル検索。
         */
        get: operations["gnosis_search_api_gnosis_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gnosis/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gnosis Stats
         * @description Gnōsis インデックス統計。
         */
        get: operations["gnosis_stats_api_gnosis_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DendronCheckRequest
         * @description 個別ファイルチェックリクエスト。
         */
        DendronCheckRequest: {
            /**
             * Path
             * @description チェック対象のファイルパス
             */
            path: string;
        };
        /**
         * DendronCheckResponse
         * @description 個別ファイルチェック結果。
         */
        DendronCheckResponse: {
            /** Path */
            path: string;
            result?: components["schemas"]["DendronFileResult"] | null;
            /**
             * Error
             * @default
             */
            error: string;
        };
        /**
         * DendronFileResult
         * @description 個別ファイルのチェック結果。
         */
        DendronFileResult: {
            /** Path */
            path: string;
            /** Has Proof */
            has_proof: boolean;
            /**
             * Level
             * @default
             */
            level: string;
            /**
             * Parent
             * @default
             */
            parent: string;
            /**
             * Issues
             * @default []
             */
            issues: string[];
        };
        /**
         * DendronReportResponse
         * @description Dendron レポート。
         */
        DendronReportResponse: {
            summary: components["schemas"]["DendronSummary"];
            /**
             * File Results
             * @description detail=full 時のみ展開
             */
            file_results?: components["schemas"]["DendronFileResult"][];
        };
        /**
         * DendronSummary
         * @description Dendron レポートサマリー。
         */
        DendronSummary: {
            /**
             * Total Files
             * @default 0
             */
            total_files: number;
            /**
             * Files With Proof
             * @default 0
             */
            files_with_proof: number;
            /**
             * Files Without Proof
             * @default 0
             */
            files_without_proof: number;
            /**
             * Coverage Percent
             * @default 0
             */
            coverage_percent: number;
            /**
             * Total Dirs
             * @default 0
             */
            total_dirs: number;
            /**
             * Dirs With Proof
             * @default 0
             */
            dirs_with_proof: number;
            /**
             * Issues
             * @default []
             */
            issues: string[];
        };
        /**
         * FEPDashboardResponse
         * @description ダッシュボード分析データ。
         */
        FEPDashboardResponse: {
            /**
             * Total Steps
             * @default 0
             */
            total_steps: number;
            /**
             * Action Distribution
             * @default {}
             */
            action_distribution: {
                [key: string]: number;
            };
            /**
             * Series Distribution
             * @default {}
             */
            series_distribution: {
                [key: string]: number;
            };
            /**
             * Available
             * @default true
             */
            available: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * FEPStateResponse
         * @description Agent の内部状態。
         */
        FEPStateResponse: {
            /** Beliefs */
            beliefs: number[];
            /** Epsilon */
            epsilon: {
                [key: string]: number;
            };
            /** History Length */
            history_length: number;
            /** Precision Weights */
            precision_weights?: {
                [key: string]: number;
            } | null;
        };
        /**
         * FEPStepRequest
         * @description FEP step リクエスト。
         */
        FEPStepRequest: {
            /**
             * Observation
             * @description 観測インデックス (0-47)
             */
            observation: number;
        };
        /**
         * FEPStepResponse
         * @description FEP step 結果。
         */
        FEPStepResponse: {
            /** Action Name */
            action_name: string;
            /** Action Index */
            action_index: number;
            /** Selected Series */
            selected_series?: string | null;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /** Beliefs Entropy */
            beliefs_entropy?: number | null;
        };
        /**
         * GnosisSearchResponse
         * @description 検索レスポンス。
         */
        GnosisSearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["GnosisSearchResult"][];
            /** Total */
            total: number;
        };
        /**
         * GnosisSearchResult
         * @description 検索結果1件。
         */
        GnosisSearchResult: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Authors
             * @default
             */
            authors: string;
            /**
             * Abstract
             * @default
             */
            abstract: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Citations
             * @default
             */
            citations: string;
            /** Score */
            score?: number | null;
        };
        /**
         * GnosisStatsResponse
         * @description インデックス統計。
         */
        GnosisStatsResponse: {
            /**
             * Total
             * @default 0
             */
            total: number;
            /**
             * Unique Dois
             * @default 0
             */
            unique_dois: number;
            /**
             * Unique Arxiv
             * @default 0
             */
            unique_arxiv: number;
            /**
             * Sources
             * @default {}
             */
            sources: {
                [key: string]: number;
            };
            /**
             * Last Collected
             * @default
             */
            last_collected: string;
            /**
             * Available
             * @default true
             */
            available: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheckResponse
         * @description 軽量ヘルスチェック。
         */
        HealthCheckResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Version
             * @default
             */
            version: string;
            /**
             * Uptime Seconds
             * @default 0
             */
            uptime_seconds: number;
        };
        /**
         * HealthItemResponse
         * @description 個別ヘルスチェック結果。
         */
        HealthItemResponse: {
            /** Name */
            name: string;
            /**
             * Status
             * @description ok | warn | error | unknown
             */
            status: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Metric */
            metric?: number | null;
            /**
             * Emoji
             * @default
             */
            emoji: string;
        };
        /**
         * HealthReportResponse
         * @description 全体ヘルスレポート。
         */
        HealthReportResponse: {
            /** Timestamp */
            timestamp: string;
            /** Items */
            items: components["schemas"]["HealthItemResponse"][];
            /**
             * Score
             * @description 0.0-1.0 総合スコア
             */
            score: number;
        };
        /**
         * PostcheckRequest
         * @description ポストチェック実行リクエスト。
         */
        PostcheckRequest: {
            /**
             * Wf Name
             * @description ワークフロー名 (例: dia, noe, boot)
             */
            wf_name: string;
            /**
             * Mode
             * @description モード (+, -, *, 空)
             * @default
             */
            mode: string;
            /**
             * Content
             * @description チェック対象テキスト
             */
            content: string;
        };
        /**
         * PostcheckResponse
         * @description ポストチェック結果。
         */
        PostcheckResponse: {
            /** Wf Name */
            wf_name: string;
            /** Mode */
            mode: string;
            /** Passed */
            passed: boolean;
            /** Checks */
            checks: components["schemas"]["PostcheckResult"][];
            /**
             * Formatted
             * @default
             */
            formatted: string;
        };
        /**
         * PostcheckResult
         * @description 個別チェック結果。
         */
        PostcheckResult: {
            /** Requirement */
            requirement: string;
            /** Passed */
            passed: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * SELItem
         * @description SEL enforcement 項目。
         */
        SELItem: {
            /** Wf Name */
            wf_name: string;
            /**
             * Modes
             * @default {}
             */
            modes: {
                [key: string]: unknown;
            };
        };
        /**
         * SELListResponse
         * @description 全WF の SEL enforcement 一覧。
         */
        SELListResponse: {
            /** Items */
            items: components["schemas"]["SELItem"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_status_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
    full_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReportResponse"];
                };
            };
        };
    };
    fep_step_api_fep_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FEPStepRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FEPStepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fep_state_api_fep_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FEPStateResponse"];
                };
            };
        };
    };
    fep_dashboard_api_fep_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FEPDashboardResponse"];
                };
            };
        };
    };
    run_postcheck_api_postcheck_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostcheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostcheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sel_api_postcheck_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SELListResponse"];
                };
            };
        };
    };
    dendron_report_api_dendron_report_get: {
        parameters: {
            query?: {
                /** @description summary | full */
                detail?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DendronReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dendron_check_api_dendron_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DendronCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DendronCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gnosis_search_api_gnosis_search_get: {
        parameters: {
            query: {
                /** @description 検索クエリ */
                q: string;
                /** @description 結果件数 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnosisSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gnosis_stats_api_gnosis_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GnosisStatsResponse"];
                };
            };
        };
    };
}
