# PROOF: [Level/Category] <- mekhane/ochema/proto/ A0->Auto->AddedByCI
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import extension_server_pb2 as extension__server__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in extension_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExtensionServerServiceStub(object):
    """Minimal service definition - only what LS needs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeToUnifiedStateSyncTopic = channel.unary_stream(
                '/exa.extension_server_pb.ExtensionServerService/SubscribeToUnifiedStateSyncTopic',
                request_serializer=extension__server__pb2.SubscribeToUnifiedStateSyncTopicRequest.SerializeToString,
                response_deserializer=extension__server__pb2.UnifiedStateSyncUpdate.FromString,
                _registered_method=True)
        self.PushUnifiedStateSyncUpdate = channel.unary_unary(
                '/exa.extension_server_pb.ExtensionServerService/PushUnifiedStateSyncUpdate',
                request_serializer=extension__server__pb2.PushUnifiedStateSyncUpdateRequest.SerializeToString,
                response_deserializer=extension__server__pb2.PushUnifiedStateSyncUpdateResponse.FromString,
                _registered_method=True)
        self.LanguageServerStarted = channel.unary_unary(
                '/exa.extension_server_pb.ExtensionServerService/LanguageServerStarted',
                request_serializer=extension__server__pb2.LanguageServerStartedRequest.SerializeToString,
                response_deserializer=extension__server__pb2.LanguageServerStartedResponse.FromString,
                _registered_method=True)
        self.RecordError = channel.unary_unary(
                '/exa.extension_server_pb.ExtensionServerService/RecordError',
                request_serializer=extension__server__pb2.RecordErrorRequest.SerializeToString,
                response_deserializer=extension__server__pb2.RecordErrorResponse.FromString,
                _registered_method=True)


class ExtensionServerServiceServicer(object):
    """Minimal service definition - only what LS needs
    """

    def SubscribeToUnifiedStateSyncTopic(self, request, context):
        """Critical: LS calls this to subscribe to state updates (OAuth token)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushUnifiedStateSyncUpdate(self, request, context):
        """LS calls this to push state updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LanguageServerStarted(self, request, context):
        """LS calls this on startup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordError(self, request, context):
        """LS calls this to report errors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExtensionServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeToUnifiedStateSyncTopic': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUnifiedStateSyncTopic,
                    request_deserializer=extension__server__pb2.SubscribeToUnifiedStateSyncTopicRequest.FromString,
                    response_serializer=extension__server__pb2.UnifiedStateSyncUpdate.SerializeToString,
            ),
            'PushUnifiedStateSyncUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PushUnifiedStateSyncUpdate,
                    request_deserializer=extension__server__pb2.PushUnifiedStateSyncUpdateRequest.FromString,
                    response_serializer=extension__server__pb2.PushUnifiedStateSyncUpdateResponse.SerializeToString,
            ),
            'LanguageServerStarted': grpc.unary_unary_rpc_method_handler(
                    servicer.LanguageServerStarted,
                    request_deserializer=extension__server__pb2.LanguageServerStartedRequest.FromString,
                    response_serializer=extension__server__pb2.LanguageServerStartedResponse.SerializeToString,
            ),
            'RecordError': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordError,
                    request_deserializer=extension__server__pb2.RecordErrorRequest.FromString,
                    response_serializer=extension__server__pb2.RecordErrorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exa.extension_server_pb.ExtensionServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exa.extension_server_pb.ExtensionServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExtensionServerService(object):
    """Minimal service definition - only what LS needs
    """

    @staticmethod
    def SubscribeToUnifiedStateSyncTopic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/exa.extension_server_pb.ExtensionServerService/SubscribeToUnifiedStateSyncTopic',
            extension__server__pb2.SubscribeToUnifiedStateSyncTopicRequest.SerializeToString,
            extension__server__pb2.UnifiedStateSyncUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushUnifiedStateSyncUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.extension_server_pb.ExtensionServerService/PushUnifiedStateSyncUpdate',
            extension__server__pb2.PushUnifiedStateSyncUpdateRequest.SerializeToString,
            extension__server__pb2.PushUnifiedStateSyncUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LanguageServerStarted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.extension_server_pb.ExtensionServerService/LanguageServerStarted',
            extension__server__pb2.LanguageServerStartedRequest.SerializeToString,
            extension__server__pb2.LanguageServerStartedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.extension_server_pb.ExtensionServerService/RecordError',
            extension__server__pb2.RecordErrorRequest.SerializeToString,
            extension__server__pb2.RecordErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
