# Hegemonikón ワークフロー一覧

> **スナップショット日時**: 2026-01-29 10:36
> **総ワークフロー数**: 46
> **派生付きワークフロー**: 5 (O-series)
> **総派生数**: 12 (O1:3, O2:3, O3:3, O4:3)

---

## 命名規則遵守状況

| 階層 | 文字数 | 規則 | 遵守 |
|:-----|:-------|:-----|:-----|
| **Ω (Omega)** | 1-2 | 定理群統合 | ✅ |
| **Δ (Delta)** | 3 | ドメイン専門家 | ✅ |
| **τ (Tau)** | 3-4 | 個別タスク | ✅ |
| **特殊** | 1 | `/u` のみ | ✅ |

---

## O-series (Ousia / 本質)

| Workflow | Module | 派生 | Version |
|:---------|:-------|:-----|:--------|
| `/noe` | O1 Noēsis | **nous, phro, meta** | 4.1 |
| `/bou` | O2 Boulēsis | **desir, voli, akra** | 4.1 |
| `/zet` | O3 Zētēsis | **anom, hypo, eval** | 5.1 |
| `/ene` | O4 Energeia | **flow, prax, pois** | 4.1 |
| `/o` | Hub (O1-O4) | 全12派生 | 2.0 |
| `/poc` | O3 派生 | — | 1.0 |
| `/why` | O3 派生 | — | 1.0 |
| `/pre` | O2 派生 | — | 1.0 |
| `/flag` | O4 派生 | — | 1.0 |

---

## S-series (Schema / 様態)

| Workflow | Module | Version |
|:---------|:-------|:--------|
| `/s` | Hub (S1-S4) | 4.1 |
| `/met` | S1 Metron | 1.0 |
| `/mek` | S2 Mekhanē | 6.0 |
| `/sta` | S3 Stathmos | 1.0 |
| `/pra` | S4 Praxis | 1.0 |

---

## H-series (Hormē / 傾向)

| Workflow | Module | Version |
|:---------|:-------|:--------|
| `/h` | Hub (H1-H4) | 3.0 |
| `/pro` | H1 Propatheia | 1.0 |
| `/pis` | H2 Pistis | 1.0 |
| `/ore` | H3 Orexis | 1.0 |
| `/dox` | H4 Doxa | 1.0 |

---

## P-series (Perigraphē / 条件)

| Workflow | Module | Version |
|:---------|:-------|:--------|
| `/p` | Hub (P1-P4) | 2.3 |
| `/kho` | P1 Khōra | 1.0 |
| `/hod` | P2 Hodos | 1.0 |
| `/tro` | P3 Trokhia | 1.0 |
| `/tek` | P4 Tekhnē | 1.0 |

---

## K-series (Kairos / 文脈)

| Workflow | Module | Version |
|:---------|:-------|:--------|
| `/k` | Hub (K1-K4) | 3.0 |
| `/euk` | K1 Eukairia | 1.0 |
| `/chr` | K2 Chronos | 1.0 |
| `/tel` | K3 Telos | 3.0 |
| `/sop` | K4 Sophia | 5.1 |

---

## A-series (Akribeia / 精密)

| Workflow | Module | Version |
|:---------|:-------|:--------|
| `/a` | Hub (A1-A4) | 2.3 |
| `/pat` | A1 Pathos | 1.0 |
| `/dia` | A2 Krisis | 5.0 |
| `/gno` | A3 Gnōmē | 1.0 |
| `/epi` | A4 Epistēmē | 1.0 |
| `/epo` | A2 派生 (Epochē) | 2.0 |
| `/pan` | A2 派生 (Panorama) | 3.0 |
| `/syn` | A2 派生 (Synedrion) | 3.0 |
| `/fit` | A2 派生 (Digestion) | 3.1 |
| `/vet` | A2 派生 (Cross-Model) | 2.1 |

---

## X-series (関係層)

| Workflow | Module | Version |
|:---------|:-------|:--------|
| `/x` | 36 Relations | 5.1 |
| `/ax` | 統合オーケストレーター | 2.3 |

---

## Utils / 特殊

| Workflow | 目的 | Version |
|:---------|:-----|:--------|
| `/boot` | セッション開始 | 3.0 |
| `/bye` | セッション終了 | 2.6 |
| `/dev` | 開発プロトコル参照 | 1.1 |
| `/u` | 意見要求 | 2.1 |
| `/eat` | コンテンツ消化 | 1.0 |

---

## O-series 派生マトリクス（12派生）

| 定理 | 派生1 | 派生2 | 派生3 |
|:-----|:------|:------|:------|
| **O1 Noēsis** | nous (直観) | phro (実践知) | meta (自己反省) |
| **O2 Boulēsis** | desir (欲動) | voli (意志統合) | akra (自制) |
| **O3 Zētēsis** | anom (異常検出) | hypo (仮説生成) | eval (評価) |
| **O4 Energeia** | flow (流れ) | prax (実践) | pois (創造) |

---

## 統計

| カテゴリ | 数 |
|:---------|:---|
| O-series | 9 |
| S-series | 5 |
| H-series | 5 |
| P-series | 5 |
| K-series | 5 |
| A-series | 10 |
| X-series | 2 |
| Utils | 5 |
| **合計** | **46** |

---

*Generated by /bou → workflow inventory task — 2026-01-29*
