#!/bin/bash
# PROOF: [L2/インフラ] <- mekhane/anamnesis/mk-bye.sh
#
# /bye ワークフローのオーケストレーター (v2.0)
# 1. Handoff ファイル直接保存 (ローカル — 常に成功)
# 2. チャット履歴エクスポート (export_chats.py)
# 3. Slack 通知 (curl — 非同期)
# 4. n8n Webhook 通知 (オプション — 失敗しても継続)
#
# Usage:
#   ./mk-bye.sh [主題(オプション)]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HEGEMONIKON_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
VENV_PYTHON="$HEGEMONIKON_DIR/.venv/bin/python"
EXPORT_SCRIPT="$SCRIPT_DIR/export_chats.py"
N8N_WEBHOOK_URL="http://localhost:5678/webhook/bye-handoff"
HANDOFF_DIR="$HOME/oikos/mneme/.hegemonikon/handoffs"

# Slack Webhook
SLACK_WEBHOOK_URL=""
if [ -f "$HEGEMONIKON_DIR/.env" ]; then
    SLACK_WEBHOOK_URL=$(grep '^SLACK_WEBHOOK_URL=' "$HEGEMONIKON_DIR/.env" | cut -d= -f2 | tr -d '"')
fi

# コンテキスト（主題）
SUBJECT="$1"
if [ -z "$SUBJECT" ]; then
    SUBJECT="Auto-generated Handoff"
fi

TIMESTAMP=$(date +%Y%m%d_%H%M)
DATE_ISO=$(date -Iseconds)

echo "=== /bye Sequence Initiated ==="
echo "Subject: $SUBJECT"

# 1. Handoff ファイル直接保存 (最優先)
echo "[1/4] 💾 Saving Handoff locally..."
mkdir -p "$HANDOFF_DIR"

# サブジェクトからファイル名安全な文字列を生成
SAFE_SUBJECT=$(echo "$SUBJECT" | sed 's/[^a-zA-Z0-9_-]/_/g' | head -c 50)
HANDOFF_FILE="$HANDOFF_DIR/handoff_${TIMESTAMP}_${SAFE_SUBJECT}.md"

cat > "$HANDOFF_FILE" <<EOF
# Handoff: ${SUBJECT}

> **日時**: $(date '+%Y-%m-%d %H:%M')
> **Agent**: Claude (Antigravity)
> **Generated by**: mk-bye.sh v2.0

---

## セッション概要

主題: ${SUBJECT}

---

*Handoff generated: ${DATE_ISO}*
EOF

echo "  Saved: $HANDOFF_FILE"

# 2. Export Chat History
echo "[2/4] 📤 Exporting chat history..."
if [ -x "$VENV_PYTHON" ] && [ -f "$EXPORT_SCRIPT" ]; then
    if "$VENV_PYTHON" "$EXPORT_SCRIPT" --single "$SUBJECT" --format md 2>/dev/null; then
        echo "  Chat export successful."
    else
        echo "  Chat export failed. Continuing..."
    fi
else
    echo "  Export script not available. Skipping..."
fi

# 3. Slack 通知 (非同期 — ハングしない)
echo "[3/4] 📱 Slack notification..."
if [ -n "$SLACK_WEBHOOK_URL" ]; then
    curl -s -X POST "$SLACK_WEBHOOK_URL" \
        -H "Content-type: application/json" \
        -d "{\"text\": \"👋 */bye* — ${SUBJECT}\n📄 Handoff: $(basename "$HANDOFF_FILE")\"}" \
        --connect-timeout 3 --max-time 5 &>/dev/null &
    echo "  Slack: notified (background)"
else
    echo "  Slack: webhook not configured"
fi

# 4. n8n Webhook (オプション — 失敗しても問題なし)
echo "[4/4] 🔗 n8n Webhook..."
RESPONSE=$(curl -s -X POST "$N8N_WEBHOOK_URL" \
    -H "Content-Type: application/json" \
    -d "{\"subject\": \"$SUBJECT\", \"timestamp\": \"$DATE_ISO\", \"handoff_file\": \"$HANDOFF_FILE\"}" \
    --connect-timeout 3 --max-time 5 2>/dev/null || echo "unreachable")

if [ "$RESPONSE" = "unreachable" ]; then
    echo "  n8n: unreachable (local save successful, this is optional)"
else
    echo "  n8n: $RESPONSE"
fi

# デスクトップ通知
if command -v notify-send &>/dev/null; then
    notify-send -u critical -i dialog-information \
        "👋 /bye Sequence Complete" \
        "Subject: $SUBJECT" 2>/dev/null &
fi

echo "=== /bye Sequence Completed ==="
